### ISSUE TITLE
Unable to use v1.1.1.1 in HUAWEI MATE20 Pro (EMUI9.1.0.135)

### ISSUE THREAD

**Issue by hkx303** [TonyJiangWJ/Ant-Forest#1]
Hi,
1.1.1.0版本在华为MATE20 Pro EMUI9.1.0.135 无法正常使用
提示为：进入好友排行榜失败
日志信息：
![594460268](https://user-images.githubusercontent.com/46016760/70111608-bde01300-168d-11ea-8fd2-b4779b38194d.jpg)

**Comment by TonyJiangWJ** [comment]
基于图像识别的已经上线，没有发布release，直接下载代码 然后运行config.js 在`进阶配置`中勾选`基于图像分析`选项即可，当前还是测试性功能

**Comment by hkx303** [comment]
> 基于图像识别的已经上线，没有发布release，直接下载代码 然后运行config.js 在`进阶配置`中勾选`基于图像分析`选项即可，当前还是测试性功能

![Screenshot_20191211_163347_org autojs autojs](https://user-images.githubusercontent.com/46016760/70604743-18e8ab80-1c34-11ea-9a2a-0a7664d25d18.jpg)
下载代码，运行config.js后勾选`基于图像分析`
运行`main.js`报错，日志如上

**Comment by TonyJiangWJ** [comment]
- 查看`lib/autojs-tools.dex`是否存在
- 然后强制关闭AutoJS软件后重新开始
- 新的图像分析方法调用了封装的Java方法，因为AutoJS中纯JS实现的BitMap实在太慢了

**Comment by hkx303** [comment]
强行重启应用后可以运行。但发现了如下问题:

1、打开总排行榜滑动至第二十位好友时，报错
     报错时的错误提示：
     获取截图失败多次[3]，可能已经没有了截图权限，重新执行脚本。

2、打开总排行榜滑动至第二十位好友时，直接退出，本轮收取完毕

3、打开总排行后重复进入一能量待成熟标志的好友界面，重复几次后退出，收取完毕

版本暂未release，提供些信息哈，作者加油

**Comment by TonyJiangWJ** [comment]
哦对了 忘了说了 
图像识别开启的同时 得同时开启 `是否启用模拟滑动` 然后 `滑动速度（ms）`修改为`200`
`排行榜下拉次数`按实际好友数修改大概比例为 100个好友`13-15` 保险起见设置大一些也没事 就是会在底部滑动很多次 后续找办法解决判定是否到达列表底部
先这么改着，今晚会继续更新一些代码
