### ISSUE TITLE
永不停止模式下，脚本在下次运行之前错误退出并没有重新启动

### ISSUE THREAD

**Issue by chilllyn** [TonyJiangWJ/Ant-Forest#100]
![微信图片_20210506150447](https://user-images.githubusercontent.com/55988394/117255734-942bac80-ae7c-11eb-9168-56109ca8931a.jpg)

**Comment by TonyJiangWJ** [comment]
这个属于致命错误了 脚本自己重启也没用的那种，需要强杀AutoJS或者重启手机，建议使用我修改的版本[AutoJS Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk)
