### ISSUE TITLE
双击能量卡无法触发

### ISSUE THREAD

**Issue by kjif1993** [TonyJiangWJ/Ant-Forest#104]
小米11双击能量卡设置了，也一直无法触发

**Comment by oneyh** [comment]
我这边也一直无法触发

**Comment by TonyJiangWJ** [comment]
可能有误解，双击卡功能只是启用后会在收集一遍后二次校验避免漏收二次收集，并不是脚本触发使用双击卡。

**Comment by kjif1993** [comment]
> 可能有误解，双击卡功能只是启用后会在收集一遍后二次校验避免漏收二次收集，并不是脚本触发使用双击卡。

原来如此，谢谢解答~
