### ISSUE TITLE
能量雨漏收严重

### ISSUE THREAD

**Issue by oneyh** [TonyJiangWJ/Ant-Forest#105]
手机 华为mate20Pro  系统EMUI11  autojs使用项目推荐版本  支付宝版本10.2.20
红包雨前几秒命中率较高，之后就基本上命不中了，一场红包雨下来只有30g能量

**Comment by TonyJiangWJ** [comment]
更新到最新版试一下

**Comment by oneyh** [comment]
> 更新到最新版试一下

试了，效果不好。

**Comment by TonyJiangWJ** [comment]
也还是只有30吗

**Comment by Rongronggg9** [comment]
最新版前半段收得挺好，后半段会全部漏掉，看光标信息发现点击点相对于能量球越来越高，直至脱离能量球，是不是蚂蚁森林给能量雨加了逐渐加速的效果？

**Comment by TonyJiangWJ** [comment]
我实现的方向错了 性能跟不上 暂时不会更新了 你们可以用一下这个项目里面的能量雨模块 [https://github.com/SuperMonster003/Ant-Forest](https://github.com/SuperMonster003/Ant-Forest)
