### ISSUE TITLE
小米11 210528 开发版内测系统启动项目失败

### ISSUE THREAD

**Issue by kjif1993** [TonyJiangWJ/Ant-Forest#106]
小米11 210528日期的开发版内测版本， 在启动项目时提示“请求截图失败”。具体详见附件。  是在此界面卡住的
![Screenshot_2021-05-28-17-15-12-595_com android systemui](https://user-images.githubusercontent.com/82137561/119961797-05bccd80-bfd9-11eb-813f-aa6225741b96.jpg)

日志也在附件中。  大佬有空能就帮忙看看原因，更新前都是一直正常的。

**Comment by kjif1993** [comment]
![Screenshot_2021-05-28-17-15-12-595_com android systemui](https://user-images.githubusercontent.com/82137561/119962267-719f3600-bfd9-11eb-8aab-f57c712e15fb.jpg)
![IMG_20210528_171453](https://user-images.githubusercontent.com/82137561/119962271-72d06300-bfd9-11eb-87dc-801045f295a1.jpg)
![IMG_20210528_171445](https://user-images.githubusercontent.com/82137561/119962273-7368f980-bfd9-11eb-81fe-29797dd32dd9.jpg)

**Comment by TonyJiangWJ** [comment]
尝试强制重启AutoJS，从最近任务中长按并强制停止
如果还是不行的话尝试一下[这个版本的AutoJS](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk)

**Comment by kjif1993** [comment]
> 尝试强制重启AutoJS，从最近任务中长按并强制停止
> 如果还是不行的话尝试一下[这个版本的AutoJS](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk)


两种方式都尝试了下，发现还是不行~

**Comment by TonyJiangWJ** [comment]
尝试直接修改 `lib/prototype/RequestScreenCapture.js`
第40行增加 `requestSuccess = true` 试试能否正常运行，如果不行的话只能关闭自动授权
```javascript
  let requestThread = threads.start(function () {
    requestSuccess = requestScreenCapture(landscape)
    // 直接设置为true
    requestSuccess = true
    countDown.countDown()
  })
```

**Comment by TonyJiangWJ** [comment]
原因找到了 动画过度时获取了错误的位置导致无法正确点击
在 lib/prototype/RequestScreenCapture.js 第16行增加sleep(1000)即可
![image](https://user-images.githubusercontent.com/11325805/120737688-1d3c0f00-c521-11eb-8f11-a764f25ffb8c.png)

**Comment by kjif1993** [comment]
> 原因找到了 动画过度时获取了错误的位置导致无法正确点击
> 在 lib/prototype/RequestScreenCapture.js 第16行增加sleep(1000)即可
> ![image](https://user-images.githubusercontent.com/11325805/120737688-1d3c0f00-c521-11eb-8f11-a764f25ffb8c.png)

刚下载最新的1.5.5版本，添加了16行代码，测试还是不行，不知道是手机哪里的配置有点问题

**Comment by TonyJiangWJ** [comment]
试一下新版本看看能不能授权？

**Comment by kjif1993** [comment]
> 试一下新版本看看能不能授权？

已能正常授权，测试需要清楚软件数据才可以，只是更新版本也不能识别！应该有应用缓存
