### ISSUE TITLE
Autojs软件版本问题

### ISSUE THREAD

**Issue by NotRodeo** [TonyJiangWJ/Ant-Forest#107]
如题，如果用4.1.1版本，会在好友列表底端不停滑动最后报错退出，如果用M修改版，又无法创建定时任务，日志里连启动记录都没有，而且修改版不能打开音量上停止脚本，否则软件就会闪退需要清除数据。

**Comment by TonyJiangWJ** [comment]
什么手机，系统版本是什么？
尝试重置默认配置，并关闭模拟滑动试试

**Comment by TonyJiangWJ** [comment]
另外提供一下运行日志logs/log-verboses.log

**Comment by NotRodeo** [comment]
魅族18pro，flyme9，安卓11
4.1.1通过打开模拟滑动暂时解决了，不过以前也经常出现这种问题……都是直接清除app数据解决的
M版还是没法定时，而且那个log里面什么数据都没有，到了设置的时间，息屏状态没有任何反应，必须手动解锁。我已经设置了自定义解锁模块，在4.1.1版本里面没问题的……
![S10529-22074804](https://user-images.githubusercontent.com/33481310/120073361-84ddfe80-c0ca-11eb-8fb5-c143e9e6515b.png)
![S10529-22075799](https://user-images.githubusercontent.com/33481310/120073370-90c9c080-c0ca-11eb-807b-a4bded8a7d5b.png)
![S10529-22080193](https://user-images.githubusercontent.com/33481310/120073394-a939db00-c0ca-11eb-8376-38872b301e48.png)
![S10529-22080527](https://user-images.githubusercontent.com/33481310/120073396-ab039e80-c0ca-11eb-8983-ce243ff9f43b.png)
![S10529-22080835](https://user-images.githubusercontent.com/33481310/120073398-ac34cb80-c0ca-11eb-9528-f1c196aa886f.png)
![S10529-22081135](https://user-images.githubusercontent.com/33481310/120073399-ad65f880-c0ca-11eb-8478-3faa0f9ef7df.png)

**Comment by TonyJiangWJ** [comment]
无障碍执行异常。无能为力了
