### ISSUE TITLE
关于倒计时准确性

### ISSUE THREAD

**Issue by NotRodeo** [TonyJiangWJ/Ant-Forest#109]
是这样大神，关于倒计时有个建议。
现在版本的倒计时是精确到秒，比如07:02:30获取到一个还有1分钟成熟的能量球或者排行榜里面有1分钟后可收取，那么计时器的逻辑好像就是在07:02:30的基础上加60秒，也就是07:03:30开始运行。
但是实际上蚂蚁的收取时间全都是整分钟的，不会出现秒的问题，最多会因为网络有那么一两秒的延迟出现，也就是说实际上需要启动的时间就是07:03:00，可以直接去掉计算后的秒那一部分时间，否则时间误差最大可以达到59秒。

**Comment by TonyJiangWJ** [comment]
可以 这个细节我倒没注意过
下个版本安排一下
