### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Neil-Boyle** [TonyJiangWJ/Ant-Forest#11]
启动main
 10:27:51.883/E: TypeError: Cannot find function loadDex in object com.stardust.autojs.runtime.ScriptRuntime@8af2e95. (<main>#9)
	at script(<main>:9)

启动config
10:28:51.135/E: ReferenceError: "activity" is not defined. (__ui__.js#12)
	at script(__ui__.js:12)
	at script(__ui__.js:393)
	at script(<config>:1113)

**Comment by TonyJiangWJ** [comment]
AutoJS版本太低，下载最新的[4.1.1 Alpha2](https://www.dropbox.com/s/pe3w53k0fugo1fa/Autojs%204.1.1%20Alpha2.apk?dl=0)
