### ISSUE TITLE
蚂蚁显示：您近期操作存在异常，请稍后再试

### ISSUE THREAD

**Issue by bayllech** [TonyJiangWJ/Ant-Forest#111]
问题：计时模式运行几次后，当自动点击能量球时，会弹出异常操作提示，此时关闭脚本，手动点击能量球也会有同样的提示
截图和日志如下：
![Screenshot_20210627_073535_com eg android AlipayGphone](https://user-images.githubusercontent.com/22362346/123607964-ef509e80-d830-11eb-9af7-de0dd3f734e2.jpg)

[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/6724784/log-verboses.log)

**Comment by TonyJiangWJ** [comment]
尝试关闭AUTOJS的无障碍权限，再手动收取

**Comment by TonyJiangWJ** [comment]
[无障碍防检测版](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AntiDetect.20210628.-armeabi.apk) 不确定有没有用，但是我这边一直用着没被检测过。这个版本正常使用需要安卓8.0以上

**Comment by williamglasgow** [comment]
我之前一直用的AutoJs 4.1.1 alpha2，从前段时间开始也每天被检测，时间大概从7:20-7:30开始，一直到8:00左右结束，期间都无法收能量。
从前天开始下载了这个无障碍防检测版，设置参数什么的与AutoJs 4.1.1 alpha2完全一样，使用体验不好，具体表现在无法按设定时间运行。比如设定8:00收能量/喂小鸡，可能一直到8:10分都没运行，然后手动打开防检测版AutoJS，他又会立刻运行攒下的人物。而且与4.1.1版本不同的是，这个版本每次运行都要跳出“要开始使用AntiDetect录制或投射内容吗？”的对话框，这个框一旦没成功点确认，就不会运行。
求问大佬防检测版AntiDetect这种情况是什么原因？
PS权限都给全了，包括自启动、功耗无限制、读写存储等等

**Comment by TonyJiangWJ** [comment]
![IMG_20210707_114237](https://user-images.githubusercontent.com/11325805/124697015-b2fbfd00-df18-11eb-8de3-a79c97dff832.jpg)
打开这个开关，另外问一下 蚂蚁森林防检测有用吗

**Comment by TonyJiangWJ** [comment]
> 而且与4.1.1版本不同的是，这个版本每次运行都要跳出“要开始使用AntiDetect录制或投射内容吗？”的对话框，这个框一旦没成功点确认，就不会运行。


这个应该是你后来更新过系统，以前的系统大部分有一个不再提示的勾选所以只在第一次运行的时候有，后来的安卓版本基本都没有了 所以每次运行都需要点一下，你可以在脚本设置中打开 是否自动授权截图权限

**Comment by williamglasgow** [comment]
刚才测试了一下定时任务，打开AlarmManager以后能够准时运行任务，应该是没问题了。
另外，因为这两天AntiDetect都没能在早上7点准时收能量，都是我手动收的，这两天都没有检测。我明后天观察一下再来反馈。

**Comment by williamglasgow** [comment]
另外，用了AntiDetect喂小鸡代码有点异常，经常识别倒计时识别出来负的，然后就一分钟以后再运行一次。我还没整明白是哪里不对。

**Comment by TonyJiangWJ** [comment]
嗯 检测的先观察一下，小鸡的话我们到蚂蚁庄园的仓库里面讨论

**Comment by williamglasgow** [comment]
今早还是被检测了

**Comment by TonyJiangWJ** [comment]
运行的时候有没有关闭原版的AutoJS的无障碍权限？

> 今早还是被检测了

**Comment by williamglasgow** [comment]
> 运行的时候有没有关闭原版的AutoJS的无障碍权限？
> 
> > 今早还是被检测了

没有哎，我把原版的AutoJS结束运行明早再看下

**Comment by williamglasgow** [comment]
运行了三天都被检测了蓝瘦

**Comment by TonyJiangWJ** [comment]
太惨了 这个检测好像还不是所有人都检测，我和我朋友用着啥事都没有，他用的还是原版的AutoJS

**Comment by TonyJiangWJ** [comment]
尝试一下关闭逛一逛收取 只通过排行榜收取 降低收取速度
