### ISSUE TITLE
等待控件[个人首页]失败

### ISSUE THREAD

**Issue by oiin** [TonyJiangWJ/Ant-Forest#113]
![Screenshot_20210805-205328](https://user-images.githubusercontent.com/88411797/128353202-ac3efadd-a739-4da1-b4cf-f15248da7a52.jpg)
支付宝最新版本，脚本也是最新版本
脚本自动打开蚂蚁森林之后，等了几秒，不收集，退出去又进来，就这样不停重复，最近这几天一直是这个问题，今天才过来提交，不知道是不是和蚂蚁森林首页左上角新加的那个【发现动物】有关系，感觉像是新加的，之前没注意到有。

**Comment by TonyJiangWJ** [comment]
从日志看是无法获取 `查看更多动态.*` 对应的控件文本，你可以检查一下当前森林首页能够获取到的控件信息中有没有它 没有的话修改一下控件文本的配置，配置首页独有的控件文本。具体获取方式可以直接通过AutoJS的悬浮窗获取，或者运行这个脚本[unit/获取当前页面的布局信息.js](https://github.com/TonyJiangWJ/Ant-Forest/blob/release/unit/%E8%8E%B7%E5%8F%96%E5%BD%93%E5%89%8D%E9%A1%B5%E9%9D%A2%E7%9A%84%E5%B8%83%E5%B1%80%E4%BF%A1%E6%81%AF.js)   获取所有控件信息，然后将这个结果贴出来我可以帮你分析

**Comment by oiin** [comment]
![Screenshot_20210806-115203](https://user-images.githubusercontent.com/88411797/128453574-aaf02430-db04-4755-9b09-7cab44415fde.jpg)
![Screenshot_20210806-115006](https://user-images.githubusercontent.com/88411797/128453583-3e5b730d-a361-47f1-89e0-08cfb2df47ac.jpg)
什么都没修改，今天早上运行了一下，发现好了，可以用了，早上本来想关掉这个问题，结果搞忘了。刚看到你的回复，然后找到相应的地方，相应的工具也运行了一下，顿时就明白之前几天为什么用不了，原因可能是，我八月份没有好友收集能量的动态，最近的一个动态还是七月二号的，进入八月份，可能动态就抹除了，所以搜索不到【查看更多动态】的文本，今天早上有人收集了我的能量球，有新动态了，所以今天就可以正常使用了。

**Comment by oiin** [comment]
写的脚本没有任何问题，运行很流畅，用了大概一年了，就是为了提这个问题，注册的github账号，没想到昨天晚上提的，今天早上就可以用了，我™等了五六天，以为有bug，等着博主更新呢，结果是我打扰了，很感谢楼主的无私奉献，博主牛逼👍，对了，博主，这个脚本有bug，那就是太强大了，搞得好友都没法偷我的能量，进而没有好友收集能量的动态，进而就出现了我这个问题。下个月我留意一下，看是不是换一个月动态就抹除了

**Comment by TonyJiangWJ** [comment]
哈哈哈哈 我是设置的每天早上7-8点不收自己能量 让早起的好友们也能收我的。不至于每天都只能我偷他们，他们偷不了我。
