### ISSUE TITLE
华为手机无法找到auto.js，请问怎么安装？

### ISSUE THREAD

**Issue by hopbaby** [TonyJiangWJ/Ant-Forest#117]
谢谢！~能否整体打包成js，用以atuo.js导入项目？

**Comment by TonyJiangWJ** [comment]
你仔细看一下README吧 怎么下载 怎么用都写了

**Comment by hopbaby** [comment]
> 你仔细看一下README吧 怎么下载 怎么用都写了

感谢，现在找得到”脚本“文件夹了，先前一直找不到。
