### ISSUE TITLE
1.2.0.9一直提示获取截图权限失败！

### ISSUE THREAD

**Issue by kovenkoo** [TonyJiangWJ/Ant-Forest#12]
我的系统是EMUI，10.0.0.0.171，无障碍跟悬浮窗的权限是给了的。不知道为什么一直提示获取截图权限失败。

**Comment by TonyJiangWJ** [comment]
设置改一下参数 README有说明

**Comment by kovenkoo** [comment]
我这边重启手机后正常，但是只要一关闭auto.js再打开，就会获取截图权限失败；只有重启后第一次打开才正常运行。

**Comment by 54lH** [comment]
同样的问题，设置中“获取截图等待时间”已经调的非常大了。

**Comment by TonyJiangWJ** [comment]
- 你们描述的这个问题，是一开始的截图权限获取失败，这个问题在华为手机上似乎比较容易出现，和脚本无关，是AutoJS和华为不太兼容，估计是华为改了底层的一些功能导致的。此问题同时存在于部分云手机上。
- 你们可以自行尝试如下代码，如果可用，尝试关闭`是否需要自动授权截图权限`。如果不可用，那无能为力，只有换手机或者修改AutoJS源码
  ```javascript
  requestScreenCapture()
  console.show()
  let img = captureScreen()
  log('图片大小：' + img.getWidth() + ', ' + img.getHeight())
  ```

**Comment by 54lH** [comment]
重新安装AutoJS后好像就可以了
