### ISSUE TITLE
新版收能量过程中自动打开能量雨，但是不收取

### ISSUE THREAD

**Issue by gudan001** [TonyJiangWJ/Ant-Forest#122]
1.3.5.9.3版本更新后，自动收能量过程中，如果没有可收取的能量，就会自动打开能量雨，但是不会收球，白白浪费掉120g

**Comment by TonyJiangWJ** [comment]
关闭逛一逛吧

**Comment by gudan001** [comment]
一直是用逛一逛收能量。。。好友太多了，刷好友列表太慢了

**Comment by gudan001** [comment]
一直用逛一逛收能量，好友太多了，用列表的话，很卡

**Comment by TonyJiangWJ** [comment]
那你搞个定时任务 每天提前把能量雨收掉就行了 工具都提供了 你说的这个问题以后再解决

**Comment by gudan001** [comment]
还有个问题，现在打能量雨的按钮又跑到屏幕中间了，遮挡住了开始按钮，希望新版本可以修复

**Comment by TonyJiangWJ** [comment]
故意的，就是让你们点悬浮窗的 立即开始 而不是手动点击能量雨里面的开始
