### ISSUE TITLE
每次运行5分钟就报错停止收能量了

### ISSUE THREAD

**Issue by gudan001** [TonyJiangWJ/Ant-Forest#123]
小米11Pro，每次运行5分钟就不收能量报错了，帮忙看一下什么问题吧「阿里云盘」
链接：https://www.aliyundrive.com/s/4cN7eMa8Rci

**Comment by TonyJiangWJ** [comment]
图片的直接拖入github输入框就行 别搞这种需要登录的 你直接提供日志就行logs/log-verboses.log

**Comment by gudan001** [comment]
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/7585617/log-verboses.log)
日志没记录
![IMG_20211123_113016](https://user-images.githubusercontent.com/93954544/142967471-1dfb616b-0c3b-4bdc-9506-d4c85d9a84b8.jpg)

**Comment by TonyJiangWJ** [comment]
ADB 授权报错 不用管 新版已经修改
