### ISSUE TITLE
能量雨问题

### ISSUE THREAD

**Issue by Kirito-Aus** [TonyJiangWJ/Ant-Forest#125]
![image](https://user-images.githubusercontent.com/54315770/143416636-2912ed91-c43c-4a62-bb98-c27fadfcc7c8.png)
![image](https://user-images.githubusercontent.com/54315770/143416658-f5be9891-7dbc-4d08-aa9f-eee42b7cb922.png)

**Comment by Kirito-Aus** [comment]
每次进入到能量雨这里好像就进不去了，接着会从zfb退出来。返回到autojs以后又提示“有能量漏收”，又进入zfb。

**Comment by TonyJiangWJ** [comment]
这个还在测试中 你可以先搞一个零点钟定时自动收集能量雨的 规避这个问题
