### ISSUE TITLE
请教com.googlecode.tesseract.android.TessBaseAPI是怎么安装在手机里的？

### ISSUE THREAD

**Issue by james-bond-007** [TonyJiangWJ/Ant-Forest#127]
请教您一个问题，在TesserOcrUtil.js中，有importClass(com.googlecode.tesseract.android.TessBaseAPI)，这个com.googlecode.tesseract.android.TessBaseAPI是怎样安装到手机的？

**Comment by TonyJiangWJ** [comment]
修改版[AutoJS Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk) 源代码也在这个仓库
