### ISSUE TITLE
运行中自动开启飞行模式

### ISSUE THREAD

**Issue by NotRodeo** [TonyJiangWJ/Ant-Forest#128]
如题，大概有一个多月了，以前也会有这种情况，但是偶尔出现，现在是每天必出现，运行后的5-15分钟左右，基本都出现在解锁的过程中，眼睁睁看着开灯开飞行，而且是直接开的，不是下拉状态栏以后点击快捷方式开的……是不是有必要把软件重置一下，重新下载插件包

**Comment by TonyJiangWJ** [comment]
什么设备 系统版本 尝试运行 `unit/获取锁屏界面控件信息.js` 根据提示获取控件信息
提供一下最后获取的控件信息 日志会自动保存在 `logs/info.log` 里面 你把它发出来就行
并尝试此脚本多次 看是否会有同样的问题

**Comment by NotRodeo** [comment]
> 

魅族18pro ，安卓11底层，好像最近我的魅族17pro也出现了这个问题
[info.log](https://github.com/TonyJiangWJ/Ant-Forest/files/7834335/info.log)

**Comment by TonyJiangWJ** [comment]
从控件信息中没看出啥问题
尝试将密码改成 pin密码 看还会不会这样

**Comment by NotRodeo** [comment]
> 从控件信息中没看出啥问题
> 尝试将密码改成 pin密码 看还会不会这样 

pin码只有重启以后需要输入啊……我用的自定义解锁 以前没啥问题

**Comment by TonyJiangWJ** [comment]
我的意思是你把锁屏密码形式改成PIN密码试试

**Comment by NotRodeo** [comment]
> 我的意思是你把锁屏密码形式改成PIN密码试试

魅族的锁屏要么滑动要么密码，我一直都用的密码

**Comment by TonyJiangWJ** [comment]
哦
