### ISSUE TITLE
这个错误怎么解决？

### ISSUE THREAD

**Issue by eaglexxxm** [TonyJiangWJ/Ant-Forest#134]
14:02:43.751/E: Function importClass must be called with a class; had "[JavaPackage com.tony.ColorCenterCalculatorWithInterval]" instead. (<init>#14)
Function importClass must be called with a class; had "[JavaPackage com.tony.ColorCenterCalculatorWithInterval]" instead.
    at <init>:14:0
    at file:/storage/emulated/0/脚本/Ant-Forest-1.3.6.2.1/core/ImgBasedFriendListScanner.js:8:0
    at file:/storage/emulated/0/脚本/Ant-Forest-1.3.6.2.1/core/Ant_forest.js:18:0
    at _load (file:///android_asset/modules/jvm-npm.js:60:0)
    at /storage/emulated/0/脚本/Ant-Forest-1.3.6.2.1/main.js:43:0

**Comment by TonyJiangWJ** [comment]
免费版bug，重启AutoJS 或者用修改版
