### ISSUE TITLE
1.3.6.2.3无法运行

### ISSUE THREAD

**Issue by iciness** [TonyJiangWJ/Ant-Forest#135]
![Screenshot_20220126_081702_org.autojs.autojs.modify.jpg](https://user-images.githubusercontent.com/4505686/151081570-98299b62-afa1-4f83-8840-ce70ee0a2c5b.jpg)

**Comment by ilcf** [comment]
我也遇到同样的问题，等待修复。。。谢谢！

**Comment by TonyJiangWJ** [comment]
`lib/BaseOcrUtil.js` 最上面修改如下
```javascript
try {
  importClass("okhttp3.OkHttpClient")
  importClass("okhttp3.FormBody")
  importClass("okhttp3.Request")
} catch (e) {
  //
}
```

**Comment by ilcf** [comment]
> `lib/BaseOcrUtil.js` 最上面修改如下
> 
> ```js
> try {
>   importClass("okhttp3.OkHttpClient")
>   importClass("okhttp3.FormBody")
>   importClass("okhttp3.Request")
> } catch (e) {
>   //
> }
> ```

谢谢，这就试试，等会给您反馈！

**Comment by TonyJiangWJ** [comment]
新版本已修复
