### ISSUE TITLE
Main定时启动时报错

### ISSUE THREAD

**Issue by only4xiao** [TonyJiangWJ/Ant-Forest#137]
可以自动解锁，解锁后报错stack size 1043KB
版本Autojs. Modify
森林最新版

**Comment by TonyJiangWJ** [comment]
AutoJS保持更新 https://github.com/TonyJiangWJ/Auto.js/releases

**Comment by only4xiao** [comment]
> AutoJS保持更新 https://github.com/TonyJiangWJ/Auto.js/releases

更新到最新版还是会报错
![_20220226_210756](https://user-images.githubusercontent.com/93267251/155844610-48892559-c3a7-41f6-b5dc-e9bb9b02255b.JPG)
![_20220226_210740](https://user-images.githubusercontent.com/93267251/155844611-a31637f2-8b90-4644-a451-38dbfb395616.JPG)

**Comment by only4xiao** [comment]
补充只有在定时启动main的时候屏幕解锁后会报错，直接运行main一切正常

**Comment by TonyJiangWJ** [comment]
截图日志界面 这点信息无从判断 你自己尝试历史版本吧 我无能为力

**Comment by only4xiao** [comment]
帮忙看下日志，谢谢
![Screenshot_20220226-230044](https://user-images.githubusercontent.com/93267251/155847963-01ed150f-1340-4f3e-bf34-4b3da5484f43.png)
![Screenshot_20220226-230054](https://user-images.githubusercontent.com/93267251/155847969-e6bfa9c1-95b8-48e1-8660-05f5e70cc61f.png)
![Screenshot_20220226-230106](https://user-images.githubusercontent.com/93267251/155847971-a530e024-b166-4bb0-b745-910ae5444e18.png)
![Screenshot_20220226-230125](https://user-images.githubusercontent.com/93267251/155847974-92e7f5c0-2c59-4d9b-883e-5fa1fd62a029.png)
![Screenshot_20220226-230135](https://user-images.githubusercontent.com/93267251/155847976-51bc2ef2-10e3-4514-82b0-a26779e51290.png)

**Comment by TonyJiangWJ** [comment]
不是这个日志 AutoJS的日志 这个明显是AutoJS的问题 你用其他版本的AutoJS吧 反正我没事 其他人也没事
