### ISSUE TITLE
如何把整个脚本项目放进 "/sdcard/脚本/" 文件夹下面？

### ISSUE THREAD

**Issue by gubindp** [TonyJiangWJ/Ant-Forest#141]
把整个脚本项目放进 "/sdcard/脚本/" 文件夹下面？

**Comment by TonyJiangWJ** [comment]
https://www.bilibili.com/video/BV1R7411K7b3?p=2  你可以参考这个

**Comment by gubindp** [comment]
非常感谢解答。给您添麻烦了！见谅。
