### ISSUE TITLE
解锁设备求助

### ISSUE THREAD

**Issue by Elksforest** [TonyJiangWJ/Ant-Forest#142]
把ExternalUnlockDevice-demo.js重命名去掉“-demo”，然后里面填写了pin码，然后设置了定时任务测试是否能解锁，但是失败了，只能发起ISSUE求助了
[info.log](https://github.com/TonyJiangWJ/Ant-Forest/files/8501619/info.log)

**Comment by TonyJiangWJ** [comment]
从布局看并不需要重写解锁代码 用默认的即可 打开可视化配置 配置一下密码

**Comment by Elksforest** [comment]
> 从布局看并不需要重写解锁代码 用默认的即可 打开可视化配置 配置一下密码

可以了，谢谢指导
