### ISSUE TITLE
设置分辨率后识别区域不对

### ISSUE THREAD

**Issue by reixuemin** [TonyJiangWJ/Ant-Forest#143]
MIUI有个设置分辨率的功能，设置到极清后，是不是要自己去调整识别区域？
![126ff73f9cd572d1d1d1db2bed9563d](https://user-images.githubusercontent.com/14087655/164455613-af320f01-bef8-467a-bb62-3f1d918a89ff.jpg)
![519902502d850c17e2363e1f6773cb2](https://user-images.githubusercontent.com/14087655/164455638-dca18694-a103-4281-971d-96c5f1d583f9.jpg)

**Comment by TonyJiangWJ** [comment]
是的 建议不要频繁切换分辨率 你可以自己重新配置或者直接点击右上角 重置默认配置 脚本下次运行时会自动重新识别
