### ISSUE TITLE
最新支付宝支持两个设备切换登录了！

### ISSUE THREAD

**Issue by Prophetia086** [TonyJiangWJ/Ant-Forest#144]
如题，最新的支付宝支持两个设备切换登录，希望能做一个简单的兼容，发现被其他设备登录后，点一下“进入支付宝”，这样用来收能量的手机就可以不带在身上了！
拜托啦！

**Comment by TonyJiangWJ** [comment]
试了一下要指纹登录 个性化的建议自己开发一下

**Comment by Prophetia086** [comment]
> 试了一下要指纹登录 个性化的建议自己开发一下

@TonyJiangWJ 不是，不过我也是才发现，这个是灰度发布的，我的支付宝账号可以，但是我老婆的就不行。
具体是这样的，如果是在名单内，功能发布后第一次登录，会提示你，支付宝现在支持可信任设备快速登录了，不需要任何认证，然后让你在最近登录的设备中选择两台（含本机），这两台设备切换登录就不需要任何认证了。

效果是这样的，同一时间只能在一台设备上处于登录状态，但是另一台可信设备打开支付宝时，只需要在页面上点一下“进入支付宝”按钮，没有任何其他认证，就登录成功了，前一台设备会提示账号在其他设备登录。同样，要想登录回来，也只需要点一下。

可以在“我的--设置--账号与安全--登录设置“看一下，如果只有两个选项，就没有这个功能。如果有这个功能，会有第三排，叫”信任设备快捷登录“，点击开启，可以看到当前已关联的信任设备情况。

没事，等放开了再适配吧！😬

非常期待！
![IMG_DDC68DA50013-1](https://user-images.githubusercontent.com/73395827/167525290-f60c5136-bdd1-4982-b3ce-8ab9f7c0c92c.jpeg)
![IMG_F06D3C5EEF75-1](https://user-images.githubusercontent.com/73395827/167525295-b27c4356-ff76-469c-be99-bbeffa734c84.jpeg)

**Comment by Prophetia086** [comment]
好像已经放开咯，期待新功能！😬

**Comment by Prophetia086** [comment]
之前以为挺麻烦一直没有去看代码
昨天晚上细看了一下原来只需要改几个字就行了，哈哈哈哈哈哈哈
多谢多谢！！
