### ISSUE TITLE
初次使用，有几个小问题想问一下

### ISSUE THREAD

**Issue by xzhlksh** [TonyJiangWJ/Ant-Forest#145]
1、我在收集设置里开了永不停止的同时，还开了显示0:30~6:50不可运行。结果第二天早上就真的没有运行？这个能不能改一下逻辑呢？我日常性没法早起手动启动脚本，但是也不能半夜让脚本每隔一小时解锁屏幕跑一次啊

2、收集设置里没有找到提前解锁收集，导致有时候采集能量晚了半分钟就被别人偷了，这个能不能加一个提前量设置呢？哪怕只提前半分钟解锁并循环监控自己的能量也可以啊

3、每次启动任务时延迟时间能不能自定义几个档位呢？固定5分钟着实有点长了

**Comment by xzhlksh** [comment]
还有，请问能不能加一个0点的定时收集任务？这个时间点会统一释放快过期的能量球。

**Comment by TonyJiangWJ** [comment]
。。。麻烦仔细看README 白嫖有度 自行摸索
