### ISSUE TITLE
安装完成，支付宝反复启动，收取能量失败

### ISSUE THREAD

**Issue by 52git-hub** [TonyJiangWJ/Ant-Forest#146]
查询日志：
错误位置：当前未打开支付宝，com.huawei.system.manager
错误位置：当前未打开支付宝，org.autojs.autojs.modify
等待控件[个人首页]失败，查找内容：查看更多动态.*
错误位置：当前未打开支付宝，com.huawei.android.launcher

我是鸿蒙英文系统，不知有没有影响

**Comment by TonyJiangWJ** [comment]
无法取到正确包名 和系统应该没关系 试试修改版autojs

**Comment by 52git-hub** [comment]
> 无法取到正确包名 和系统应该没关系 试试修改版autojs

您好！现在用的就是autojs modify。

**Comment by TonyJiangWJ** [comment]
看一下你有没有装什么悬浮球之类的 可能控件获取错误导致包名校验失败

**Comment by 52git-hub** [comment]
悬浮球是什么？有具体的名字吗？

**Comment by TonyJiangWJ** [comment]
大哥 你自己手机 我哪知道 自己摸索吧
