### ISSUE TITLE
可视化配置无法执行，可能是由于手机存在传感器故障导致，请教解决方案

### ISSUE THREAD

**Issue by iciness** [TonyJiangWJ/Ant-Forest#148]
![e88892ef6587507fed0b23b7a7ee1d2](https://user-images.githubusercontent.com/4505686/168454570-f50acbd6-38c2-4007-bd9b-4729216d94ef.jpg)
![微信图片_20220515102555](https://user-images.githubusercontent.com/4505686/168454612-8bfaeae3-a556-46f2-8c6c-b192e4e6c4fa.jpg)

**Comment by TonyJiangWJ** [comment]
是我代码有问题 判断写反了 可视化配置 146行的`if (!distanceSensor) {`感叹号去掉 修改如下
```javascript
  if (distanceSensor) {
    distanceSensor.on('change', (event, d) => {
      postMessageToWebView({ functionName: 'distanceSensorChange', data: { distance: d } })
    })
  }
```
