### ISSUE TITLE
一些修改建议

### ISSUE THREAD

**Issue by Ehustein** [TonyJiangWJ/Ant-Forest#15]
在使用的过程中，我有一些好的建议：

1.颜色相似度和悬浮窗位置建议建议不要采用拖动滑块的方式来输入，非常难以操作并且无法精确输入值。
2.既然有不收取的白名单，不浇水的黑名单，我觉得还应该有个不帮他收取的名单
3.永不停止的模式下，倒计时可否设置一个随机值？比如50～60之间的随机值
4.是否可以增加一个功能：半夜(比如23:00-次日5:00)不收取能量？

**Comment by TonyJiangWJ** [comment]
- 1 已经在优化进程中
- 2、3 总的来说无意义
- 4 不收能量 你定时设置不就可以了，`util/` 下面已经提供了几个
  比如23:00 执行 计时停止， 6点执行 永不停止

**Comment by Ehustein** [comment]
感谢指点
