### ISSUE TITLE
是放弃了AutoX.JS版本的支持吗？

### ISSUE THREAD

**Issue by xxchengxx** [TonyJiangWJ/Ant-Forest#151]
使用Autox.js运行就报错Function importClass must be called with a class;had"[JavaPackage com.tony.ColorCenterCalculatorWithInterval"]……
换AutoJS Pro 倒是正常，是放弃了Autox吗？以前是可以正常运行的。

**Comment by TonyJiangWJ** [comment]
autox的问题不是脚本的问题 再说了一开始就没打算支持
