### ISSUE TITLE
请问为什么会导入模块SQLiteUtils失败，请检查代码？

### ISSUE THREAD

**Issue by andymo21** [TonyJiangWJ/Ant-Forest#152]
请问为什么会导入模块SQLiteUtils失败，请检查代码？

**Comment by TonyJiangWJ** [comment]
旧版本autojs不支持新语法，更新一下最新版修改版autojs或者等下次发布兼容的版本 
旧版本autojs不建议继续使用有不少内存泄露问题

**Comment by andymo21** [comment]
好的，谢谢解答
