### ISSUE TITLE
定时任务启动失败，日志显示解密字段失败walking_accounts

### ISSUE THREAD

**Issue by SY-997** [TonyJiangWJ/Ant-Forest#153]
[我并没有开启刷步数的

![微信图片_20220525091204](https://user-images.githubusercontent.com/70785897/170157591-0e23b620-7c0d-4db1-b3aa-0051b643ce38.jpg)

**Comment by TonyJiangWJ** [comment]
定时任务不受这个影响 请截图其他关键日志

**Comment by SY-997** [comment]
12.15定时执行
![微信图片_20220525122251](https://user-images.githubusercontent.com/70785897/170179303-ba453af2-66eb-4094-bf4c-0d7005c14f10.jpg)
@TonyJiangWJ

**Comment by TonyJiangWJ** [comment]
你日志里面的都是闪退后自动运行的CrashCatcher 而不是main.js 我无法提供任何帮助
