### ISSUE TITLE
小号脱敏显示是一样的。。

### ISSUE THREAD

**Issue by avebest1992** [TonyJiangWJ/Ant-Forest#155]
![IMG_20220529_151408](https://user-images.githubusercontent.com/77918703/170856831-ecb2f7ba-2395-472a-b5cf-069e017b6600.jpg)
多账号管理里面添加账号的时候就只能添加一个了。。能把小号也用uid来识别吗？

**Comment by TonyJiangWJ** [comment]
我真的笑死 你这账号 哈哈哈 没绑定邮箱吗 拿邮箱登录就行了
