### ISSUE TITLE
解锁设备：荣耀9X

### ISSUE THREAD

**Issue by here101** [TonyJiangWJ/Ant-Forest#156]
大佬，请问手机解锁密码是6位数字的那种，怎样写解锁代码啊。谢谢。
以下是锁屏界面控件信息：
info logs for [2022-05-31 14:27:41]
2022-05-31 14:28:00.124 总分析耗时：6744ms 总控件数：216

=================
锁屏界面:
分析耗时：1090ms
控件总数：98
分析控件内容：
-[1:0]id:[com.android.systemui:id/scrim_behind]bounds:[0, 0, 1080, 2340]
-[1:1]id:[com.android.systemui:id/scrim_in_front]bounds:[0, 0, 1080, 2340]
-[1:2]id:[com.android.systemui:id/notification_panel]bounds:[0, 0, 1080, 2340]
--[2:0]id:[com.android.systemui:id/hw_keyguard_bottom_area]bounds:[0, 0, 1080, 2340]
---[3:0]id:[com.android.systemui:id/infoview_container]bounds:[0, 0, 1080, 2340]
---[3:1]id:[com.android.systemui:id/toolbox_container]bounds:[0, 0, 1080, 2340]
----[4:0]id:[com.android.systemui:id/info_center_container]bounds:[0, 361, 1080, 1979]
-----[5:0]id:[com.android.systemui:id/info_center]bounds:[0, 2221, 1080, 119]
------[6:0]id:[com.android.systemui:id/info_center_hint]bounds:[1, 2268, 1078, 72]
-------[7:0]id:[com.android.systemui:id/info_center_hint_up]bounds:[504, 2268, 72, 72]
------[6:1]id:[com.android.systemui:id/extra_layout]bounds:[1, 2340, 1078, 0]
-------[7:0]id:[com.android.systemui:id/change_lockscreen_style][desc]content:[更换锁屏样式]bounds:[1, 2340, 1078, 0]
-------[7:1]id:[com.android.systemui:id/bottom_tool_box]bounds:[1, 2461, 1078, -121]
--------[8:0]id:[com.android.systemui:id/ic_layout_shortcut_1]bounds:[73, 2491, 186, -151]
---------[9:0]id:[com.android.systemui:id/ic_circle_shortcut_1][desc]content:[录音机]bounds:[97, 2491, 138, -151]
---------[9:1]id:[com.android.systemui:id/info_center_shortcut_1]bounds:[130, 2524, 72, -184]
--------[8:1]id:[com.android.systemui:id/ic_layout_shortcut_2]bounds:[259, 2491, 187, -151]
---------[9:0]id:[com.android.systemui:id/ic_circle_shortcut_2][desc]content:[计算器]bounds:[283, 2491, 138, -151]
---------[9:1]id:[com.android.systemui:id/info_center_shortcut_2]bounds:[316, 2524, 72, -184]
--------[8:2]id:[com.android.systemui:id/ic_layout_shortcut_3]bounds:[446, 2491, 187, -151]
---------[9:0]id:[com.android.systemui:id/ic_circle_shortcut_3][desc]content:[手电筒]bounds:[470, 2491, 138, -151]
---------[9:1]id:[com.android.systemui:id/info_center_shortcut_3]bounds:[503, 2524, 72, -184]
--------[8:3]id:[com.android.systemui:id/ic_layout_shortcut_4]bounds:[633, 2491, 187, -151]
---------[9:0]id:[com.android.systemui:id/ic_circle_shortcut_4][desc]content:[计时器]bounds:[657, 2491, 138, -151]
---------[9:1]id:[com.android.systemui:id/info_center_shortcut_4]bounds:[690, 2524, 72, -184]
--------[8:4]id:[com.android.systemui:id/ic_layout_shortcut_5]bounds:[820, 2491, 187, -151]
---------[9:0]id:[com.android.systemui:id/ic_circle_shortcut_5][desc]content:[扫一扫]bounds:[844, 2491, 138, -151]
---------[9:1]id:[com.android.systemui:id/info_center_shortcut_5]bounds:[877, 2524, 72, -184]
--[2:1]id:[com.android.systemui:id/notification_container_parent]bounds:[0, 0, 1080, 2340]
---[3:0]id:[com.android.systemui:id/qs_frame]bounds:[0, 0, 1080, 2340]
----[4:0]id:[com.android.systemui:id/quick_settings_container]bounds:[0, 0, 1080, 0]
-----[5:0]id:[com.android.systemui:id/header]bounds:[24, 0, 1032, 0]
---[3:1]id:[com.android.systemui:id/notification_stack_scroller]bounds:[0, 0, 1080, 2268]
-[1:3]id:[com.android.systemui:id/backdrop]bounds:[0, 0, 1080, 2340]
--[2:0]id:[com.android.systemui:id/backdrop_back]bounds:[0, 0, 1080, 2340]
----[4:0]id:[com.android.systemui:id/magazine_img]bounds:[0, 0, -3, 2340]
----[4:1]id:[com.android.systemui:id/description_container]bounds:[0, 0, -3, 2340]
----[4:2]id:[com.android.systemui:id/wallpaper_mask]bounds:[0, 0, -3, 2340]
-----[5:0]id:[com.android.systemui:id/mask_top]bounds:[0, 0, -3, 336]
-----[5:1]id:[com.android.systemui:id/mask_bottom]bounds:[0, 2100, -3, 240]
----[4:0]id:[com.android.systemui:id/magazine_img]bounds:[0, 0, 1080, 2340]
----[4:1]id:[com.android.systemui:id/description_container]bounds:[0, 0, 1080, 2340]
----[4:0]id:[com.android.systemui:id/magazine_img]bounds:[1083, 0, -3, 2340]
----[4:1]id:[com.android.systemui:id/description_container]bounds:[1083, 0, -3, 2340]
----[4:2]id:[com.android.systemui:id/wallpaper_mask]bounds:[1083, 0, -3, 2340]
-----[5:0]id:[com.android.systemui:id/mask_top]bounds:[1083, 0, -3, 336]
-----[5:1]id:[com.android.systemui:id/mask_bottom]bounds:[1083, 2100, -3, 240]
--[2:1]id:[com.android.systemui:id/keyguard_lock_screen_panel]bounds:[0, 0, 1080, 2340]
---[3:0]id:[com.android.systemui:id/dynamicUnlockScreen]bounds:[0, 0, 1080, 2340]
-[1:4]id:[com.android.systemui:id/keyguard_header]bounds:[0, 0, 1080, 72]
--[2:0]id:[com.android.systemui:id/status_bar_contents]bounds:[0, 0, 1080, 72]
---[3:0]id:[com.android.systemui:id/status_bar_contents_parent]bounds:[0, 0, 1080, 72]
----[4:0]id:[com.android.systemui:id/operator_name_container]bounds:[72, 0, 182, 72]
-----[5:0]id:[com.android.systemui:id/msim_status_bar_operators_card_one_id]bounds:[72, 12, 182, 47]
------[6:0]id:[com.android.systemui:id/operator_name][desc]content:[中国移动]bounds:[72, 12, 142, 47]
------[6:1]id:[com.android.systemui:id/operator_icon]bounds:[214, 14, 40, 42]
------[6:2]id:[com.android.systemui:id/operator_cust_container]bounds:[214, 35, 0, 0]
----[4:1]id:[com.android.systemui:id/system_icon_area_fixed]bounds:[254, 0, 258, 72]
-----[5:0]id:[com.android.systemui:id/link_plus_view]bounds:[254, 0, 0, 72]
-----[5:1]id:[com.android.systemui:id/signal_cluster_container]bounds:[254, 15, 105, 42]
------[6:0]id:[com.android.systemui:id/signal_cluster]bounds:[254, 15, 105, 42]
-------[7:0]id:[com.android.systemui:id/signal_cluster_container]bounds:[254, 15, 105, 42]
---------[9:0]id:[com.android.systemui:id/mobile_combo]bounds:[254, 15, 61, 42]
----------[10:0][desc]content:[4G 手机信号满格。]bounds:[254, 15, 61, 42]
------------[12:0]id:[com.android.systemui:id/mobile_data]bounds:[315, 15, 0, 0]
-------------[13:0]id:[com.android.systemui:id/mobile_type_slave]bounds:[315, 15, 0, 0]
-------------[13:1]id:[com.android.systemui:id/mobile_signal_slave]bounds:[315, 15, 0, 0]
-------------[13:2]id:[com.android.systemui:id/mobile_signal]bounds:[254, 15, 61, 42]
-------------[13:3]id:[com.android.systemui:id/mobile_signal_type]bounds:[254, 15, 61, 42]
--------[8:1]id:[com.android.systemui:id/wifi_combo][desc]content:[WLAN 信号强度满格。]bounds:[315, 15, 44, 42]
---------[9:0]id:[com.android.systemui:id/wifi_signal]bounds:[315, 15, 44, 42]
---------[9:1]id:[com.android.systemui:id/wifi_signal_dark]bounds:[315, 15, 44, 42]
---------[9:2]id:[com.android.systemui:id/wifi_inout]bounds:[315, 15, 44, 42]
--------[8:2]id:[com.android.systemui:id/mobile_signal_group]bounds:[359, 36, 0, 0]
-----[5:2]id:[com.android.systemui:id/network_speed_view]bounds:[359, 0, 153, 72]
------[6:0]id:[com.android.systemui:id/speed][desc]content:[62.7B/s]bounds:[365, 0, 141, 72]
----[4:2]id:[com.android.systemui:id/system_icon_unstable]bounds:[512, 0, 0, 72]
-----[5:0]id:[com.android.systemui:id/statusIcons_more]bounds:[512, 0, 0, 72]
----[4:3]id:[com.android.systemui:id/system_icons_super_container]bounds:[560, 0, 448, 72]
-----[5:0]id:[com.android.systemui:id/system_icons_container]bounds:[757, 0, 251, 72]
------[6:0]id:[com.android.systemui:id/system_icons]bounds:[757, 0, 251, 72]
-------[7:0]id:[com.android.systemui:id/statusIcons]bounds:[757, 0, 117, 72]
--------[8:0][desc]content:[流量节省程序已开启]bounds:[757, 5, 42, 62]
--------[8:1][desc]content:[蓝牙已连接。]bounds:[799, 5, 33, 62]
--------[8:2][desc]content:[振铃器静音。]bounds:[832, 5, 42, 62]
-------[7:1]id:[com.android.systemui:id/battery]bounds:[874, 13, 134, 46]
--------[8:0]id:[com.android.systemui:id/battery_outside_percent][desc]content:[54%]bounds:[874, 13, 63, 46]
---------[9:0]id:[com.android.systemui:id/battery_border][desc]content:[电量剩余 54。]bounds:[937, 15, 71, 43]
---------[9:1]id:[com.android.systemui:id/battery_inside_level]bounds:[937, 15, 71, 43]
---------[9:2]id:[com.android.systemui:id/battery_inside_save]bounds:[937, 15, 71, 43]
-[1:5]id:[com.android.systemui:id/status_bar_container]bounds:[0, 0, 1080, 72]
--[2:0]id:[com.android.systemui:id/status_bar]bounds:[0, 0, 1080, 72]
---[3:0]id:[com.android.systemui:id/status_bar_contents]bounds:[0, 0, 1080, 72]
----[4:0]id:[com.android.systemui:id/system_icon_unstable]bounds:[330, 0, 427, 72]
-----[5:0]id:[com.android.systemui:id/notification_icon_area]bounds:[330, 0, 427, 72]
------[6:0]id:[com.android.systemui:id/notification_icon_area_inner]bounds:[330, 0, 427, 72]
-------[7:0]id:[com.android.systemui:id/notificationIcons]bounds:[330, 0, 0, 72]
----[4:1]id:[com.android.systemui:id/system_icon_area]bounds:[757, 0, 251, 72]
=================
密码输入界面:
分析耗时：436ms
控件总数：118
分析控件内容：
-[1:0]id:[com.android.systemui:id/scrim_behind]bounds:[0, 0, 1080, 2340]
-[1:1]id:[com.android.systemui:id/scrim_in_front]bounds:[0, 0, 1080, 2340]
-[1:2]id:[com.android.systemui:id/notification_panel]bounds:[0, 0, 1080, 2340]
--[2:0]id:[com.android.systemui:id/notification_container_parent]bounds:[0, 0, 1080, 2340]
---[3:0]id:[com.android.systemui:id/qs_frame]bounds:[0, 0, 1080, 2340]
----[4:0]id:[com.android.systemui:id/quick_settings_container]bounds:[0, 0, 1080, 0]
-----[5:0]id:[com.android.systemui:id/header]bounds:[24, 0, 1032, 0]
---[3:1]id:[com.android.systemui:id/notification_stack_scroller]bounds:[0, 0, 1080, 2268]
-[1:3]id:[com.android.systemui:id/backdrop]bounds:[0, 0, 1080, 2340]
--[2:0]id:[com.android.systemui:id/backdrop_back]bounds:[0, 0, 1080, 2340]
----[4:0]id:[com.android.systemui:id/magazine_img]bounds:[0, 0, -3, 2340]
----[4:1]id:[com.android.systemui:id/description_container]bounds:[0, 0, -3, 2340]
----[4:2]id:[com.android.systemui:id/wallpaper_mask]bounds:[0, 0, -3, 2340]
-----[5:0]id:[com.android.systemui:id/mask_top]bounds:[0, 0, -3, 336]
-----[5:1]id:[com.android.systemui:id/mask_bottom]bounds:[0, 2100, -3, 240]
----[4:0]id:[com.android.systemui:id/magazine_img]bounds:[0, 0, 1080, 2340]
----[4:1]id:[com.android.systemui:id/description_container]bounds:[0, 0, 1080, 2340]
----[4:0]id:[com.android.systemui:id/magazine_img]bounds:[1083, 0, -3, 2340]
----[4:1]id:[com.android.systemui:id/description_container]bounds:[1083, 0, -3, 2340]
----[4:2]id:[com.android.systemui:id/wallpaper_mask]bounds:[1083, 0, -3, 2340]
-----[5:0]id:[com.android.systemui:id/mask_top]bounds:[1083, 0, -3, 336]
-----[5:1]id:[com.android.systemui:id/mask_bottom]bounds:[1083, 2100, -3, 240]
-[1:5]id:[com.android.systemui:id/keyguard_header]bounds:[0, 0, 1080, 72]
--[2:0]id:[com.android.systemui:id/status_bar_contents]bounds:[0, 0, 1080, 72]
---[3:0]id:[com.android.systemui:id/status_bar_contents_parent]bounds:[0, 0, 1080, 72]
----[4:0]id:[com.android.systemui:id/operator_name_container]bounds:[72, 0, 182, 72]
-----[5:0]id:[com.android.systemui:id/msim_status_bar_operators_card_one_id]bounds:[72, 12, 182, 47]
------[6:0]id:[com.android.systemui:id/operator_name][desc]content:[中国移动]bounds:[72, 12, 142, 47]
------[6:1]id:[com.android.systemui:id/operator_icon]bounds:[214, 14, 40, 42]
------[6:2]id:[com.android.systemui:id/operator_cust_container]bounds:[214, 35, 0, 0]
----[4:1]id:[com.android.systemui:id/system_icon_area_fixed]bounds:[254, 0, 258, 72]
-----[5:0]id:[com.android.systemui:id/link_plus_view]bounds:[254, 0, 0, 72]
-----[5:1]id:[com.android.systemui:id/signal_cluster_container]bounds:[254, 15, 105, 42]
------[6:0]id:[com.android.systemui:id/signal_cluster]bounds:[254, 15, 105, 42]
-------[7:0]id:[com.android.systemui:id/signal_cluster_container]bounds:[254, 15, 105, 42]
---------[9:0]id:[com.android.systemui:id/mobile_combo]bounds:[254, 15, 61, 42]
----------[10:0][desc]content:[4G 手机信号满格。]bounds:[254, 15, 61, 42]
------------[12:0]id:[com.android.systemui:id/mobile_data]bounds:[315, 15, 0, 0]
-------------[13:0]id:[com.android.systemui:id/mobile_type_slave]bounds:[315, 15, 0, 0]
-------------[13:1]id:[com.android.systemui:id/mobile_signal_slave]bounds:[315, 15, 0, 0]
-------------[13:2]id:[com.android.systemui:id/mobile_signal]bounds:[254, 15, 61, 42]
-------------[13:3]id:[com.android.systemui:id/mobile_signal_type]bounds:[254, 15, 61, 42]
--------[8:1]id:[com.android.systemui:id/wifi_combo][desc]content:[WLAN 信号强度满格。]bounds:[315, 15, 44, 42]
---------[9:0]id:[com.android.systemui:id/wifi_signal]bounds:[315, 15, 44, 42]
---------[9:1]id:[com.android.systemui:id/wifi_signal_dark]bounds:[315, 15, 44, 42]
---------[9:2]id:[com.android.systemui:id/wifi_inout]bounds:[315, 15, 44, 42]
--------[8:2]id:[com.android.systemui:id/mobile_signal_group]bounds:[359, 36, 0, 0]
-----[5:2]id:[com.android.systemui:id/network_speed_view]bounds:[359, 0, 153, 72]
------[6:0]id:[com.android.systemui:id/speed][desc]content:[23.7B/s]bounds:[365, 0, 141, 72]
----[4:2]id:[com.android.systemui:id/system_icon_unstable]bounds:[512, 0, 0, 72]
-----[5:0]id:[com.android.systemui:id/statusIcons_more]bounds:[512, 0, 0, 72]
----[4:3]id:[com.android.systemui:id/system_icons_super_container]bounds:[560, 0, 448, 72]
-----[5:0]id:[com.android.systemui:id/system_icons_container]bounds:[682, 0, 251, 72]
------[6:0]id:[com.android.systemui:id/system_icons]bounds:[682, 0, 251, 72]
-------[7:0]id:[com.android.systemui:id/statusIcons]bounds:[682, 0, 117, 72]
--------[8:0][desc]content:[流量节省程序已开启]bounds:[682, 5, 42, 62]
--------[8:1][desc]content:[蓝牙已连接。]bounds:[724, 5, 33, 62]
--------[8:2][desc]content:[振铃器静音。]bounds:[757, 5, 42, 62]
-------[7:1]id:[com.android.systemui:id/battery]bounds:[799, 13, 134, 46]
--------[8:0]id:[com.android.systemui:id/battery_outside_percent][desc]content:[54%]bounds:[799, 13, 63, 46]
---------[9:0]id:[com.android.systemui:id/battery_border][desc]content:[电量剩余 54。]bounds:[862, 15, 71, 43]
---------[9:1]id:[com.android.systemui:id/battery_inside_level]bounds:[862, 15, 71, 43]
---------[9:2]id:[com.android.systemui:id/battery_inside_save]bounds:[862, 15, 71, 43]
-----[5:1]id:[com.android.systemui:id/clock][desc]content:[2:27]bounds:[933, 0, 75, 72]
-[1:6]id:[com.android.systemui:id/status_bar_container]bounds:[0, 0, 1080, 72]
--[2:0]id:[com.android.systemui:id/status_bar]bounds:[0, 0, 1080, 72]
---[3:0]id:[com.android.systemui:id/status_bar_contents]bounds:[0, 0, 1080, 72]
----[4:0]id:[com.android.systemui:id/system_icon_unstable]bounds:[330, 0, 427, 72]
-----[5:0]id:[com.android.systemui:id/notification_icon_area]bounds:[330, 0, 427, 72]
------[6:0]id:[com.android.systemui:id/notification_icon_area_inner]bounds:[330, 0, 427, 72]
-------[7:0]id:[com.android.systemui:id/notificationIcons]bounds:[330, 0, 0, 72]
----[4:1]id:[com.android.systemui:id/system_icon_area]bounds:[757, 0, 251, 72]
--[2:0]id:[com.android.systemui:id/keyguard_host_view]bounds:[0, 0, 1080, 2340]
---[3:0]id:[com.android.systemui:id/keyguard_security_container]bounds:[60, 540, 960, 1800]
----[4:0]id:[com.android.systemui:id/view_flipper]bounds:[60, 540, 960, 1800]
-----[5:0]id:[com.android.systemui:id/keyguard_fixed_length_pin_view][desc]content:[密码解锁]bounds:[60, 564, 960, 1776]
------[6:0]id:[com.android.systemui:id/row0]bounds:[60, 620, 960, 320]
-------[7:0]id:[com.android.systemui:id/rl_keyguard_message_area]bounds:[126, 620, 828, 209]
--------[8:0]id:[com.android.systemui:id/keyguard_message_area][desc]content:[输入密码]bounds:[126, 764, 828, 65]
-------[7:1]id:[com.android.systemui:id/fixedPinEntry][desc]content:[PIN 码区域]bounds:[232, 901, 615, 39]
------[6:1]id:[com.android.systemui:id/container]bounds:[60, 1368, 960, 876]
-------[7:0]id:[com.android.systemui:id/row1]bounds:[60, 1368, 960, 219]
--------[8:0]id:[com.android.systemui:id/key1][desc]content:[1]bounds:[60, 1368, 320, 219]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[1]bounds:[196, 1397, 48, 112]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[ ]bounds:[216, 1491, 9, 49]
--------[8:1]id:[com.android.systemui:id/key2][desc]content:[2]bounds:[380, 1368, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[ABC]bounds:[506, 1491, 68, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[2]bounds:[516, 1397, 48, 112]
--------[8:2]id:[com.android.systemui:id/key3][desc]content:[3]bounds:[700, 1368, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[DEF]bounds:[828, 1491, 64, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[3]bounds:[836, 1397, 48, 112]
-------[7:1]id:[com.android.systemui:id/row2]bounds:[60, 1587, 960, 219]
--------[8:0]id:[com.android.systemui:id/key4][desc]content:[4]bounds:[60, 1587, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[GHI]bounds:[190, 1710, 60, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[4]bounds:[196, 1616, 48, 112]
--------[8:1]id:[com.android.systemui:id/key5][desc]content:[5]bounds:[380, 1587, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[JKL]bounds:[509, 1710, 62, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[5]bounds:[516, 1616, 48, 112]
--------[8:2]id:[com.android.systemui:id/key6][desc]content:[6]bounds:[700, 1587, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[MNO]bounds:[820, 1710, 81, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[6]bounds:[836, 1616, 48, 112]
-------[7:2]id:[com.android.systemui:id/row3]bounds:[60, 1806, 960, 219]
--------[8:0]id:[com.android.systemui:id/key7][desc]content:[7]bounds:[60, 1806, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[PQRS]bounds:[175, 1929, 90, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[7]bounds:[196, 1835, 48, 112]
--------[8:1]id:[com.android.systemui:id/key8][desc]content:[8]bounds:[380, 1806, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[TUV]bounds:[506, 1929, 68, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[8]bounds:[516, 1835, 48, 112]
--------[8:2]id:[com.android.systemui:id/key9][desc]content:[9]bounds:[700, 1806, 320, 219]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[WXYZ]bounds:[811, 1929, 98, 49]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[9]bounds:[836, 1835, 48, 112]
-------[7:3]id:[com.android.systemui:id/row4]bounds:[60, 2025, 960, 219]
--------[8:0]id:[com.android.systemui:id/emergency_call_button_pin_view][desc]content:[紧急呼叫]bounds:[60, 2049, 320, 108]
--------[8:1]id:[com.android.systemui:id/key0][desc]content:[0]bounds:[380, 2025, 320, 219]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[0]bounds:[516, 2046, 48, 112]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[+]bounds:[527, 2135, 27, 65]
--------[8:2]id:[com.android.systemui:id/delete_back_layout]bounds:[700, 2049, 320, 195]
---------[9:0]id:[com.android.systemui:id/back_to_keyguard][desc]content:[返回]bounds:[700, 2049, 320, 108]

**Comment by TonyJiangWJ** [comment]
你这个密码默认解锁代码不支持吗？看上去应该是支持的

**Comment by here101** [comment]
哈，是吗，那可能是我手机省电策略的问题吧…………

**Comment by here101** [comment]
还有个问题我想请问一下，开启无障碍权限后我都已经成功运行了很多次了，但是为什么今天运行后一直在    成功开启autojs的辅助服务和成功关闭autojs的辅助服务      循环啊。

**Comment by TonyJiangWJ** [comment]
不知道 重启试试 授权ADB没

**Comment by TonyJiangWJ** [comment]
不知道 重启试试 授权ADB没

**Comment by here101** [comment]
授权了的。

**Comment by here101** [comment]
重启了就可以正常运行了……

**Comment by here101** [comment]
大哥，不用toast广播，您怎样解决的那个省电模式的问题啊。这个定时运行时灵，时不灵的。
