### ISSUE TITLE
脚本更新问题

### ISSUE THREAD

**Issue by Tao4167** [TonyJiangWJ/Ant-Forest#157]
运行可视化配置，点击右上角更新弹出以下提示
![fdb859136f303318a641de660d7fcc7](https://user-images.githubusercontent.com/106895115/172031946-8aab0ac7-3376-4abe-8e2e-06131473a83a.jpg)

**Comment by TonyJiangWJ** [comment]
直接运行 `update/检测更新.js` 进行更新
