### ISSUE TITLE
main.js创建桌面快捷方式显示无文件读写权限

### ISSUE THREAD

**Issue by IDontUnderstand7** [TonyJiangWJ/Ant-Forest#158]
用的是[AutoJS Modify]，在main.js右边点击三个点->更多->创建快捷方式，可以成功在桌面创建一个快捷方式的图标。
但是点击这个图标会提示“无文件读写权限：/storage/emulated/0/脚本/TonyJiang/main.js”。
之前用的AutoJs 4.1.1 alpha2版本没有这个问题，可以正常创建快捷方式，点击快捷方式图标就可以直接运行main.js。
希望得到您的解答

**Comment by TonyJiangWJ** [comment]
并不支持这个功能 谢谢
