### ISSUE TITLE
关于更换手机使用MIUI 13之后能量球无法点击的问题

### ISSUE THREAD

**Issue by fengsidu** [TonyJiangWJ/Ant-Forest#159]
手机型号：MI 11 Ultra
Android 12
MIUI 13.0.12 稳定版

日志如下，也使用了群里的Auto js 修改版.android12
![O3HXAVUG_X_8PEB~FW62BD7](https://user-images.githubusercontent.com/54129071/172989393-30570e63-5afb-44f4-a1ce-be42fbccbe5c.jpg)

**Comment by TonyJiangWJ** [comment]
逛一逛等配置信息不正确，请确认是不是自己换了手机直接复制了配置或者修改了手机动态分辨率，请自行参考README相关说明 或者直接重置默认配置让脚本自动生成区域配置信息。
