### ISSUE TITLE
请作者帮忙写个解锁设备的

### ISSUE THREAD

**Issue by cc082295** [TonyJiangWJ/Ant-Forest#161]
请作者帮忙写个解锁设备的脚本
[info.log](https://github.com/TonyJiangWJ/Ant-Forest/files/8926084/info.log)

**Comment by TonyJiangWJ** [comment]
大致看了一下 你这个布局 默认代码应该支持的。解不开吗 提供一下AutoJS运行日志看看

**Comment by cc082295** [comment]
请问在锁屏，黑屏的状态下，脚本能自动点亮屏幕，自动解锁吗？为什么我始终无法运行

**Comment by TonyJiangWJ** [comment]
> 请问在锁屏，黑屏的状态下，脚本能自动点亮屏幕，自动解锁吗？为什么我始终无法运行

定时任务有创建吗 安装最新的修改版试试 电量无限制、自启动等权限都给了吗 或者可能你手机系统限制了吧
