### ISSUE TITLE
为什么有的时候能量就能收到，有的时候明明有能量但是就收不到？

### ISSUE THREAD

**Issue by cc082295** [TonyJiangWJ/Ant-Forest#163]
为什么有的时候能量就能收到，有的时候明明有能量但是就收不到？
是因为能量球位置的关系吗？

**Comment by TonyJiangWJ** [comment]
识别不到呗 等后续优化

**Comment by AFUL1991** [comment]
> 识别不到呗 等后续优化

我觉得这个项目[Ant-Forest](https://github.com/SuperMonster003/Ant-Forest)的识别，以及自动下次运行时间感觉比较好。

强烈建议根据这个项目的自动运行方式改一下。

**Comment by TonyJiangWJ** [comment]
@cc082295 更新新版试试
@AFUL1991 那你可以直接用这个项目呀 我们两个作者各自有各自的实现方式 并不需要照搬对方的

**Comment by AFUL1991** [comment]
>
> @cc082295 更新新版试试 @AFUL1991 那你可以直接用这个项目呀 我们两个作者各自有各自的实现方式 并不需要照搬对方的

他那个现在还是基于老版本的app，经常出问题。他现在在改app。
你这个基于自己修改后的app，相对来说我觉得问题少一些。
当然，你改不改无所谓，等到那边app改好了后，我可能就会用那个，因为我觉得那个使用更傻瓜，且更准确一些。

**Comment by TonyJiangWJ** [comment]
有能力就自己改代码，拉踩谁不会 我们两个作者都认识对方 别给我们找不痛快

**Comment by AFUL1991** [comment]
> 有能力就自己改代码，拉踩谁不会 我们两个作者都认识对方 别给我们找不痛快

我拉踩谁了？？
你说的 “那你可以直接用这个项目呀 我们两个作者各自有各自的实现方式 并不需要照搬对方的”
我说的“当然，你改不改无所谓，等到那边app改好了后，我可能就会用那个，因为我觉得那个使用更傻瓜，且更准确一些。”

这算什么拉踩？我只不过建议加一个自动更新，你直接说你不需要就行，上来就是各种嘲讽。这有意思吗？

**Comment by TonyJiangWJ** [comment]
@cc082295 更新最新版的试试
