### ISSUE TITLE
关于对双屏设备的适配

### ISSUE THREAD

**Issue by iciness** [TonyJiangWJ/Ant-Forest#164]
刚入手了mate x2，外屏似乎对屏幕大小识别不正确，然后也无法收取能量
我需要提供哪些数据
![Screenshot_20220620_085723_com eg android AlipayGphone](https://user-images.githubusercontent.com/4505686/175232844-14dc6a1b-4c9a-4fea-bb83-13decfcdc040.jpg)
![Screenshot_20220620_090833_org autojs autojs modify](https://user-images.githubusercontent.com/4505686/175232849-3828fb52-8947-4fcb-8a23-184c0da072fa.jpg)
![Screenshot_20220623_143859_org autojs autojs modify](https://user-images.githubusercontent.com/4505686/175232857-9745d2a7-9ba8-4a18-8c79-41b1778067ea.jpg)

**Comment by TonyJiangWJ** [comment]
抱歉 无法支持 建议自己修改代码
