### ISSUE TITLE
疑似存在内存溢出？

### ISSUE THREAD

**Issue by xzhlksh** [TonyJiangWJ/Ant-Forest#166]
如题
长时间运行脚本后，脚本容易出现能点击允许截图但是反复说自己找不到允许截图按钮的情况。一般三小时重启一下autojs就能规避这个问题，但是太麻烦了，想问一下大佬能不能分析一下日志找一下原因？蚂蚁森林和庄园都有这个问题
[logs20220703.zip](https://github.com/TonyJiangWJ/Ant-Forest/files/9033950/logs20220703.zip)
？

**Comment by TonyJiangWJ** [comment]
没空看 自己检查以下有没有授权自启动、电量无限制 以及参考如下内容进行ADB授权一下不需要截图弹窗请求https://github.com/TonyJiangWJ/Ant-Forest/issues/130

**Comment by xzhlksh** [comment]
adb赋权限了，还是不行，会弹toast：上次有漏收，再次收集。然后就反复上下滑动屏幕
反复弹了几次toast就啥都不干退出脚本了
大概是6月的某次更新后就这样了

另外，偶尔逛一逛逛到剩余不到1分钟的能量，为什么会添加到排行榜识别的白名单里啊？遇到好几次逛一逛剩余1分钟，然后再逛排行榜的时候变小手都不进去，或者排行榜也是1分钟但是不识别
