### ISSUE TITLE
对main.js设置的每日定时运行不生效

### ISSUE THREAD

**Issue by linyecheng** [TonyJiangWJ/Ant-Forest#168]
对main.js设置的每日定时运行，但是一直不生效，不知大家有遇到这个情况吗

**Comment by here101** [comment]
我是设置好自启动那些，然后充上电，这样的话每天早上就会正常自动运行了。

**Comment by linyecheng** [comment]
> 我是从那些开始设置好的，然后充上电，这样的话每天早上就能正常自动运行了。

不知什么情况，我重新安装了软件后就可以了，谢谢。
