### ISSUE TITLE
自动锁屏问题

### ISSUE THREAD

**Issue by yuanchen1** [TonyJiangWJ/Ant-Forest#170]
**目前已在extends创建LockScreen.js,脚本内容要如何写**

总分析耗时：6318ms 总控件数：224

=================
锁屏界面:
分析耗时：504ms
控件总数：90
分析控件内容：
-[1:0]id:[com.android.systemui:id/scrim_behind]bounds:[0, 0, 1080, 1920]
-[1:1]id:[com.android.systemui:id/notification_panel]bounds:[0, 0, 1080, 1920]
--[2:0]id:[com.android.systemui:id/wallpaper]bounds:[0, 0, 1080, 1920]
--[2:1]id:[com.android.systemui:id/notification_container_parent]bounds:[0, 0, 1080, 1920]
---[3:0]id:[com.android.systemui:id/keyguard_header]bounds:[0, 0, 1080, 72]
------[6:0]id:[com.android.systemui:id/notchLeftEar]bounds:[6, 36, 348, 0]
-----[5:0]id:[com.android.systemui:id/keyguard_carrier_super_container]bounds:[6, 0, 348, 72]
------[6:0]id:[com.android.systemui:id/keyguard_carrier_container]bounds:[6, 0, 192, 72]
-------[7:0]id:[com.android.systemui:id/keyguard_carrier_text][desc]content:[仅可紧急通话]bounds:[6, 0, 192, 72]
----[4:2]id:[com.android.systemui:id/system_icons_super_container]bounds:[744, 0, 336, 72]
-----[5:0]id:[com.android.systemui:id/system_icons_container]bounds:[753, 0, 321, 72]
------[6:0]id:[com.android.systemui:id/system_icons]bounds:[753, 6, 321, 60]
-------[7:0]id:[com.android.systemui:id/statusIcons]bounds:[753, 6, 82, 60]
--------[8:0][desc]content:[蓝牙开启。]bounds:[753, 6, 35, 60]
--------[8:1][desc]content:[振铃器振动。]bounds:[788, 6, 47, 60]
-------[7:1]id:[com.android.systemui:id/signal_cluster_view]bounds:[835, 6, 112, 60]
--------[8:0]id:[com.android.systemui:id/signal_cluster]bounds:[835, 6, 112, 60]
---------[9:0]id:[com.android.systemui:id/mobile_signal_group_dual_notch]bounds:[835, 6, 10, 60]
----------[10:0]id:[com.android.systemui:id/mobile_combo]bounds:[835, 6, 10, 60]
-----------[11:0]id:[com.android.systemui:id/notch_mobile]bounds:[835, 6, 0, 60]
------------[12:0]id:[com.android.systemui:id/notch_mobile_signal2]bounds:[835, 36, 0, 0]
------------[12:1]id:[com.android.systemui:id/notch_mobile_signal]bounds:[835, 36, 0, 0]
-----------[11:1]id:[com.android.systemui:id/carrier]bounds:[835, 6, 5, 60]
-----------[11:2]id:[com.android.systemui:id/mobile_type]bounds:[840, 6, 5, 60]
------------[12:0]id:[com.android.systemui:id/mobile_signal_upgrade]bounds:[845, 36, 0, 0]
------------[12:1]id:[com.android.systemui:id/mobile_inout]bounds:[845, 36, 0, 0]
---------[9:1]id:[com.android.systemui:id/mobile_signal_group_1]bounds:[835, 36, 0, 0]
---------[9:2]id:[com.android.systemui:id/mobile_signal_group_0]bounds:[835, 36, 0, 0]
---------[9:3]id:[com.android.systemui:id/no_sims_combo][desc]content:[没有 SIM 卡。]bounds:[845, 9, 47, 53]
----------[10:0]id:[com.android.systemui:id/no_sims_dark]bounds:[845, 9, 47, 53]
----------[10:1]id:[com.android.systemui:id/no_sims]bounds:[845, 9, 47, 53]
---------[9:4]id:[com.android.systemui:id/wifi_combo][desc]content:[WLAN 信号满格。]bounds:[892, 9, 55, 53]
----------[10:0]id:[com.android.systemui:id/wifi_inout]bounds:[892, 9, 55, 53]
----------[10:1]id:[com.android.systemui:id/wifi_signal]bounds:[892, 9, 55, 53]
---------[9:6]id:[com.android.systemui:id/wifi_signal_spacer]bounds:[947, 30, 0, 12]
-------[7:2]id:[com.android.systemui:id/battery]bounds:[947, 6, 127, 60]
---------[9:0]id:[com.android.systemui:id/battery_image][desc]content:[正在充电，已完成百分之100。]bounds:[994, 6, 80, 60]
---------[9:1]id:[com.android.systemui:id/battery_digit][desc]content:[100]bounds:[1014, 6, 39, 60]
---[3:1]id:[com.android.systemui:id/notification_stack_scroller]bounds:[28, 0, 1024, 1920]
-----[5:0]id:[com.android.systemui:id/veto]bounds:[28, 636, 144, 0]
-----[5:1]id:[com.android.systemui:id/backgroundNormal]bounds:[28, 636, 1024, 319]
-----[5:2]id:[com.android.systemui:id/expanded]bounds:[28, 636, 1024, 319]
------[6:0]id:[android:id/status_bar_latest_event_content]bounds:[28, 636, 1024, 197]
-------[7:0]id:[android:id/right_icon][desc]content:[Android 系统]bounds:[60, 672, 110, 110]
--------[8:0]id:[android:id/notification_main_column]bounds:[194, 671, 821, 110]
---------[9:0]id:[android:id/line1]bounds:[194, 671, 821, 53]
----------[10:0]id:[android:id/title][desc]content:[正在通过 USB 充电]bounds:[194, 671, 821, 53]
----------[10:0]id:[android:id/text][desc]content:[点按即可查看更多选项。]bounds:[194, 732, 821, 49]
-----[5:3]id:[com.android.systemui:id/fake_shadow]bounds:[28, 636, 1024, 319]
-----[5:0]id:[com.android.systemui:id/veto]bounds:[28, 844, 144, 0]
-----[5:1]id:[com.android.systemui:id/backgroundNormal]bounds:[28, 844, 1024, 319]
-----[5:2]id:[com.android.systemui:id/expanded]bounds:[28, 844, 1024, 319]
------[6:0]id:[android:id/status_bar_latest_event_content]bounds:[28, 844, 1024, 197]
-------[7:0]id:[android:id/right_icon][desc]content:[Android 系统]bounds:[60, 880, 110, 110]
--------[8:0]id:[android:id/notification_main_column]bounds:[194, 879, 821, 110]
---------[9:0]id:[android:id/line1]bounds:[194, 879, 821, 53]
----------[10:0]id:[android:id/title][desc]content:[已连接到USB调试]bounds:[194, 879, 821, 53]
----------[10:0]id:[android:id/text][desc]content:[点按即可停用 USB 调试功能。]bounds:[194, 940, 821, 49]
-----[5:3]id:[com.android.systemui:id/fake_shadow]bounds:[28, 844, 1024, 319]
---[3:2]id:[com.android.systemui:id/qs_frame]bounds:[28, 0, 1024, 1920]
----[4:0]id:[com.android.systemui:id/quick_settings_container]bounds:[28, 0, 1024, -18]
-----[5:0]id:[com.android.systemui:id/qs_content]bounds:[28, 0, 1024, -18]
------[6:0]id:[com.android.systemui:id/qs_container]bounds:[28, 0, 1024, -18]
-------[7:0]id:[com.android.systemui:id/qs_background]bounds:[28, 0, 1024, -224]
-------[7:1]id:[com.android.systemui:id/qs_footer_bundle]bounds:[28, 0, 1024, -18]
--[2:3]id:[com.android.systemui:id/keyguard_right_view]bounds:[1080, 0, 0, 1920]
--[2:4]id:[com.android.systemui:id/keyguard_clock_view]bounds:[0, 0, 1080, 911]
---[3:0]id:[com.android.systemui:id/miui_keyguard_clock]bounds:[0, 115, 1080, 796]
----[4:0]id:[com.android.systemui:id/time_layout]bounds:[0, 209, 1080, 645]
-----[5:0]id:[com.android.systemui:id/horizontal_time_layout]bounds:[317, 209, 445, 324]
------[6:0]id:[com.android.systemui:id/horizontal_hour][desc]content:[8]bounds:[317, 303, 128, 230]
------[6:1]id:[com.android.systemui:id/horizontal_dot][desc]content:[:]bounds:[445, 303, 62, 230]
------[6:2]id:[com.android.systemui:id/horizontal_min][desc]content:[09]bounds:[507, 303, 255, 230]
-----[5:1]id:[com.android.systemui:id/vertical_time_layout]bounds:[398, 209, 284, 645]
------[6:0]id:[com.android.systemui:id/vertical_hour][desc]content:[08]bounds:[398, 209, 284, 435]
------[6:1]id:[com.android.systemui:id/vertical_min][desc]content:[09]bounds:[398, 609, 284, 245]
----[4:1]id:[com.android.systemui:id/date_and_battery_info]bounds:[346, 527, 387, 63]
-----[5:0]id:[com.android.systemui:id/current_date][desc]content:[7月22日 周五上午]bounds:[346, 527, 387, 63]
--[2:5]id:[com.android.systemui:id/keyguard_bottom_area]bounds:[0, 1590, 1080, 330]
---[3:0]id:[com.android.systemui:id/miui_keyguard_charging_info_id]bounds:[0, 1590, 1080, 330]
----[4:0]id:[com.android.systemui:id/battery_charging_view]bounds:[450, 1596, 180, 180]
---[3:1]id:[com.android.systemui:id/left_button_layout]bounds:[0, 1752, 336, 168]
----[4:0]id:[com.android.systemui:id/left_button][desc]content:[锁屏画报]bounds:[0, 1752, 168, 168]
---[3:2]id:[com.android.systemui:id/keyguard_indication_area]bounds:[168, 1752, 744, 168]
----[4:0]id:[com.android.systemui:id/keyguard_indication_text][desc]content:[预计可用27小时13分]bounds:[361, 1809, 357, 53]
---[3:3]id:[com.android.systemui:id/right_button_layout]bounds:[744, 1752, 336, 168]
----[4:0]id:[com.android.systemui:id/right_button][desc]content:[相机]bounds:[912, 1752, 168, 168]
-[1:2]id:[com.android.systemui:id/scrim_in_front]bounds:[0, 0, 1080, 1920]
-[1:3]id:[com.android.systemui:id/heads_up_scrim]bounds:[0, 0, 1080, 750]
-[1:4]id:[com.android.systemui:id/status_bar_container]bounds:[0, 0, 1080, 72]
=================
密码输入界面:
分析耗时：532ms
控件总数：134
分析控件内容：
-[1:0]id:[com.android.systemui:id/scrim_behind]bounds:[0, 0, 1080, 1920]
-[1:1]id:[com.android.systemui:id/notification_panel]bounds:[0, 0, 1080, 1920]
--[2:0]id:[com.android.systemui:id/wallpaper]bounds:[0, 0, 1080, 1920]
--[2:1]id:[com.android.systemui:id/notification_container_parent]bounds:[0, 0, 1080, 1920]
---[3:0]id:[com.android.systemui:id/keyguard_header]bounds:[0, 0, 1080, 72]
------[6:0]id:[com.android.systemui:id/notchLeftEar]bounds:[6, 36, 348, 0]
-----[5:0]id:[com.android.systemui:id/keyguard_carrier_super_container]bounds:[6, 0, 348, 72]
------[6:0]id:[com.android.systemui:id/keyguard_carrier_container]bounds:[6, 0, 192, 72]
-------[7:0]id:[com.android.systemui:id/keyguard_carrier_text][desc]content:[仅可紧急通话]bounds:[6, 0, 192, 72]
----[4:2]id:[com.android.systemui:id/system_icons_super_container]bounds:[744, 0, 336, 72]
-----[5:0]id:[com.android.systemui:id/system_icons_container]bounds:[753, 0, 321, 72]
------[6:0]id:[com.android.systemui:id/system_icons]bounds:[753, 6, 321, 60]
-------[7:0]id:[com.android.systemui:id/statusIcons]bounds:[753, 6, 82, 60]
--------[8:0][desc]content:[蓝牙开启。]bounds:[753, 6, 35, 60]
--------[8:1][desc]content:[振铃器振动。]bounds:[788, 6, 47, 60]
-------[7:1]id:[com.android.systemui:id/signal_cluster_view]bounds:[835, 6, 112, 60]
--------[8:0]id:[com.android.systemui:id/signal_cluster]bounds:[835, 6, 112, 60]
---------[9:0]id:[com.android.systemui:id/mobile_signal_group_dual_notch]bounds:[835, 6, 10, 60]
----------[10:0]id:[com.android.systemui:id/mobile_combo]bounds:[835, 6, 10, 60]
-----------[11:0]id:[com.android.systemui:id/notch_mobile]bounds:[835, 6, 0, 60]
------------[12:0]id:[com.android.systemui:id/notch_mobile_signal2]bounds:[835, 36, 0, 0]
------------[12:1]id:[com.android.systemui:id/notch_mobile_signal]bounds:[835, 36, 0, 0]
-----------[11:1]id:[com.android.systemui:id/carrier]bounds:[835, 6, 5, 60]
-----------[11:2]id:[com.android.systemui:id/mobile_type]bounds:[840, 6, 5, 60]
------------[12:0]id:[com.android.systemui:id/mobile_signal_upgrade]bounds:[845, 36, 0, 0]
------------[12:1]id:[com.android.systemui:id/mobile_inout]bounds:[845, 36, 0, 0]
---------[9:1]id:[com.android.systemui:id/mobile_signal_group_1]bounds:[835, 36, 0, 0]
---------[9:2]id:[com.android.systemui:id/mobile_signal_group_0]bounds:[835, 36, 0, 0]
---------[9:3]id:[com.android.systemui:id/no_sims_combo][desc]content:[没有 SIM 卡。]bounds:[845, 9, 47, 53]
----------[10:0]id:[com.android.systemui:id/no_sims_dark]bounds:[845, 9, 47, 53]
----------[10:1]id:[com.android.systemui:id/no_sims]bounds:[845, 9, 47, 53]
---------[9:4]id:[com.android.systemui:id/wifi_combo][desc]content:[WLAN 信号满格。]bounds:[892, 9, 55, 53]
----------[10:0]id:[com.android.systemui:id/wifi_inout]bounds:[892, 9, 55, 53]
----------[10:1]id:[com.android.systemui:id/wifi_signal]bounds:[892, 9, 55, 53]
---------[9:6]id:[com.android.systemui:id/wifi_signal_spacer]bounds:[947, 30, 0, 12]
-------[7:2]id:[com.android.systemui:id/battery]bounds:[947, 6, 127, 60]
---------[9:0]id:[com.android.systemui:id/battery_image][desc]content:[正在充电，已完成百分之100。]bounds:[994, 6, 80, 60]
---------[9:1]id:[com.android.systemui:id/battery_digit][desc]content:[100]bounds:[1014, 6, 39, 60]
---[3:1]id:[com.android.systemui:id/notification_stack_scroller]bounds:[28, 0, 1024, -1536]
-----[5:0]id:[com.android.systemui:id/veto]bounds:[28, 0, 144, -2820]
-----[5:1]id:[com.android.systemui:id/backgroundNormal]bounds:[28, 0, 1024, -2501]
-----[5:2]id:[com.android.systemui:id/expanded]bounds:[28, 0, 1024, -2501]
------[6:0]id:[android:id/status_bar_latest_event_content]bounds:[28, 0, 1024, -2623]
-------[7:0]id:[android:id/right_icon][desc]content:[Android 系统]bounds:[60, 0, 110, -2674]
--------[8:0]id:[android:id/notification_main_column]bounds:[194, 0, 821, -2675]
---------[9:0]id:[android:id/line1]bounds:[194, 0, 821, -2732]
----------[10:0]id:[android:id/title][desc]content:[正在通过 USB 充电]bounds:[194, 0, 821, -2732]
----------[10:0]id:[android:id/text][desc]content:[点按即可查看更多选项。]bounds:[194, 0, 821, -2675]
-----[5:3]id:[com.android.systemui:id/fake_shadow]bounds:[28, 0, 1024, -2501]
-----[5:0]id:[com.android.systemui:id/veto]bounds:[28, 0, 144, -2612]
-----[5:1]id:[com.android.systemui:id/backgroundNormal]bounds:[28, 0, 1024, -2293]
-----[5:2]id:[com.android.systemui:id/expanded]bounds:[28, 0, 1024, -2293]
------[6:0]id:[android:id/status_bar_latest_event_content]bounds:[28, 0, 1024, -2415]
-------[7:0]id:[android:id/right_icon][desc]content:[Android 系统]bounds:[60, 0, 110, -2466]
--------[8:0]id:[android:id/notification_main_column]bounds:[194, 0, 821, -2467]
---------[9:0]id:[android:id/line1]bounds:[194, 0, 821, -2524]
----------[10:0]id:[android:id/title][desc]content:[已连接到USB调试]bounds:[194, 0, 821, -2524]
----------[10:0]id:[android:id/text][desc]content:[点按即可停用 USB 调试功能。]bounds:[194, 0, 821, -2467]
-----[5:3]id:[com.android.systemui:id/fake_shadow]bounds:[28, 0, 1024, -2293]
---[3:2]id:[com.android.systemui:id/qs_frame]bounds:[28, 0, 1024, 1920]
----[4:0]id:[com.android.systemui:id/quick_settings_container]bounds:[28, 0, 1024, -18]
-----[5:0]id:[com.android.systemui:id/qs_content]bounds:[28, 0, 1024, -18]
------[6:0]id:[com.android.systemui:id/qs_container]bounds:[28, 0, 1024, -18]
-------[7:0]id:[com.android.systemui:id/qs_background]bounds:[28, 0, 1024, -224]
-------[7:1]id:[com.android.systemui:id/qs_footer_bundle]bounds:[28, 0, 1024, -18]
--[2:3]id:[com.android.systemui:id/keyguard_right_view]bounds:[1080, 0, 0, 1920]
--[2:4]id:[com.android.systemui:id/keyguard_clock_view]bounds:[0, 0, 1080, -2545]
---[3:0]id:[com.android.systemui:id/miui_keyguard_clock]bounds:[0, 0, 1080, -2545]
----[4:0]id:[com.android.systemui:id/time_layout]bounds:[0, 0, 1080, -2602]
-----[5:0]id:[com.android.systemui:id/horizontal_time_layout]bounds:[317, 0, 445, -2923]
------[6:0]id:[com.android.systemui:id/horizontal_hour][desc]content:[8]bounds:[317, 0, 128, -2923]
------[6:1]id:[com.android.systemui:id/horizontal_dot][desc]content:[:]bounds:[445, 0, 62, -2923]
------[6:2]id:[com.android.systemui:id/horizontal_min][desc]content:[09]bounds:[507, 0, 255, -2923]
-----[5:1]id:[com.android.systemui:id/vertical_time_layout]bounds:[398, 0, 284, -2602]
------[6:0]id:[com.android.systemui:id/vertical_hour][desc]content:[08]bounds:[398, 0, 284, -2812]
------[6:1]id:[com.android.systemui:id/vertical_min][desc]content:[09]bounds:[398, 0, 284, -2602]
----[4:1]id:[com.android.systemui:id/date_and_battery_info]bounds:[346, 0, 387, -2866]
-----[5:0]id:[com.android.systemui:id/current_date][desc]content:[7月22日 周五上午]bounds:[346, 0, 387, -2866]
--[2:5]id:[com.android.systemui:id/keyguard_bottom_area]bounds:[0, 1590, 1080, 330]
---[3:0]id:[com.android.systemui:id/miui_keyguard_charging_info_id]bounds:[0, 1590, 1080, 330]
----[4:0]id:[com.android.systemui:id/battery_charging_view]bounds:[450, 1596, 180, 180]
---[3:1]id:[com.android.systemui:id/left_button_layout]bounds:[0, 1752, 336, 168]
----[4:0]id:[com.android.systemui:id/left_button][desc]content:[锁屏画报]bounds:[0, 1752, 168, 168]
---[3:2]id:[com.android.systemui:id/keyguard_indication_area]bounds:[168, 1752, 744, 168]
----[4:0]id:[com.android.systemui:id/keyguard_indication_text][desc]content:[预计可用27小时13分]bounds:[361, 1809, 357, 53]
---[3:3]id:[com.android.systemui:id/right_button_layout]bounds:[744, 1752, 336, 168]
----[4:0]id:[com.android.systemui:id/right_button][desc]content:[相机]bounds:[912, 1752, 168, 168]
-[1:2]id:[com.android.systemui:id/scrim_in_front]bounds:[0, 0, 1080, 1920]
-[1:4]id:[com.android.systemui:id/heads_up_scrim]bounds:[0, 0, 1080, 750]
-[1:5]id:[com.android.systemui:id/status_bar_container]bounds:[0, 0, 1080, 72]
--[2:0]id:[com.android.systemui:id/keyguard_host_view]bounds:[0, 0, 1080, 1920]
---[3:0]id:[com.android.systemui:id/keyguard_security_container]bounds:[0, 0, 1080, 1920]
----[4:0]id:[com.android.systemui:id/view_flipper]bounds:[0, 0, 1080, 1920]
-----[5:0]id:[com.android.systemui:id/keyguard_pin_view]bounds:[0, 0, 1080, 1836]
------[6:0]id:[com.android.systemui:id/container]bounds:[90, 591, 900, 1245]
-------[7:0]id:[com.android.systemui:id/row0]bounds:[90, 414, 900, 177]
--------[8:0]id:[com.android.systemui:id/pinEntry][desc]content:[密码区域]bounds:[217, 366, 645, 225]
-------[7:1]id:[com.android.systemui:id/row1]bounds:[90, 841, 900, 170]
--------[8:0]id:[com.android.systemui:id/key1][desc]content:[1]bounds:[90, 771, 300, 70]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[1]bounds:[220, 730, 41, 111]
--------[8:1]id:[com.android.systemui:id/key2][desc]content:[2]bounds:[390, 771, 300, 70]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[2]bounds:[516, 730, 49, 111]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[ABC]bounds:[517, 748, 47, 93]
--------[8:2]id:[com.android.systemui:id/key3][desc]content:[3]bounds:[690, 771, 300, 70]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[3]bounds:[816, 730, 49, 111]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[DEF]bounds:[819, 748, 43, 93]
-------[7:2]id:[com.android.systemui:id/row2]bounds:[90, 1027, 900, 170]
--------[8:0]id:[com.android.systemui:id/key4][desc]content:[4]bounds:[90, 1027, 300, 16]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[4]bounds:[215, 1002, 51, 25]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[GHI]bounds:[220, 1020, 40, 7]
--------[8:1]id:[com.android.systemui:id/key5][desc]content:[5]bounds:[390, 1027, 300, 16]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[5]bounds:[516, 1002, 49, 25]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[JKL]bounds:[520, 1020, 41, 7]
--------[8:2]id:[com.android.systemui:id/key6][desc]content:[6]bounds:[690, 1027, 300, 16]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[MNO]bounds:[813, 1020, 55, 7]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[6]bounds:[815, 1002, 50, 25]
-------[7:3]id:[com.android.systemui:id/row3]bounds:[90, 1213, 900, 170]
--------[8:0]id:[com.android.systemui:id/key7][desc]content:[7]bounds:[90, 1213, 300, 84]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[PQRS]bounds:[210, 1246, 61, 28]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[7]bounds:[219, 1213, 43, 43]
--------[8:1]id:[com.android.systemui:id/key8][desc]content:[8]bounds:[390, 1213, 300, 84]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[8]bounds:[515, 1213, 51, 43]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[TUV]bounds:[518, 1246, 45, 28]
--------[8:2]id:[com.android.systemui:id/key9][desc]content:[9]bounds:[690, 1213, 300, 84]
---------[9:0]id:[com.android.systemui:id/klondike_text][desc]content:[WXYZ]bounds:[808, 1246, 64, 28]
---------[9:1]id:[com.android.systemui:id/digit_text][desc]content:[9]bounds:[816, 1213, 49, 43]
-------[7:4]id:[com.android.systemui:id/row4]bounds:[90, 1399, 900, 170]
--------[8:0]id:[com.android.systemui:id/key0][desc]content:[0]bounds:[390, 1399, 300, 132]
---------[9:0]id:[com.android.systemui:id/digit_text][desc]content:[0]bounds:[515, 1399, 50, 91]
---------[9:1]id:[com.android.systemui:id/klondike_text][desc]content:[+]bounds:[533, 1480, 14, 28]
-------[7:5]id:[com.android.systemui:id/keyguard_selector_fade_container]bounds:[90, 1576, 900, 170]
--------[8:0]id:[com.android.systemui:id/emergency_call_button][desc]content:[紧急呼叫]bounds:[90, 1576, 300, 170]
--------[8:1]id:[com.android.systemui:id/back_button][desc]content:[返回]bounds:[690, 1576, 300, 170]
--[2:1]id:[com.android.systemui:id/keyguard_bouncer_bg]bounds:[0, 0, 1080, 1920]

**Comment by TonyJiangWJ** [comment]
安卓版本？9以及以上都能通过无障碍自动锁屏不需要自己写锁屏代码。如果安卓9以下需要自己在控制中心或者桌面放一键锁屏的按钮 然后写代码对固定坐标进行点击，具体代码只能你自己写。另外你给的这些日志是在解锁的时候才需要的，对自动锁屏没有任何用处。
