### ISSUE TITLE
检测到截图的宽度大于高度，可能截图方法出现了问题，请尝试强制重启AutoJS，否则脚本无法正常运行! w:2340 h:1080

### ISSUE THREAD

**Issue by songjiang951130** [TonyJiangWJ/Ant-Forest#173]
11:24:34.703/V: 开始运行[/storage/emulated/0/脚本/main.js]
11:24:34.759/V: config未实例化，准备实例化config.js
11:24:34.918/V: 95 使用异步日志
11:24:34.930/V: 订阅文件消息：/data/user/0/org.autojs.autojs.modify/cache/ant_forest_config_fork_version/.configShare
11:24:35.170/V: 通过event.on('exit')注册生命周期回调
11:24:35.203/V: 待执行的alter sqls: ["create index idx_date_friend on ENERGY_COLLECT_DATA(COLLECT_DATE,FRIEND_NAME)","create index idx_date on MY_ENERGY_DATA(ENERGY_DATE,ENERGY)"]
11:24:35.285/V: 当前数据库版本号：1
11:24:35.286/V: 准备初始化表数据:ENERGY_COLLECT_DATA
11:24:35.288/V: 准备初始化表数据IdentifyMap:ENERGY_COLLECT_DATA
11:24:35.315/V: 准备初始化表数据ColumnConvertMap:ENERGY_COLLECT_DATA
11:24:35.317/V: 准备初始化表数据:MY_ENERGY_DATA
11:24:35.318/V: 准备初始化表数据IdentifyMap:MY_ENERGY_DATA
11:24:35.320/V: 准备初始化表数据ColumnConvertMap:MY_ENERGY_DATA
11:24:35.321/V: 初始化数据库成功
11:24:35.322/V: 查询参数 date:2022-08-02 time: 2022-08-02 10:24:35
11:24:35.326/V: 查询参数 date:2022-08-02 time: 2022-08-02 10:24:35-2022-08-02 11:24:35
11:24:35.328/V: 最近1小时内收集好友能量：0 g 未达到冷却值: 600
11:24:35.329/D: ======单脚本运行直接清空任务队列=======
11:24:35.332/D: 清除数据成功
11:24:35.333/D: ======尝试加入任务队列，并关闭重复运行的脚本=======
11:24:35.336/V: 队列小于等于1 不需要去重:null
11:24:35.340/V: 当前无任务等待，直接执行：{"source":"/storage/emulated/0/脚本/main.js","engineId":95}
11:24:35.342/V: 设置脚本状态为执行中
11:24:35.345/V: 当前脚本信息 id:95 source:/storage/emulated/0/脚本/main.js 运行中脚本数量：1
11:24:35.346/D: ======加入任务队列成功=======
11:24:35.347/D: ======基于图像分析模式：加载dex=======
11:24:35.361/D: =======加载dex完成=======
11:24:35.382/V: Is _origin_images null? false.
11:24:35.386/V: 当前可用内存：1547878400b 1476.171875MB
11:24:35.389/V: 预估单张图片大小：1.5063285827636719MB
11:24:35.391/V: 支持最大图片张数：100 一半：50
11:24:35.393/V: 图片资源代理创建完毕，准备替换scope中的images
11:24:35.394/V: 图片资源代理替换images完毕
11:24:35.419/D: 使用内置解锁模块
11:24:35.442/I: 当前OpenCV版本：4.5.5
11:24:35.491/D: ======校验无障碍功能======
11:24:35.500/D: ---前置校验完成;启动系统--->>>>
11:24:35.502/D: 版本信息：1.3.6.7.2
11:24:35.503/I: 本脚本免费使用，更多说明可前往github查阅README.md，地址：https://github.com/TonyJiangWJ/Ant-Forest
11:24:35.504/D: AutoJS version: 4.1.22.0621.alpha Modify
11:24:35.504/D: device info: HONOR NTH-AN00 12
11:24:35.505/D: 运行模式：单脚本运行无视运行队列 循环2次 基于图像分析 排行榜可收取判定方式：自动判断是否可收取 使用模拟滑动, 底部高度：200
11:24:35.505/D: 设备分辨率：[1080, 2340]
11:24:35.506/W: 脚本会自动识别排行榜顶部和底部区域，首次运行时自动识别需要一定时间，请不要手动关闭脚本
11:24:35.506/W: 以上配置的详细内容请见README.md
11:24:35.507/D: ======解锁并校验截图权限======
11:24:35.508/D: 已解锁
11:24:35.509/D: 不需要重新锁定屏幕
11:24:35.510/V: windowRoots size: 1
11:24:35.511/V: 获取包名总耗时：2ms
11:24:35.512/D: 当前包名：org.autojs.autojs.modify
11:24:35.513/V: try to find one: 向商家付(钱|款) timeout: 1000ms
11:24:36.520/V: cannot find any matches 向商家付(钱|款) timeout:1000
11:24:36.522/V: timeout for finding 向商家付(钱|款)
11:24:36.523/D: 解锁成功
11:24:36.524/V: 启动参数：{}
11:24:37.036/V: try to find one: START NOW|立即开始|允许 timeout: 8000ms
11:24:37.042/V: find text START NOW|立即开始|允许  允许
11:24:37.456/W: 未能找到id:android:id/checkbox对应的控件
11:24:37.668/W: 未能找到id:com.android.systemui:id/remember对应的控件
11:24:37.675/W: 未找到记住按钮
11:24:37.680/V: 点击允许截图权限
11:24:37.685/V: try to find one: START NOW|立即开始|允许 timeout: 200ms
11:24:37.710/V: find text START NOW|立即开始|允许  允许
11:24:37.974/V: 请求截屏权限结束：true
11:24:37.975/D: 请求截屏权限成功
11:24:38.103/V: action执行结束: true 耗时：127ms
11:24:38.103/V: 获取截图耗时：128ms
11:24:38.104/E: 检测到截图的宽度大于高度，可能截图方法出现了问题，请尝试强制重启AutoJS，否则脚本无法正常运行! w:2340 h:1080
11:24:38.110/V: 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/main.js","engineId":95,"timeout":1659411575341} 超时剩余时间：897秒
11:24:38.119/V: 准备移除运行中任务
11:24:38.129/V: 队列小于等于1 不需要去重:null
11:24:38.131/V: 无任务等待中
11:24:38.134/V: 设置脚本状态为执行完毕
11:24:38.137/I: 预订[5]分钟后的任务，时间：2022-08-02 11:29:38(1659410978136)
11:24:38.225/V: 定时任务预定成功: 54

**Comment by songjiang951130** [comment]
然后后台自动运行又能起来，在收取能量的时候又提示“未收取能量，可能有森林赠礼”

**Comment by TonyJiangWJ** [comment]
请重置默认配置再试试

**Comment by songjiang951130** [comment]
> 请重置默认配置再试试

重新导入个新包就好了。请问支持给朋友浇水不？
