### ISSUE TITLE
导入模块SQLiteUtil失败

### ISSUE THREAD

**Issue by wdl5i** [TonyJiangWJ/Ant-Forest#177]
从v1.3.6.3升级到V1.3.6.8.3的过程中出现“导入模块：[SQLiteUtil]失败，请检查代码”的错误提示，希望大神能够解决该问题，多谢
安卓版本：10
autojs版本：4.1.1.Alpha2

**Comment by TonyJiangWJ** [comment]
尝试强制重启AutoJS再试试，另外旧版本AutoJS[4.1.1.Alpha2]已经不再维护了且存在大量已知问题，我也不会额外提供支持了，建议下载[修改版AutoJS](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk)

**Comment by wdl5i** [comment]
谢谢大神，我下载了AutoJs M版本，发现无法唤醒手机，各种办法都试过了，之前的版本可以，不知道什么情况，我再搞一搞

**Comment by TonyJiangWJ** [comment]
是定时任务没触发吧 左上角打开设置抽屉 开启 使用AlarmManager调度任务。同时开启自启动、关闭电量限制
