### ISSUE TITLE
蚂蚁深林 “没有更多了” 出现循环判断，感觉定位元素一直失效了 

### ISSUE THREAD

**Issue by ruixule** [TonyJiangWJ/Ant-Forest#178]
![image](https://user-images.githubusercontent.com/33270841/190903428-6134f489-606a-4a7d-9f6f-ec89fa5002d6.png)

**Comment by TonyJiangWJ** [comment]
麻烦自己看一下README中底部区域相关说明 自行修改相应配置，配置入口 `图像识别相关配置` 底部校验区域和底部判断的灰度颜色值
