### ISSUE TITLE
用autox.js app最新版会报导入timers错误，希望支持

### ISSUE THREAD

**Issue by songjiang951130** [TonyJiangWJ/Ant-Forest#179]
![4b700a17280aeea41528bd6135c7ba3](https://user-images.githubusercontent.com/20123559/191143563-ab84a794-9bcc-40fe-8fb4-1cb6d48af1a9.jpg)

**Comment by songjiang951130** [comment]
我把timers.js 复制到lib下了，又报没有getInstance 方法，我还去autox看了一下，发现是kotlin代码，看不懂了
![微信图片_20220920090707](https://user-images.githubusercontent.com/20123559/191145310-41671f2d-d496-46fd-98fd-11f13ed400c6.png)

**Comment by TonyJiangWJ** [comment]
他们修改了源代码我这边无法支持 另外就算支持了其他功能也还是有兼容性问题的。我也没那么多时间 只能说无能为力
