### ISSUE TITLE
好友有防护罩时候报错

### ISSUE THREAD

**Issue by iciness** [TonyJiangWJ/Ant-Forest#18]
![Screenshot_20200101_082955_com eg android AlipayGphone](https://user-images.githubusercontent.com/4505686/71636843-14327880-2c71-11ea-8744-99d82cbe1ff0.jpg)

![Screenshot_20200101_081251_org autojs autojs](https://user-images.githubusercontent.com/4505686/71636819-b0a84b00-2c70-11ea-9341-e4b604aedda2.jpg)
提示usingtime没有定义
现在利用白名单来规避，貌似就这个好友会

新年快乐

**Comment by TonyJiangWJ** [comment]
这个问题挺严重的，已修复
