### ISSUE TITLE
无障碍模式 总是自动退出 有什么好的结局办法吗

### ISSUE THREAD

**Issue by ruixule** [TonyJiangWJ/Ant-Forest#180]
华为手机

**Comment by TonyJiangWJ** [comment]
[ADB授权脚本自动开启无障碍权限](https://github.com/TonyJiangWJ/AutoScriptBase/blob/master/resources/doc/ADB%E6%8E%88%E6%9D%83%E8%84%9A%E6%9C%AC%E8%87%AA%E5%8A%A8%E5%BC%80%E5%90%AF%E6%97%A0%E9%9A%9C%E7%A2%8D%E6%9D%83%E9%99%90.md)

**Comment by ruixule** [comment]
> [ADB授权脚本自动开启无障碍权限](https://github.com/TonyJiangWJ/AutoScriptBase/blob/master/resources/doc/ADB%E6%8E%88%E6%9D%83%E8%84%9A%E6%9C%AC%E8%87%AA%E5%8A%A8%E5%BC%80%E5%90%AF%E6%97%A0%E9%9A%9C%E7%A2%8D%E6%9D%83%E9%99%90.md)

Autojs的包名怎么查看

**Comment by ruixule** [comment]
![image](https://user-images.githubusercontent.com/33270841/191773486-b7f2bd93-b172-4f57-8bc8-31afd93568c4.png)
查不到设备

**Comment by TonyJiangWJ** [comment]
通过脚本运行toastLog(context.getPackageName())可以获取包名，或者通过应用设置查看（不同系统不一样这里不做举例）

> > [ADB授权脚本自动开启无障碍权限](https://github.com/TonyJiangWJ/AutoScriptBase/blob/master/resources/doc/ADB%E6%8E%88%E6%9D%83%E8%84%9A%E6%9C%AC%E8%87%AA%E5%8A%A8%E5%BC%80%E5%90%AF%E6%97%A0%E9%9A%9C%E7%A2%8D%E6%9D%83%E9%99%90.md)
> 
> Autojs的包名怎么查看

找不到设备是你自己连接手机有问题 自己检查一下有没有打开USB调试模式 具体请百度 懒得教

**Comment by TonyJiangWJ** [comment]
我说的是ADB连接手机的问题需要你自己去百度找解决方案  我只是给你举了个例子 谢谢 不想浪费时间
