### ISSUE TITLE
倒计时收取没有效果

### ISSUE THREAD

**Issue by WuYanchunGitHub** [TonyJiangWJ/Ant-Forest#182]
关闭了循环和永不停止，也不自动激活倒计时模式，并且设置了main文件的定时也没有效果，不知道为啥

**Comment by ruixule** [comment]
哥们，你的最近还可以用吗？方便交流下么 QQ1414100586

**Comment by WuYanchunGitHub** [comment]
手动启动是可以正常收的，能量雨也都正常，我这只是定时和倒计时用不了，合种浇水也不行
