### ISSUE TITLE
进入森林主页后无法正常收取能量

### ISSUE THREAD

**Issue by only4xiao** [TonyJiangWJ/Ant-Forest#183]
版本为最新版1.3.6.8.10，aotujs.modify版本已更新至最新

在森林主页上显示一行绿色小字（查找是否有“打开”对话框），然后过几秒页面会下滑一下，再过几秒自动返回支付宝首页，随即又进入森林主页，如此循环

**Comment by TonyJiangWJ** [comment]
请提供日志 logs/log-verboses.log

**Comment by only4xiao** [comment]
重启了几次解决了
