### ISSUE TITLE
新版本森林临时设置

### ISSUE THREAD

**Issue by TonyJiangWJ** [TonyJiangWJ/Ant-Forest#184]
控件文本设置-个人首页 改为 最新动态
控件文本设置-加载好友动态 改为 (点击)?展开好友动态
收集设置- 开启永不停止 开启所有模式强制仅执行逛一逛
图像识别设置：自行配置逛一逛按钮区域，使用取色工具获取“收能量”的区域信息
查找图片设置：所有按钮重新配置一下最新的图片

unit/waterFriend.js中的 "点击展开好友动态" 替换为 "(点击)?展开好友动态"

其他更完善的修改请等待我这边森林界面更新后适配 目前阶段请手动执行

**Comment by ruixule** [comment]
> 控件文本设置-个人首页 改为 最新动态 收集设置- 开启永不停止 开启所有模式强制仅执行逛一逛 图像识别设置：自行配置逛一逛按钮区域，使用取色工具获取“收能量”的区域信息 查找图片设置：所有按钮重新配置一下最新的图片
> 
> 其他更完善的修改请等待我这边森林界面更新后适配 目前阶段请手动执行

可以出一个视频教程吗

**Comment by wdl5i** [comment]
期待更新，解决新版本支付宝的适配问题
