### ISSUE TITLE
[广告]抖音极速版脚本

### ISSUE THREAD

**Issue by TonyJiangWJ** [TonyJiangWJ/Ant-Forest#185]
最近开发了抖音极速版自动刷广告的脚本，目前收费三毛一天10天起售，试用可以发送设备ID到我的邮箱tonyjiangwj@gmail.com获取试用的秘钥，试用期以我回复时间视情况调整，时间早当天晚上12点失效，时间晚第二天晚上12点失效。请注意查收邮件。
使用说明如下：[使用说明](http://mtw.so/666Vc8)
下载地址：[https://github.com/TonyJiangWJ/DouyinLite/releases](https://github.com/TonyJiangWJ/DouyinLite/releases)
基本每两天能提现15块，收益很不错。
![image](https://user-images.githubusercontent.com/11325805/201509983-b8e9e4f1-323d-4f2b-be81-f49e9d93ded2.png)

**Comment by ruixule** [comment]
> 最近开发了抖音极速版自动刷广告的脚本，目前收费1元一天，请加群获取 使用说明如下：https://sourl.cn/R2Mq5U 下载地址：https://github.com/TonyJiangWJ/DouyinLite/releases 基本每两天能提现15块，收益很不错。 ![image](https://user-images.githubusercontent.com/11325805/201509983-b8e9e4f1-323d-4f2b-be81-f49e9d93ded2.png)

QQ 群是多少

**Comment by TonyJiangWJ** [comment]
[加群获取](https://jq.qq.com/?_wv=1027&k=uYq7S3hr)
