### ISSUE TITLE
收取了好友能量还是提示“未收取能量，可能有森林赠礼，延迟等待动画”

### ISSUE THREAD

**Issue by Sakakibara-Hu** [TonyJiangWJ/Ant-Forest#186]
最新版本，已按照临时处理办法修改配置，目前可以进入收集，但是收集一个好友能量之后就如题所示卡在那里了，看日志也正常打印了收取多少克能量的记录

**Comment by TonyJiangWJ** [comment]
别催了 大哥大姐们 支付宝不给我推送新的版本我无法提供任何帮助 请自行研究源码调整吧
