### ISSUE TITLE
你好该脚本可以在电脑模拟器上使用吗

### ISSUE THREAD

**Issue by loyaltou** [TonyJiangWJ/Ant-Forest#187]
没有安卓设备

**Comment by TonyJiangWJ** [comment]
不知道 自己试试

**Comment by choudewanmei** [comment]
> 不知道 自己试试

作者大大你好，森林更新了![Screenshot_2022-11-28-01-55-30-143_com.eg.android.AlipayGphone.jpg](https://user-images.githubusercontent.com/68597681/204151841-bdbb487a-4385-473a-8b4f-5823ed00ec41.jpg)
