### ISSUE TITLE
不断在支付宝主页和蚂蚁森林个人主页间循环跳转

### ISSUE THREAD

**Issue by luchangharry** [TonyJiangWJ/Ant-Forest#188]
不断在支付宝主页和蚂蚁森林个人主页间循环跳转，直到停止脚本运行，蚂蚁庄园也是一样
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/10098018/log-verboses.log)
日志文件见附件，麻烦大佬看一下

**Comment by TonyJiangWJ** [comment]
你就不能自己看一下这个吗 https://github.com/TonyJiangWJ/Ant-Forest/issues/184

**Comment by luchangharry** [comment]
> 你就不能自己看一下这个吗 #184

主要是新用户，昨天才刚装上体验，按#184操作了一下没整明白，那我再研究下吧
