### ISSUE TITLE
多账号设置时，其中两个账号显示名称一样，就会始终有个不工作

### ISSUE THREAD

**Issue by fgzong** [TonyJiangWJ/Ant-Forest#193]
如题，我有5个账号，其中大号（一图最上）与另一小号（一图最下）显示名称一样（实际不一样，但是中间都是******），这样的情况在多账号设置里面，只能添加其中一个号，另一个号无法添加进去，如二图所示。然后我为了解决这个问题，大号使用了USERID，这样带来的问题是，与其同显示名称的账号就完全不工作了，无法能量雨，无法执行浇水，望能否区分一下这个问题？

另外还有次，账号输错了无法修改，最后只好把整个包删了，推到重来
![1](https://user-images.githubusercontent.com/52276585/206217784-d0fbb576-770e-46d2-a300-26daaea3f773.jpg)
![2](https://user-images.githubusercontent.com/52276585/206217836-d3cccd8e-3fe6-49a8-a9a4-9e625d876f2c.jpg)

**Comment by TonyJiangWJ** [comment]
有邮箱吗 绑定个邮箱再用邮箱登录就能规避了

修改账号 你直接左滑就调出修改菜单了 这种操作就自己摸索了 我不可能每个地方都写操作说明

**Comment by fgzong** [comment]
> 有邮箱吗 绑定个邮箱再用邮箱登录就能规避了
> 
> 修改账号 你直接左滑就调出修改菜单了 这种操作就自己摸索了 我不可能每个地方都写操作说明

谢谢！第二个确实我没发现，感谢提醒，关于第一个还是不行，使用邮箱登陆后，还是显示的手机号，不过我自己暂时解决了，新办了个副卡，相当于换了手机号解决

**Comment by here101** [comment]
> > 有邮箱吗 绑定个邮箱再用邮箱登录就能规避了
> > 修改账号 你直接左滑就调出修改菜单了 这种操作就自己摸索了 我不可能每个地方都写操作说明
> 
> 谢谢！第二个确实我没发现，感谢提醒，关于第一个还是不行，使用邮箱登陆后，还是显示的手机号，不过我自己暂时解决了，新办了个副卡，相当于换了手机号解决

你好狠啊，为了个小号直接换个手机号…………
