### ISSUE TITLE
定时任务无法自动唤醒手机

### ISSUE THREAD

**Issue by fflzh** [TonyJiangWJ/Ant-Forest#194]
之前用的别的脚本，最近切换到该版本，用了两天，发现一个问题
有时候（大多数时候）定时任务无法唤醒手机，需要手动按一下手机电源键，然后脚本才自动输密码解锁执行收能量。
是我设置的不对吗？
AutoJs是推荐的AutoJS Modify，手机P30 Pro ，系统版本鸿蒙2.0.0.268

**Comment by TonyJiangWJ** [comment]
①软件界面左上角右滑打开抽屉页面，在最底下打开 使用AlarmManager调度任务

②系统设置中，电量优化改成无限制；应用启动管理，自启动改为手动管理，允许自启动；打开允许修改系统设置；打开前台服务。

鸿蒙系统
打开系统设置，电量优化改成无限制。应用启动管理，自启动改为手动管理，允许自启动

如果以上设置以后都不行 那可能就是系统限制太多没法调度了 请尝试其他版本autojs

**Comment by only4xiao** [comment]
需要在要执行的代码里增加device.wakeupifneeded()
