### ISSUE TITLE
升级到1.3.7.3后小号切换异常

### ISSUE THREAD

**Issue by dacs6** [TonyJiangWJ/Ant-Forest#195]
脚本无法正常切换到小号中，日志中显示：
查找目标id:.*king_kong_image对应的控件
等待控件[.*king_kong_image]失败，id:.*king_kong_image

手动切换到小号，使用多账号管理中-->当前主账号-->切换账号，仍旧无法切换，日志中出错地方同上。

**Comment by TonyJiangWJ** [comment]
- 修改 `lib/AlipayAccountManage.js` 第47-48行成如下内容，恢复旧版。
- ```javascript
  automator.clickCenter(target)
  // target.parent().parent().click()
  ```

- 如果可以的话提供一下布局信息，运行 `独立工具/布局分析悬浮窗.js` 然后打开账号切换界面，点击 悬浮窗触发菜单按钮`啾`，运行完毕后提供一下：`logs/uiobjects.json` 文件

**Comment by dacs6** [comment]
[uiobjects.zip](https://github.com/TonyJiangWJ/Ant-Forest/files/10277698/uiobjects.zip)

**Comment by dacs6** [comment]
修改lib/AlipayAccountManage.js后测试切换正常，谢谢！

**Comment by dacs6** [comment]
升级到1.3.7.3.1后问题解决，作者解决问题的速度实在感人
