### ISSUE TITLE
cannot find any matches /^打开$/

### ISSUE THREAD

**Issue by wdl5i** [TonyJiangWJ/Ant-Forest#198]
支付宝版本：10.3.36
手机型号： 荣耀30
操作系统版本: Andriod 10

**Comment by wdl5i** [comment]
auto.js Ant Forest, 本地版本从V1.3.7.2到最新的V1.3.7.4， 均出现该现象

**Comment by TonyJiangWJ** [comment]
日志不是给你提示了吗 你按提示操作啊 另外给日志麻烦给完整整个流程的。
重置默认配置，然后自己配置能量球所在区域。

**Comment by wdl5i** [comment]
> 日志不是给你提示了吗 你按提示操作啊 另外给日志麻烦给完整整个流程的。 重置默认配置，然后自己配置能量球所在区域。

谢谢，我现在就试试

**Comment by wdl5i** [comment]
已解决，主要是没有把"打开"和"找能量"关联在一起，作者的日志挺详细
