### ISSUE TITLE
停留在蚂蚁森林首页-不运行了

### ISSUE THREAD

**Issue by feng99** [TonyJiangWJ/Ant-Forest#2]
**停留在此页面不运行了**
![333](https://user-images.githubusercontent.com/13182572/70526786-53473f80-1b85-11ea-97be-25b89e7d7823.jpg)
**软件权限**
![222](https://user-images.githubusercontent.com/13182572/70526802-593d2080-1b85-11ea-817c-1fe6a9a0610a.jpg)
**运行日志**
![111](https://user-images.githubusercontent.com/13182572/70526805-5b9f7a80-1b85-11ea-8992-e92ef24b2f86.jpg)
手机:Vivox27
Android Q系统

**Comment by feng99** [comment]
你好~ 运行哪个脚本   可以进行 `布局范围分析`?

**Comment by TonyJiangWJ** [comment]
自带的工具，悬浮窗 建议网上查一下

**Comment by feng99** [comment]
在autojs软件的文件-->示例代码-->悬浮窗 目录里看到以下脚本
![111](https://user-images.githubusercontent.com/13182572/70533278-bb9d1d80-1b93-11ea-8a86-3833b06b9475.jpg)
但是依次运行后,发现  未看到页面布局.

**Comment by TonyJiangWJ** [comment]
[控件悬浮窗等教程](https://www.bilibili.com/read/cv1328014)
是软件提供的 不是脚本

**Comment by feng99** [comment]
换了一个安卓手机. 解决了.
