### ISSUE TITLE
【非必现】好友有其他人送的能量时，会循环进入该好友收取页面，无法跳过

### ISSUE THREAD

**Issue by YinHang119** [TonyJiangWJ/Ant-Forest#20]
![Screenshot_20200113-164325_Autojs](https://user-images.githubusercontent.com/39940790/72243130-0cd27e00-3626-11ea-9db2-5b5817ff2edf.jpg)
截取了log-verbose.log，在develop.log里面仅有一行，没有截取

**Comment by TonyJiangWJ** [comment]
昨天就已经修复了，更新即可

**Comment by YinHang119** [comment]
> 昨天就已经修复了，更新即可

好的，一会试试，多谢！
