### ISSUE TITLE
提示  自己识别逛一逛按钮失败，请主动配置区域或者图片信息，请教怎么处理

### ISSUE THREAD

**Issue by dengqinzhi** [TonyJiangWJ/Ant-Forest#200]
提示  自己识别逛一逛按钮失败，请主动配置区域或者图片信息，请教怎么处理

**Comment by TonyJiangWJ** [comment]
运行可视化配置，点击进入查找图片设置，根据界面内提示将所有按钮重新配置一下最新的图片。每个项目左滑即可调出修改菜单，具体的自己按界面提示操作

**Comment by dengqinzhi** [comment]
好的，谢谢，我先试试！


另建议增加一个自己的能量倒计时功能，倒计时一分钟或者二分钟的时候，自动跳到首页等待能量成熟然后收取，收取完毕后再进行收取其他家的能量，
总是自己的能量给错过了收取，得不偿失了！




24427467
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TonyJiangWJ/Ant-Forest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TonyJiangWJ/Ant-Forest] 提示  自己识别逛一逛按钮失败，请主动配置区域或者图片信息，请教怎么处理 (Issue #200)





 
运行可视化配置，点击进入查找图片设置，根据界面内提示将所有按钮重新配置一下最新的图片。每个项目左滑即可调出修改菜单，具体的自己按界面提示操作

**Comment by TonyJiangWJ** [comment]
您提的这个 目前并不会考虑增加此功能
