### ISSUE TITLE
开机自启动方案

### ISSUE THREAD

**Issue by linliyuan** [TonyJiangWJ/Ant-Forest#201]
大佬你好，我现在也在做一个简单的autojs脚本，但是打包成apk之后不知道怎么开机自启动，有什么方案吗？这个脚本只有main.js，没有ui

**Comment by TonyJiangWJ** [comment]
我不玩打包，所以并没有研究过这些。

**Comment by linliyuan** [comment]
好的好的，同样感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月1日(星期三) 下午5:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TonyJiangWJ/Ant-Forest] 开机自启动方案 (Issue #201)





 
我不玩打包，所以并没有研究过这些。
