### ISSUE TITLE
一加手机待机一晚上后获取键盘控件失败

### ISSUE THREAD

**Issue by wdl5i** [TonyJiangWJ/Ant-Forest#205]
手机型号：一加Ace2
操作系统版本：Andriod 10
Ant-Forest软件版本：V1.3.7.7
准备工作：已在config文件中配置系统为coloros， 即unlock_device_flag为coloros
现象： 设置几分钟后的定时任务，锁屏后能自动解锁，当定时任务间隔比较长时，比如过一晚上，第二天定时任务启动后，解锁不成功，报获取键盘控件失败的错误，具体错误以下：
07:00:04.358/D: ======解锁并校验截图权限:=l=ll07:00:04.359/D:需要重新锁定屏幕
07:00:05.371/V: 滑动解锁，设备分辨率: 1240,277
07:00:06.702/V: 使用coloros的PIN密码解锁
07:00:07.736/E: 解锁发生异常,三分钟后重新开始Error: 获取键盘控件失败07:00:07.740/E: fileName: line:0 typeof e:object
定位：Ant-Forest/lib/Unlock.js/unlock_coloros_sample文件变量let keyboardRoot = id('com.android.systemui:id/pinColorNumericKeyboard').findOne(_config.timeout_unlock)
这个变量获取不成功
希望得到大神帮助，我只能定位问题，但是没有能力解决问题，多谢

**Comment by TonyJiangWJ** [comment]
时间有点久了，不知道你解决了没有，没有的话运行一下：`unit/获取锁屏界面控件信息.js` 根据提示操作，然后提供一下相应的日志信息
