### ISSUE TITLE
能否提供一个安卓5（32位）可以用的autojs modify或困鱼？

### ISSUE THREAD

**Issue by gzcshy** [TonyJiangWJ/Ant-Forest#207]
能否提供一个安卓5（32位）可以用的autojs modify或困鱼？目前链接提供的apk在安卓5不能安装，提示64位程序，谢谢

**Comment by TonyJiangWJ** [comment]
。。。无障碍至少需要安卓7以上，本脚本也不会再支持8.0以下非64位操作系统。你找别的脚本玩吧
