### ISSUE TITLE
神奇海洋点击垃圾无反应

### ISSUE THREAD

**Issue by lchongxiu** [TonyJiangWJ/Ant-Forest#208]
华为meta pro 50神奇海洋点击垃圾无反应，测试了click、longclick、express等都无效

**Comment by TonyJiangWJ** [comment]
是的目前无解了，如果以后森林也加这个机制的话就彻底废了。目前海洋就手动收吧

**Comment by lchongxiu** [comment]
如果是这样，那以后万一蚂蚁森林也采用类似动作，只能手工收取，程序点击无效可就麻烦大了

**Comment by TonyJiangWJ** [comment]
是的，可以考虑转投玩LSPatch。

**Comment by lchongxiu** [comment]
啥时候你开发LSPatch版本的森林和庄园呀，我到时下载你新版本

**Comment by TonyJiangWJ** [comment]
我记得有现成的，你可以搜一下。我目前刚接触LSP，用来去微博和知乎广告感觉挺好用的。
真到那个地步我估计会想别的办法实现点击，只是目前不想折腾。

**Comment by iblogc** [comment]
@TonyJiangWJ 海洋目前不能自动收，那禁用掉脚本自动进海洋，我目前概率性的有时脚本会进海洋然后就停在那里了，配置里没找到可以关闭的地方。

**Comment by TonyJiangWJ** [comment]
有概率进入？可能把海洋的球当做可收取了，关闭YOLO识别，自己正确配置能量球所在范围即可。或者手动收集掉海洋里面的能量球

**Comment by GavinLee-gn** [comment]
这个我遇到过，后来把设置里3d模式关了就好了
神奇海洋-右上角三个点-设置-显示效果
![Screenshot_20240309_113325_com eg android AlipayGphone](https://github.com/TonyJiangWJ/Ant-Forest/assets/54353328/5b29f812-91fe-4c59-827d-ad41d789ae10)

**Comment by TonyJiangWJ** [comment]
关闭3D模式即可 已更新版本并在README和设置中补充 感谢@GavinLee-gn
