### ISSUE TITLE
进到好友列表报获取截图权限失败，按readme时间调到1000ms扔报错

### ISSUE THREAD

**Issue by luckykeith** [TonyJiangWJ/Ant-Forest#21]
![微信图片_20200113180253](https://zx-zgiot-002.oss-cn-qingdao.aliyuncs.com/image/2af6f47fee424e0cbec2a4cd99e3f43c.jpg)

**Comment by luckykeith** [comment]
[http://zx-zgiot-002.oss-cn-qingdao.aliyuncs.com/image/2af6f47fee424e0cbec2a4cd99e3f43c.jpg](url)

**Comment by luckykeith** [comment]
问题截图，可直接在浏览器中打开
https://zx-zgiot-002.oss-cn-qingdao.aliyuncs.com/image/2af6f47fee424e0cbec2a4cd99e3f43c.jpg

**Comment by TonyJiangWJ** [comment]
1000不够再往上加 自行调试

**Comment by luckykeith** [comment]
卸载重新安装了一下支付宝，现在没什么问题了
