### ISSUE TITLE
三星s20升级安装安卓13后自动解锁失败

### ISSUE THREAD

**Issue by wings28** [TonyJiangWJ/Ant-Forest#212]
自己测试了一下是因为无法自动点亮屏幕导致的解锁失败

**Comment by TonyJiangWJ** [comment]
不同机型的适配需要相应设备，我无能为力，你自己研究一下怎么让你手机点亮屏幕吧 然后用自定义扩展的方式实现解锁

**Comment by only4xiao** [comment]
这个我知道，在需要定时启动的js里首行加上device. Wakeupifneeded()
