### ISSUE TITLE
请问是把图案解锁的方式移除了么？

### ISSUE THREAD

**Issue by luchangharry** [TonyJiangWJ/Ant-Forest#215]
请问大佬，我发现荣耀magic 5 pro,这两天开始无法实现图案解锁方式的滑动解锁了，请问下现在是否是把图案解锁方式移除了啊？

**Comment by TonyJiangWJ** [comment]
只是重构了代码并增加魅族的解锁，并没有移除手势解锁，可以提供一下日志看看，或者进群讨论，在线调试一下

**Comment by luchangharry** [comment]
![log](https://github.com/TonyJiangWJ/Ant-Forest/assets/50188136/8249042d-d0ae-4c6f-8c35-69eaf3a96d1d)
大佬，日志如截图所示，我测试了一下如果把解锁方式改成数字密码解锁是可以正常解锁的，但是图案解锁的话，并不像之前有模拟滑动，就卡在解锁页面，然后黑屏，然后再亮屏，如此反复。
我使用了获取锁屏界面控件信息的脚本，获得的信息贴在txt中供您参考。顺便问下我刚翻了一下没有看到有提供群号，方便的话可以提供一下么？
[lock.txt](https://github.com/TonyJiangWJ/Ant-Forest/files/12387236/lock.txt)

**Comment by TonyJiangWJ** [comment]
可视化配置-关于 里面有 你自己点一下

**Comment by luchangharry** [comment]
所需log文件见附件：
[info.log](https://github.com/TonyJiangWJ/Ant-Forest/file
[lockScreen.zip](https://github.com/TonyJiangWJ/Ant-Forest/files/12387250/lockScreen.zip)
s/12387249/info.log)

**Comment by TonyJiangWJ** [comment]
新版本已修复
