### ISSUE TITLE
无法收取能量球，提示找到能量球［］

### ISSUE THREAD

**Issue by aojie654** [TonyJiangWJ/Ant-Forest#216]
RT, 这种是查找失败了所以不会收取吗？

2023-08-23 08:02:17.152 DEBUG [E:8 T:5177] - 找到的球:[]

**Comment by TonyJiangWJ** [comment]
#197

**Comment by aojie654** [comment]
> #197

的确是因为这个问题，非常感谢！ @TonyJiangWJ
