### ISSUE TITLE
查找浇水按钮的问题

### ISSUE THREAD

**Issue by luowl123** [TonyJiangWJ/Ant-Forest#218]
浇水相关的问题，第一浇水之后会点击到对方的树，然后弹出显示对方树的皮肤，我怀疑是对方的树加了皮肤或挂件刚好存在颜色和浇水按钮相似的，然后改成绝对坐标就不存在这个问题了，感觉可以在可视化那里加一个手动配置浇水按钮坐标的功能。

**Comment by TonyJiangWJ** [comment]
浇水按钮是找图方式，不会找错，除非你用的默认图片，启用的是SIFT特征匹配。自己去查找图片设置里面，自己重新设置一下浇水按钮的图片，
