### ISSUE TITLE
执行完小号能量雨后，点击首页开始，还是会执行小号能量雨

### ISSUE THREAD

**Issue by linfeizheng** [TonyJiangWJ/Ant-Forest#219]
我在执行unit/循环切换小号并执行能量雨后，点击首页的开始按钮，是想从此刻开始收好友能量，结果autojs又开始了一次循环切换小号并执行能量雨。
应该与机型、系统无关，所以暂时不发日志了，麻烦尝试复现一次看看，谢谢
需要更多信息请联系我，再次拜谢

**Comment by TonyJiangWJ** [comment]
麻烦自己看一眼日志，这明显是循环小号失败了，这玩意儿我天天用没你所谓的问题。
建议自己看一眼日志，别自以为是的认为日志无用。
一个个都无语的，不给日志拿什么给你分析。
