### ISSUE TITLE
脚本放置路径问题

### ISSUE THREAD

**Issue by arliong** [TonyJiangWJ/Ant-Forest#22]
1, 如果将整个目录存放于手机的 \脚本\ 下面, 则一切运行正常;
2, 如果希望将目录归档到子目录, 比如 \脚本\支付宝\ 目录下面, 则运行出错, 目前追踪到 /脚本/支付宝/Ant-Forest-master/lib/FileUtils.js, 能力有限继续不下去 , 可否麻烦作者检查一下,谢谢

**Comment by TonyJiangWJ** [comment]
我试了并没有问题，你也不给个日志，我咋看

**Comment by arliong** [comment]
1, 我重新试过, 从手机上auto.js app直接执行main.js, 无论这个程序是放在哪里,都没有问题.
2, 我从Tasker调用 main.js. 或者是从电脑的vs上运行main.js, 都报一样的错误;  
前提是, 我已经运行过config.js并且也有过将配置导出; 
auto.js 版本是4.1.1a

错误日志如下:

[Extension Host] 14:14:18.527/V: 开始运行[[remote]config.js]
console.ts:137 [Extension Host] 14:14:18.647/E: ReferenceError: "module" is not defined. ([remote]config.js#151)
ReferenceError: "module" is not defined.
    at [remote]config.js:151:0
console.ts:137 [Extension Host] 14:14:18.648/V: 
------------
[[remote]config.js]运行结束，用时0.121000秒
console.ts:137 [Extension Host] 14:14:35.843/V: 开始运行[[remote]main.js]
console.ts:137 [Extension Host] 14:14:35.853/E: Error: Can't resolve relative module ID "./config.js" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)
Error: Can't resolve relative module ID "./config.js" when require() is used outside of a module
    at Require (file:///android_asset/modules/jvm-npm.js:89:0)
    at [remote]main.js:7:0
console.ts:137 [Extension Host] 14:14:35.853/V: 
------------
[[remote]main.js]运行结束，用时0.010000秒

**Comment by TonyJiangWJ** [comment]
你这个明显是使用方式有问题。
拜托你看一下AutoJS插件的使用方式，这个是一整个项目，使用VSCODE插件时需要执行的是run project 而不是执行某个文件
