### ISSUE TITLE
希望增加一个小号收能量再逛一逛的脚本，谢谢！

### ISSUE THREAD

**Issue by Prophetia086** [TonyJiangWJ/Ant-Forest#220]
目前小号只能收自己的能量，我试着改了一下，没成功，只能做到收完自己能量后不切回主账号，然后再执行一个正常的计时停止。然后再补一个切回到主账号。
麻烦做一个循环小号手机能量并对小号执行逛一逛，逛完了不用浏览朋友倒计时，再切下一个或回主账号。

非常感谢🙏

**Comment by TonyJiangWJ** [comment]
没时间 且大小号同时可以收集会涉及统计数据紊乱，所以不考虑开发此功能
