### ISSUE TITLE
解锁不起作用，除info.log

### ISSUE THREAD

**Issue by iblogc** [TonyJiangWJ/Ant-Forest#221]
从锁屏界面到滑动解锁界面后就不动了
[info.log](https://github.com/TonyJiangWJ/Ant-Forest/files/12845097/info.log)

**Comment by TonyJiangWJ** [comment]
图形密码？改用pin密码试试吧  各家UI改了控件没时间去适配

**Comment by iblogc** [comment]
是图形密码，那我改成pin试试
