### ISSUE TITLE
逛一逛结束后经常不执行能量雨收集，无规律

### ISSUE THREAD

**Issue by zycboss** [TonyJiangWJ/Ant-Forest#227]
设置里开启了逛一逛结束后执行能量雨，但是有时执行，有时不执行，逛一逛收完能量脚本就退出了

大概发生概率50%左右吧，再次手动重复运行脚本概率也一样，不知道哪一次会执行能量雨收集，没有找到规律，也没找到相关设置

用这个脚本好几年了，中间还换过两次手机，一直都有这个问题

设置里说“不建议在逛一逛中触发能量雨”，具体原因是什么呢？是否可以有办法解决？

**Comment by TonyJiangWJ** [comment]
为啥 就是因为控件经常变化找不到入口导致失败啊
通过独立脚本执行能量雨，自己选：
- `unit/自动启动并执行能量雨.js`
- `unit/循环切换小号并执行能量雨收集.js`
