### ISSUE TITLE
华为mate30无法自动解锁

### ISSUE THREAD

**Issue by chemboy0609** [TonyJiangWJ/Ant-Forest#23]
![Screenshot_20200116_153810_org autojs autojs](https://user-images.githubusercontent.com/24561009/72504528-f07a4f80-3878-11ea-8b33-2926fee3d345.jpg)
只有这个截图，log没有找到更多具体的信息，如果哪个地方有具体的log，烦请告诉我，谢谢！不知道在哪里可以有相关学习的资料也行！

**Comment by TonyJiangWJ** [comment]
解锁需要自行写，获取锁屏界面的布局然后编写解锁的代码，具体扩展方式在README有写。
获取锁屏界面布局的方式 SuperMonster003的项目里面有，你可以自行尝试：[SuperMonster003#ISSUE135](https://github.com/SuperMonster003/Auto.js_Projects/issues/135)
