### ISSUE TITLE
华为P30通过adb不能设置无障碍权限

### ISSUE THREAD

**Issue by congscallion** [TonyJiangWJ/Ant-Forest#24]
## 华为p30通过adb设置无障碍服务无效.

```shell
[slydm@wangcong Ant-Forest]$ adb shell pm grant org.autojs.autojs android.permission.WRITE_SECURE_SETTINGS
```
上述命令执行后没明错误.
打开auto.js, 执行脚本依然提示需要开启无障碍服务. 查看权限状态,该权限确实没有打开.
有了解的朋友吗?
求指教.

**Comment by TonyJiangWJ** [comment]
确认一下是否是免费版的AutoJS，Pro版包名并不同Pro版的是`org.autojs.autojspro`
