### ISSUE TITLE
有线程执行失败

### ISSUE THREAD

**Issue by Ehustein** [TonyJiangWJ/Ant-Forest#25]
最新版本，前几天一切正常，今天早上7点仅偷取了一点点的能量便开始`“有线程执行失败”`，分析可帮助可收取点的耗时明显超时并且没有正确分析出来导致收取失败，观察记录`“将线程池关闭然后重建线程池”`后依然失败，手动重新运行`main.js`脚本却可以正常运行，直至下午1点又出现问题，以下是部分log。
> 2020-01-19 13:07:54.637:[ERROR]有线程执行失败 运行中的线程数：1
> 2020-01-19 13:07:54.640:[DEBUG]将线程池关闭然后重建线程池
> 2020-01-19 13:07:54.641:[DEBUG]分析所有可帮助和可收取的点耗时5449ms
> 2020-01-19 13:07:54.642:[DEBUG]无可收取或帮助的内容
> 2020-01-19 13:07:56.743:[DEBUG]获取到screen成功
> 2020-01-19 13:07:56.761:[DEBUG]准备检测颜色：#f99236
> 2020-01-19 13:07:56.796:[DEBUG]可帮助的点：[]
> 2020-01-19 13:07:56.800:[DEBUG]准备检测颜色：#1da06a
> 2020-01-19 13:07:56.830:[DEBUG]可收取的点：[{"x":1014.0,"y":1759.0}]
> 2020-01-19 13:07:56.832:[DEBUG]重新分析后的点：[{"x":1014.0,"y":1759.0}]
> 2020-01-19 13:07:56.835:[DEBUG]获取可帮助和可能可收取的点耗时76ms
> 2020-01-19 13:07:58.520:[DEBUG]准备获取[{"x":1014.0,"y":1759.0}]的同色[#000087]点区域
> 2020-01-19 13:08:02.139:[ERROR]有线程执行失败 运行中的线程数：1
> 2020-01-19 13:08:02.142:[DEBUG]将线程池关闭然后重建线程池
> 2020-01-19 13:08:02.143:[DEBUG]分析所有可帮助和可收取的点耗时5306ms
> 2020-01-19 13:08:02.144:[DEBUG]无可收取或帮助的内容

**Comment by TonyJiangWJ** [comment]
调整线程池配置，具体见README

**Comment by Ehustein** [comment]
这可能是手机用久了会卡，也可能是autojs的bug，或者其他问题，我现在每两天重启手机没有再出现这个问题
另外，当playstore自动更新安卓系统webview之后也会出现`JavaException:Java.lang.InterruptedException:null`的问题和`校验排行榜失败`的问题手动重启手机也可以解决问题
