### ISSUE TITLE
判断帮助收取能量球失败，陷入无限循环

### ISSUE THREAD

**Issue by Ehustein** [TonyJiangWJ/Ant-Forest#26]
仔细观察可能是对方使用了汤圆树，程序错误把汤圆树当成可帮助收取能量球了。（不太确定，遇到两次以上，上一次没仔细观察=，=）
事实上随着蚂蚁森林的日常改版，好像经常会遇到这类判断错误的“小”问题。
建议加入一个保护机制：
连续2次进入同一用户主页且没有收取/帮收取能量则跳过收取/帮收取该用户。

**Comment by Ehustein** [comment]
确认无误，的确是汤圆树的问题。
保护机制还是很有必要加的，或者可以加一个判断六个能量球是否重新进入再次收取的选项。

**Comment by bearcai** [comment]
java.lang.illegalargumentexception:x + width must be <= bitmap.width(),  卡在自己的主页。没有进入排行榜
