### ISSUE TITLE
在主页报错

### ISSUE THREAD

**Issue by bearcai** [TonyJiangWJ/Ant-Forest#27]
java.lang.illegalargumentexception:x + width must be <= bitmap.width(), 卡在自己的主页。没有进入排行榜

**Comment by TonyJiangWJ** [comment]
日志更详细一些，这样看不出来具体原因，运行config勾选开发模式，然后再截图一下具体日志。

**Comment by bearcai** [comment]
![v2-ae6372bbc19a512dfc15a2fd595577a6_720w](https://user-images.githubusercontent.com/52390054/77322212-53db9e80-6d4e-11ea-97f3-0d8c65c3878e.jpg)

**Comment by TonyJiangWJ** [comment]
- 你开发模式没打开，只打开了debug日志，开关在进阶配置拉倒最底下。
- 另外排行榜判断区域配置不正确，具体操作如下：
- 排行榜判断失效请修改控件文本配置中的 `校验排行榜分析范围` 具体数据可以通过运行 `util/悬浮窗框位置.js` 来获取，运行后点击悬浮窗即可调整位置和大小。
  ![悬浮窗框位置示例](../raw/master/resources/floaty_using.jpg)

**Comment by bearcai** [comment]
谢谢Tony，排行榜已经进去了。
--出现了一个死循环，在帮某个好友收过一次能量后，一直重复退出和进入该好友。
陷入死循环的好友都是6个能量球没收的。
![v2-a850bab90addc3cedd0fb047eadf6c10_720w](https://user-images.githubusercontent.com/52390054/77553924-6261bb80-6ef0-11ea-85e9-ff913c4bac68.jpg)
![v2-3c255d85dfeb46037458336cbe23f4ab_720w](https://user-images.githubusercontent.com/52390054/77553938-65f54280-6ef0-11ea-8a93-da7632e53e49.jpg)
