### ISSUE TITLE
已开启滑动模拟，每次在好友周排行的地方停住不动

### ISSUE THREAD

**Issue by lNeverl** [TonyJiangWJ/Ant-Forest#28]
感谢您的脚本，每次使用的时候，在好友周排行的地方停住不动，过一会会退出到支付宝界面，日志在那里查看呢，已开启滑动模拟还是不行

**Comment by lNeverl** [comment]
找到错误日志了 ![](https://gitee.com/lNeverl/pic/raw/master/Screenshot_2020-04-06-16-38-23-409_org.autojs.aut.jpg)

**Comment by lNeverl** [comment]
![Screenshot_2020-04-06-16-38-23-409_org autojs aut](https://user-images.githubusercontent.com/60817289/78539631-73ca9200-7825-11ea-86c3-38d38125c559.jpg)

**Comment by lNeverl** [comment]
![Screenshot_2020-04-06-16-43-25-688_org autojs aut](https://user-images.githubusercontent.com/60817289/78539860-d2900b80-7825-11ea-9dfd-446aaffeb279.jpg)

**Comment by TonyJiangWJ** [comment]
日志提供log-verboses.log里面的。
另外开启图像分析试试吧

**Comment by lNeverl** [comment]
已经解决，我当前使用的为miui开发板 基于安卓10，且已经开启了miui自带的root权限。
当我使用脚本的时候，按理说安卓10不需要为脚本提供root权限 只需要打开无障碍就好了，但是当我使用的时候autojs还是申请了root权限，系统当时自动拒绝，所以脚本无法正常执行，之后我开启了root权限，脚本可以正常执行。

**Comment by TonyJiangWJ** [comment]
脚本的ROOT是基于权限相关文件是否存在来自动判断是否开启的，所以当你没有授权软件ROOT权限的时候脚本依旧能取到对应文件是否存在，所以默认就当有了ROOT权限，但是运行的时候却实际并没有授权，所以会出现这个问题。

**Comment by lNeverl** [comment]
好的 感谢指点
