### ISSUE TITLE
版本更新后main和config都不能正常运行

### ISSUE THREAD

**Issue by Yiyiyimu** [TonyJiangWJ/Ant-Forest#36]
运行config报错
`Auto.js Pro：错误： 函数importClass必须与一个类一起调用；改为使用“[JavaPackage com.stardust.autojs.ScriptEngineService]”.(<init>#14)`
运行main报错
`Auto.js Pro：导入模块[CommonFucntion]失败，请检查代码`

另外运行AutoScriptBase没有问题

AutoJS版本：8.0.0-5

**Comment by lwh201314** [comment]
一样的问题

**Comment by TonyJiangWJ** [comment]
新版本加入了一些机制 暂不支持Pro 请使用免费版

**Comment by PLQin** [comment]
如果不能在 pro 中使用 `importClass` 的话 , 有什么办法能替代这个么 ?
