### ISSUE TITLE
获取目前设置的定时开始的列表

### ISSUE THREAD

**Issue by Yiyiyimu** [TonyJiangWJ/Ant-Forest#37]
因为设置了很多定时开始的条目，经常一个还没有运行完另一个又开始了，有没有途径可以查看设置了哪些定时条目，然后可以把不需要的删除了

**Comment by TonyJiangWJ** [comment]
AutoJS软件不是提供了管理列表吗？

**Comment by Yiyiyimu** [comment]
> AutoJS软件不是提供了管理列表吗？

不好意思之前不知道，多谢多谢
