### ISSUE TITLE
添加华为/荣耀的解锁和锁屏功能

### ISSUE THREAD

**Issue by ZhongJinMing** [TonyJiangWJ/Ant-Forest#39]
1. 解锁，华为/荣耀的PIN输入控件是“com.android.systemui:id/fixedPinEntry”，加一个if else 判断一下即可；
2. 锁屏这块，因为我的手机没有root权限，所以采用点击的方式实现的，具体操作：利用华为/荣耀自带的一键锁屏快捷方式（桌面位置长按可添加），然后获取到这个快捷方式的横纵坐标即可，主要是主要前后要sleep()；
3. 我的手机型号是荣耀20.

**Comment by TonyJiangWJ** [comment]
自定义解锁请按README中描述自行扩展，不会被更新覆盖。

**Comment by mauyuk** [comment]
我的华为mate 30 pro也是没搞定自动解锁，获取页面布局不会有震动提示。
另一个问题就是mate 30 pro只有一个电源键，没有音量加减键，运行的时候无法停止

**Comment by ZhongJinMing** [comment]
> 我的华为mate 30 pro也是没搞定自动解锁，获取页面布局不会有震动提示。
> 另一个问题就是mate 30 pro只有一个电源键，没有音量加减键，运行的时候无法停止

我搞定了啊兄弟，仔细看我描述的方法，只是控件名比MIUI的多了一点

**Comment by mauyuk** [comment]
> > 我的华为mate 30 pro也是没搞定自动解锁，获取页面布局不会有震动提示。
> > 另一个问题就是mate 30 pro只有一个电源键，没有音量加减键，运行的时候无法停止
> 
> 我搞定了啊兄弟，仔细看我描述的方法，只是控件名比MIUI的多了一点

小白不会弄，能否把方法贴上来？
