### ISSUE TITLE
更新后收朋友出现问题

### ISSUE THREAD

**Issue by vinsonzb** [TonyJiangWJ/Ant-Forest#40]
![image](https://user-images.githubusercontent.com/64940573/82820216-5d12f400-9ed4-11ea-913d-2839be1b170e.png)
前天支付宝更新后出现问题，进入朋友列表后卡住不动，然后提示获取截图失败多次，重新执行脚本。多试几次偶尔会成功开始下滑，滑几下又卡住。
版本1.3.0
华为mate20pro emui10.1 支付宝10.1.95

**Comment by TonyJiangWJ** [comment]
请尝试增加截图等待时间，目前我没有遇到过这个问题。
不过似乎有出现这个问题的都是华为机型，暂时无法提供帮助。

**Comment by williamglasgow** [comment]
大佬，今天上午9点突然发出现收不了朋友的能量了，找了半天找到原因，蚂蚁森林又更新了，朋友首页“你收取TA”标签没了。这zfb天天更天天更真的恼火
