### ISSUE TITLE
zfb又更新了

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Ant-Forest#41]
大佬，今天上午9点突然发出现收不了朋友的能量了，找了半天找到原因，蚂蚁森林又更新了，朋友首页“你收取TA”标签没了。这zfb天天更天天更真的恼火。我暂时把朋友首页判断改成了“浇水”哈哈，等你的更新。

**Comment by TonyJiangWJ** [comment]
暂时注释掉 `core/BaseScanner.js` 466和480行的代码，修改首页判断的文本为 "浇水|TA的好友.*|今天"

**Comment by ZhongJinMing** [comment]
> 暂时注释掉 `core/BaseScanner.js` 466和480行的代码，修改首页判断的文本为 "浇水|TA的好友.*|今天"

466和480那个getFriendEnergy方法里的“你收取TA”的字符串我改成了变量，直接获取config的配置项

**Comment by TonyJiangWJ** [comment]
已更新，请尝试新版本脚本是否正常

**Comment by williamglasgow** [comment]
已测试，我这里完全没问题，辛苦了，再次感谢！

**Comment by Ehustein** [comment]
刚才发现，“你收取TA”标签又回来了
