### ISSUE TITLE
建议搞一个配置共享，让网友把不同型号手机的配置提交上来

### ISSUE THREAD

**Issue by wayss000** [TonyJiangWJ/Ant-Forest#42]
如题，建议创建一个目录，这个目录允许网友上传他们的配置，对于其他人懒得配置的人来说，直接导入相同型号手机的配置即可。

**Comment by TonyJiangWJ** [comment]
你所说的目录顶多只能搞个分支 提供上传。但是一般懒人根本不会用Github 所以这个需求感觉没啥必要

**Comment by wayss000** [comment]
主要是我觉得配置起来比较麻烦，如果可以直接导入相同型号的配置就完美了

**Comment by Ehustein** [comment]
我也觉得这个需求没啥必要，很多相同手机不同的设置也会有不同的结果，比如底部是横条还是按钮，系统字体大小，ui缩放等等，而且仅仅是定位坐标略有麻烦，如果你会ps或者其它设计软件可以直接导入截图进去拉一下辅助线就能精确定位（我就是这么干的）这部分的问题相信也是暂时的，相信作者应该会不断完善做到精简配置的
