### ISSUE TITLE
展示今日收集能量信息.js待完善

### ISSUE THREAD

**Issue by Ehustein** [TonyJiangWJ/Ant-Forest#45]
看了下`unit`下的脚本，发现`展示今日收集能量信息.js`这个模块不错
但是似乎还在施工中且一直没有更新维护

提一点小的建议：
1.生成的内容希望可以保存到log或者其它文件，目前好像只能看到，关闭就没有了（重要）
2.继续完善本周收集能量信息甚至更长时间的信息（我好像记得之前的版本是有统计本周收取和帮收的但是最新版没了，只有当日）
3.生成的格式不知可否格式化为json、xml、csv之类的格式方便导入电脑excel分析统计存档留念

收集能量的统计信息相信在手机端看了也是白看，此模块最大的作用在于通过统计帮助清理能量经常排在末位的好友，所以能在每周末定时运行保存出来导入excel进行自定义的排序还是非常重要的

**Comment by TonyJiangWJ** [comment]
已更新

**Comment by Ehustein** [comment]
相当完美，感谢大佬百忙之中抽空完善这个坑

**Comment by Ehustein** [comment]
刚才详细分析数据发现统计信息里面缺失了一些好友，应该就是那些一周之内所有数据都是0的好友，不知能否再完善下？

**Comment by TonyJiangWJ** [comment]
只保存已收集的数据，运行中没有收集过的自然就没有了 保存下来也没有意义，还得一个一个进入首页才能保存相应数据
