### ISSUE TITLE
错误位置：当前所在位置为好友首页

### ISSUE THREAD

**Issue by Ehustein** [TonyJiangWJ/Ant-Forest#46]
最近蚂蚁森林在首页发了一篇推送，名为《这是你种的蚂蚁森林》
导致一定几率会匹配`.*的蚂蚁森林`而被误认为这是好友首页不是个人首页
（我也不知道为什么是一定几率而不是每次）
报错`错误位置：当前所在位置为好友排行榜`
另外识别好友首页的依据我好像记得是在config.js里面设置的好友首页的控件文本，
但是修改并没有效果

大概率7.3蚂蚁森林会更新一篇推送，所以这个问题其实emmm...

**Comment by TonyJiangWJ** [comment]
个人首页判断是否在好友页面机制是写死的，所以没法通过config修改，这个问题可以暂时注释掉 `lib/prototype/WidgetUtils.js` 第298行 开始的代码
```javascript
  /*
  if (widgetCheck('.*的蚂蚁森林', 500)) {
    errorInfo('错误位置：当前所在位置为好友首页')
    return false
  }
  */
```
最近一直很忙，没什么时间修改脚本

**Comment by Ehustein** [comment]
好的，顺便透露一下7.3的推送应该是关于新树的信息
大致信息：
树名：山杏
所需能量：3万还差点
能否何种：不能
消息来源：官方微博、官方抖音的留言区
所以建议最近屯一些能量

**Comment by TonyJiangWJ** [comment]
已更新
