### ISSUE TITLE
进入支付宝后，反复跳转蚂蚁森林

### ISSUE THREAD

**Issue by tulipearl** [TonyJiangWJ/Ant-Forest#47]
正常进支付宝和蚂蚁森林，但是之后会提示上次收取有漏收，再次收集，之后退出蚂蚁森林，重新进入，反复循环，无法正常收取能量，在华为P40P、P30P，魅族Pro7上都是这样，不知道有没有解决办法

**Comment by TonyJiangWJ** [comment]
看一下日志吧，你这个估计配置没做好，详细阅读一下README

**Comment by dalaobanhuanghe** [comment]
三星s10，默认设置，开始脚本后发现自己的能量树有能量但是时间没到，然后就会提示漏收，始终反复。目测是对能量颜色的分析有问题。取消根据图像分析后自动循环的问题解决了，但是会进入合种树的界面且无法退出，现在勾选“是否直接基于图像分析收取和帮助好友”和“自动判断基于图像还是控件分析”之后，测试时没有问题了。

**Comment by dalaobanhuanghe** [comment]
实测可以识别朋友的代收能量，但是进入后无法代收。

**Comment by TonyJiangWJ** [comment]
看你描述就是配置没做好，自己看一下README 相关说明都有写了
懒得操作就等后续的开发的免配置版本吧
