### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by g662993** [TonyJiangWJ/Ant-Forest#49]
![Screenshot_20200721-165915_Autojs](https://user-images.githubusercontent.com/56568162/88035331-91bdc780-cb74-11ea-9b8f-4bceb2c10273.jpg)

**Comment by TonyJiangWJ** [comment]
下载整个仓库，将zip压缩包解压到 脚本 目录下 [下载地址](https://github.com/TonyJiangWJ/Ant-Forest/archive/v1.3.1.0.zip)
