### ISSUE TITLE
森林脚本执行正常，但执行后需要约8秒才可以自动退出

### ISSUE THREAD

**Issue by youm1ng** [TonyJiangWJ/Ant-Forest#50]
执行后停留在好友列表底部约8（如下）。
![微信图片_20200722103309](https://user-images.githubusercontent.com/68574463/88127846-3be62f80-cc07-11ea-8231-e3f79e1a643e.jpg)

**Comment by TonyJiangWJ** [comment]
看一下README [配置部分](https://github.com/TonyJiangWJ/Ant-Forest#%E9%85%8D%E7%BD%AE) `底部区域` 相关的内容
