### ISSUE TITLE
“获取截图失败多次, 可能已经没有了截图权限，重新执行脚本”

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Ant-Forest#51]
大概不到一周前突然出现的新问题，从森林首页到好友列表，下滑到第二十个，之后的不刷新，然后就失败，出现上面的提示（及时手动下滑可以刷出来并继续），偶尔更严重的时候到了好友列表完全不动就出现一样的错误提示。
强制关闭、重启手机等方法都试了，发现重装zfb能解决问题，但一段时间内（短则几小时，长则一两天）又会出现，不过我还没尝试过重装autojs。
实在没办法了来咨询一下，大佬有空帮忙看一下是什么问题

log如下：
> log-verboses logs for [2020-07-28 21:32:46]
> 2020-07-28 21:32:46.326 DEBUG [E:7 T:1720] - 获取截图失败 再试一次 count:1
> 2020-07-28 21:32:46.845 DEBUG [E:7 T:1720] - 获取截图失败 再试一次 count:2
> 2020-07-28 21:32:47.357 DEBUG [E:7 T:1720] - 获取截图失败 再试一次 count:3
> 2020-07-28 21:32:47.362 ERROR [E:7 T:1720] - 获取截图失败多次[3], 可能已经没有了截图权限，重新执行脚本
> 2020-07-28 21:32:47.373 LOG [E:7 T:1720] - 启动目标脚本：/storage/emulated/0/脚本/Ant-Forest-master/main.js
> 2020-07-28 21:32:47.426 INFO [E:7 T:1720] - 脚本执行结束, 移除通话状态监听
> 2020-07-28 21:32:47.429 DEBUG [E:7 T:1720] - 当前启用状态：true
> 2020-07-28 21:32:47.430 DEBUG [E:7 T:1720] - 移除phoneStateBroadcastReceiver
> 2020-07-28 21:32:47.460 INFO [E:7 T:1720] - 脚本执行结束, 释放图片资源
> 2020-07-28 21:32:47.463 DEBUG [E:7 T:1720] - 释放图片，总数：18
> 2020-07-28 21:32:47.477 DEBUG [E:7 T:1720] - 同步释放所有图片，耗时13
> 2020-07-28 21:32:47.485 DEBUG [E:7 T:1720] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":7,"timeout":1595944056085} 超时剩余时间：889秒
> 2020-07-28 21:32:47.487 DEBUG [E:7 T:1720] - 准备移除运行中任务
> 2020-07-28 21:32:47.514 DEBUG [E:7 T:1720] - 队列小于等于1 不需要去重:[]
> 2020-07-28 21:32:47.524 DEBUG [E:7 T:1720] - 无任务等待中
> 2020-07-28 21:32:47.766 DEBUG [E:8 T:1770] - 异常终止的重启任务已存在: [{"mAction":"org.autojs.autojs.action.startup","mLocal":true,"mScriptPath":"/storage/emulated/0/脚本/Ant-Forest-master/lib/prototype/CrashCatcher.js","mId":2}]
> 2020-07-28 21:32:47.865 DEBUG [E:8 T:1770] - 添加运行状态监听器，结束时释放通话状态监听
> 2020-07-28 21:32:47.948 DEBUG [E:8 T:1770] - 当前启用状态：true
> 2020-07-28 21:32:47.951 LOG [E:8 T:1770] - ======加入任务队列，并关闭重复运行的脚本=======
> 2020-07-28 21:32:47.960 DEBUG [E:8 T:1770] - 队列小于等于1 不需要去重:[]
> 2020-07-28 21:32:47.980 DEBUG [E:8 T:1770] - 当前无任务等待，直接执行：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":8}
> 2020-07-28 21:32:47.992 DEBUG [E:8 T:1770] - 设置脚本状态为执行中
> 2020-07-28 21:32:48.3 DEBUG [E:8 T:1770] - 当前脚本信息 id:8 source:/storage/emulated/0/脚本/Ant-Forest-master/main.js 运行中脚本数量：1
> 2020-07-28 21:32:48.5 LOG [E:8 T:1770] - ======校验无障碍功能======
> 2020-07-28 21:32:48.14 DEBUG [E:8 T:1770] - 当前已启用无障碍功能的服务:org.autojs.autojs/com.stardust.autojs.core.accessibility.AccessibilityService
> 2020-07-28 21:32:48.15 LOG [E:8 T:1770] - ---前置校验完成;启动系统--->>>>
> 2020-07-28 21:32:48.17 LOG [E:8 T:1770] - 版本信息：v1.3.0.6.10.1 nodeId:bba683552c4179ad039364b6b9a2f003d3fd3c9f
> 2020-07-28 21:32:48.19 LOG [E:8 T:1770] - AutoJS version: 4.1.1 Alpha2
> 2020-07-28 21:32:48.21 LOG [E:8 T:1770] - device info: Xiaomi raphael 10
> 2020-07-28 21:32:48.22 LOG [E:8 T:1770] - 运行模式：多脚本调度运行 永不停止，重新激活时间：60 基于图像分析 
> 2020-07-28 21:32:48.24 LOG [E:8 T:1770] - 设备分辨率：[1080, 2340]
> 2020-07-28 21:32:48.25 LOG [E:8 T:1770] - ======解锁并校验截图权限======
> 2020-07-28 21:32:48.27 LOG [E:8 T:1770] - 已解锁
> 2020-07-28 21:32:48.29 LOG [E:8 T:1770] - 不需要重新锁定屏幕
> 2020-07-28 21:32:48.31 LOG [E:8 T:1770] - 解锁成功
> 2020-07-28 21:32:48.244 DEBUG [E:8 T:1774] - 开始申请截图权限
> 2020-07-28 21:32:48.250 DEBUG [E:8 T:1774] - 已存储截图权限申请标记
> 2020-07-28 21:32:48.254 DEBUG [E:8 T:1774] - 已开启弹窗监测线程
> 2020-07-28 21:32:48.459 DEBUG [E:8 T:1776] - 截图权限申请结果: true
> 2020-07-28 21:32:48.678 LOG [E:8 T:1770] - 请求截屏权限成功
> 2020-07-28 21:32:49.147 DEBUG [E:8 T:1770] - 获取到的倒计时时间：null
> 2020-07-28 21:32:49.148 DEBUG [E:8 T:1770] - 当前启用状态：true
> 2020-07-28 21:32:49.149 DEBUG [E:8 T:1770] - 当前启用状态：true
> 2020-07-28 21:32:49.150 DEBUG [E:8 T:1770] - 注册phoneStateBroadcastReceiver
> 2020-07-28 21:32:49.153 DEBUG [E:8 T:1770] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":8,"timeout":1595944067981} 超时剩余时间：899秒
> 2020-07-28 21:32:49.160 DEBUG [E:8 T:1770] - 当前有任务正在运行：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":8,"timeout":1595944067981}
> 2020-07-28 21:32:49.161 DEBUG [E:8 T:1770] - 运行中脚本任务和当前任务相同，继续判断同源脚本是否正在运行
> 2020-07-28 21:32:49.162 DEBUG [E:8 T:1770] - 运行状态校验成功，执行后续功能
> 2020-07-28 21:32:49.164 LOG [E:8 T:1770] - 已解锁
> 2020-07-28 21:32:49.166 LOG [E:8 T:1770] - 不需要重新锁定屏幕
> 2020-07-28 21:32:49.168 DEBUG [E:8 T:1770] - 不再展示延迟对话框，capture-screen-error
> 2020-07-28 21:32:49.169 INFO [E:8 T:1781] - 即将收取能量，运行中可按音量上键关闭
> 2020-07-28 21:32:49.171 LOG [E:8 T:1770] - 日期：2020-07-28，启动时能量:134651g, 截止当前已收集:1552g, 已运行[87]次, 上轮收集:0g
> 2020-07-28 21:32:49.175 INFO [E:8 T:1770] - ========第88次运行========
> 2020-07-28 21:32:49.178 DEBUG [E:8 T:1770] - 展示悬浮窗内容：第 88 次运行, 累计已收集:1552g
> 2020-07-28 21:32:49.200 DEBUG [E:8 T:1770] - 展示悬浮窗完毕
> 2020-07-28 21:32:49.202 DEBUG [E:8 T:1770] - 准备打开package: com.eg.android.AlipayGphone
> 2020-07-28 21:32:49.656 WARN [E:8 T:1780] - 关闭脚本
> 2020-07-28 21:32:49.658 DEBUG [E:8 T:1780] - 撤销自动任务：{"mDelay":0,"mInterval":0,"mLoopTimes":1,"mMillis":1595943145363,"mScheduled":true,"mScriptPath":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","mTimeFlag":0,"mId":1910}
> 2020-07-28 21:32:49.662 DEBUG [E:8 T:1780] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":8,"timeout":1595944067981} 超时剩余时间：898秒
> 2020-07-28 21:32:49.663 DEBUG [E:8 T:1780] - 准备移除运行中任务
> 2020-07-28 21:32:49.687 DEBUG [E:8 T:1780] - 队列小于等于1 不需要去重:[]
> 2020-07-28 21:32:49.696 DEBUG [E:8 T:1780] - 无任务等待中
> 2020-07-28 21:32:49.707 DEBUG [E:8 T:1780] - 设置脚本状态为执行完毕
> 2020-07-28 21:32:49.710 DEBUG [E:8 T:1780] - 释放图片，总数：0
> 2020-07-28 21:32:49.741 INFO [E:8 T:1770] - 脚本执行结束, 移除通话状态监听
> 2020-07-28 21:32:49.745 DEBUG [E:8 T:1770] - 当前启用状态：true
> 2020-07-28 21:32:49.746 DEBUG [E:8 T:1770] - 移除phoneStateBroadcastReceiver
> 2020-07-28 21:32:49.750 INFO [E:8 T:1770] - 脚本执行结束, 释放图片资源
> 2020-07-28 21:32:49.755 WARN [E:8 T:1770] - 无任务在运行中，不可移除

**Comment by TonyJiangWJ** [comment]
尝试修改一下 `获取截图等待时间` 默认是500毫秒，可能太短了同时手机可能有点卡就超时了。
另外需要你自己确认一下有没有使用其他脚本，相互之间如果都申请了截图权限就会导致这个问题。

**Comment by williamglasgow** [comment]
好的感谢！
其他脚本我倒是没用，但我发现好像每次微信视频或者语音后好像（都）会出现这个问题，会是因为这个吗

**Comment by TonyJiangWJ** [comment]
`微信视频或者语音` 没尝试过，很少使用。

**Comment by youm1ng** [comment]
同样的问题，改了等待时间也不行

**Comment by ForgetSky** [comment]
同样的问题

**Comment by williamglasgow** [comment]
> 尝试修改一下 `获取截图等待时间` 默认是500毫秒，可能太短了同时手机可能有点卡就超时了。
> 另外需要你自己确认一下有没有使用其他脚本，相互之间如果都申请了截图权限就会导致这个问题。

大佬感觉大概率不是手机卡的问题，依据有两点，一是我手机红米k20pro清内存、甚至重启以后运行依旧如此；现在算来一周前出的问题，刚出问题前几天我卸载zfb重装能好个一阵子，可从昨天开始我卸载zfb重装也没用了；然后我卸载autojs试了一下也没用。昨天今天我也没用过微信视频或者语音，所以应该也可以排除吧。
是不是zfb针对这种自动化挂件做了应对措施啊？

**Comment by williamglasgow** [comment]
给同样问题的朋友的建议，可以暂时缓解的设置：
`获取截图等待时间`:1000
`是否启用模拟滑动`:开启
`自动判断基于图像还是控件分析`:关闭
我这里（红米k20pro）这样设置暂时可以运行，但是不管是速度还是准确率跟以前都没法比了

**Comment by TonyJiangWJ** [comment]
请更新到1.3.1.3版本，然后勾选开发模式之后提供一下相应出错的日志（logs/log-verboses.log），如果分析出来只是获取截图的问题，那就无能为力了

**Comment by williamglasgow** [comment]
当设置为以前的配置：
`获取截图等待时间`:500
`是否启用模拟滑动`:关闭
完全无法正常运行
[3_log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5009534/3_log-verboses.log)

**Comment by TonyJiangWJ** [comment]
所以你出于什么目的关闭模拟滑动？控件都没了还想指望自带的scrollDown吗

**Comment by williamglasgow** [comment]
当配置设为：
获取截图等待时间:1000
是否启用模拟滑动:开启
基本可以正常运行

出现了个两个新问题：
1. 帮某朋友收取以后，无法再次进入其页面，提示截图获取失败
2. 无法判定到达底部，修改后的底部判定框应该放在哪里？

[4_log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5009603/4_log-verboses.log)

**Comment by williamglasgow** [comment]
> 所以你出于什么目的关闭模拟滑动？控件都没了还想指望自带的scrollDown吗

额，就当复现一下之前的情况吧111

**Comment by TonyJiangWJ** [comment]
截图时间的问题，你一千不够就再加好了呀，具体自己慢慢调试，AutoJS的 captureScreen获取不到最新的图片就会一直阻塞 你要是不愿意那自己修改 CommonFunction.js checkCaptureScreenPermission
`line: 107`
```javascript
this.checkCaptureScreenPermission = function () {
  return captureScreen()
}
```

第一次运行底部判断需要时间，你手动停止了~~
不想自动判断那就自己框，具体框的范围在README写了 自行查看

**Comment by williamglasgow** [comment]
哦哦这样啊，了解啦，感谢大佬

**Comment by williamglasgow** [comment]
更新了最新版本以后不太稳定，具体表现是倒计时结束时经常会程序启动失败，log如下：

> 2020-08-10 09:35:36.947 LOG [E:26 T:12517] - ========本轮结束========
> 2020-08-10 09:35:36.952 DEBUG [E:26 T:12517] - 获取到的倒计时时间：4
> 2020-08-10 09:35:36.959 DEBUG [E:26 T:12517] - 撤销自动任务：{"mDelay":0,"mInterval":0,"mLoopTimes":1,"mMillis":1597019340063,"mScheduled":true,"mScriptPath":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","mTimeFlag":0,"mId":676}
> 2020-08-10 09:35:36.964 INFO [E:26 T:12517] - 预订[3.83325]分钟后的任务，时间戳:1597023566959
> 2020-08-10 09:35:37.51 DEBUG [E:26 T:12517] - 定时任务预定成功: 677
> 2020-08-10 09:35:37.53 WARN [E:26 T:12517] - 无任务在运行中，不可移除
> 2020-08-10 09:35:37.59 DEBUG [E:26 T:12517] - 设置脚本状态为执行完毕
> 2020-08-10 09:35:37.64 DEBUG [E:26 T:12517] - 倒计时3.83325
> 2020-08-10 09:35:37.76 DEBUG [E:26 T:12517] - 距离下次运行还有[3.83]分
> 2020-08-10 09:36:07.302 DEBUG [E:26 T:12517] - 距离下次运行还有[3.33]分
> 2020-08-10 09:36:37.516 DEBUG [E:26 T:12517] - 距离下次运行还有[2.83]分
> 2020-08-10 09:37:07.745 DEBUG [E:26 T:12517] - 距离下次运行还有[2.32]分
> 2020-08-10 09:37:38.8 DEBUG [E:26 T:12517] - 距离下次运行还有[1.82]分
> 2020-08-10 09:38:08.77 DEBUG [E:26 T:12517] - 距离下次运行还有[1.32]分
> 2020-08-10 09:38:29.100 INFO [E:26 T:12875] - 即将收取能量，按音量下键延迟五分钟执行
> 2020-08-10 09:38:29.105 DEBUG [E:26 T:12875] - after setMaxListeners
> 2020-08-10 09:38:29.109 DEBUG [E:26 T:12875] - after observeKey
> 2020-08-10 09:38:29.112 DEBUG [E:26 T:12875] - after setOnceKeyDown
> 2020-08-10 09:39:27.600 DEBUG [E:27 T:12878] - 异常终止的重启任务已存在: [{"mAction":"org.autojs.autojs.action.startup","mLocal":true,"mScriptPath":"/storage/emulated/0/脚本/Ant-Forest-master/lib/prototype/CrashCatcher.js","mId":1}]
> 2020-08-10 09:39:27.721 LOG [E:27 T:12878] - ======尝试加入任务队列，并关闭重复运行的脚本=======
> 2020-08-10 09:39:27.739 DEBUG [E:27 T:12878] - 队列小于等于1 不需要去重:[]
> 2020-08-10 09:39:27.766 DEBUG [E:27 T:12878] - 当前无任务等待，直接执行：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":27}
> 2020-08-10 09:39:27.767 DEBUG [E:26 T:12517] - 通话状态监听功能当前启用状态：true
> 2020-08-10 09:39:27.776 DEBUG [E:27 T:12878] - 设置脚本状态为执行中
> 2020-08-10 09:39:27.778 DEBUG [E:26 T:12517] - 通话状态监听功能当前启用状态：true
> 2020-08-10 09:39:27.784 DEBUG [E:26 T:12517] - 注册phoneStateBroadcastReceiver
> 2020-08-10 09:39:27.790 DEBUG [E:27 T:12878] - 当前脚本信息 id:27 source:/storage/emulated/0/脚本/Ant-Forest-master/main.js 运行中脚本数量：2
> 2020-08-10 09:39:27.792 DEBUG [E:27 T:12878] - 对比脚本信息 id:26 source:/storage/emulated/0/脚本/Ant-Forest-master/main.js
> 2020-08-10 09:39:27.794 WARN [E:27 T:12878] - currentId：27 退出运行中的同源脚本id：26
> 2020-08-10 09:39:27.794 DEBUG [E:26 T:12517] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":27,"timeout":1597024467768} 超时剩余时间：900秒
> 2020-08-10 09:39:27.799 DEBUG [E:27 T:12878] - 对比脚本信息 id:27 source:/storage/emulated/0/脚本/Ant-Forest-master/main.js
> 2020-08-10 09:39:27.801 LOG [E:27 T:12878] - ======加入任务队列成功=======
> 2020-08-10 09:39:27.849 INFO [E:26 T:12517] - 脚本执行结束, 移除通话状态监听
> 2020-08-10 09:39:27.849 DEBUG [E:27 T:12878] - 添加运行状态监听器，结束时释放通话状态监听
> 2020-08-10 09:39:27.856 DEBUG [E:26 T:12517] - 通话状态监听功能当前启用状态：true
> 2020-08-10 09:39:27.859 DEBUG [E:26 T:12517] - 移除phoneStateBroadcastReceiver
> 2020-08-10 09:39:27.862 INFO [E:26 T:12517] - 脚本执行结束, 释放图片资源
> 2020-08-10 09:39:27.866 DEBUG [E:26 T:12517] - 获取运行中任务信息：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":27,"timeout":1597024467768} 超时剩余时间：900秒
> 2020-08-10 09:39:27.868 WARN [E:26 T:12517] - 运行中任务：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":27,"timeout":1597024467768}和当前任务：{"source":"/storage/emulated/0/脚本/Ant-Forest-master/main.js","engineId":26}不同，不可移除
> 2020-08-10 09:39:27.890 DEBUG [E:27 T:12878] - Is _origin_images null? false.
> 2020-08-10 09:39:28.48 INFO [E:27 T:12878] - 脚本执行结束, 移除通话状态监听
> 2020-08-10 09:39:28.55 DEBUG [E:27 T:12878] - 通话状态监听功能当前启用状态：true
> 2020-08-10 09:39:28.58 INFO [E:27 T:12878] - 脚本执行结束, 释放图片资源
> 2020-08-10 09:39:28.68 DEBUG [E:27 T:12878] - 释放图片，总数：0

**Comment by TonyJiangWJ** [comment]
没看出来是什么原因导致的，我自己也没遇到过这个问题。出现频率是多少？再更新一下看看吧

**Comment by williamglasgow** [comment]
好的，是更新上一个版本后出现的，前面几个版本的倒计时都很稳定。今天就出现了大概五六次，手动启动了五六次。
我更新以后用一段时间能再来反馈。

**Comment by williamglasgow** [comment]
好的，是更新上一个版本后出现的，前面几个版本的倒计时都很稳定。今天就出现了大概五六次，手动启动了五六次。
我更新以后用一段时间后我再来反馈。

**Comment by TonyJiangWJ** [comment]
你试试把main.js第43行 resolver()删掉看看 大概是这个问题，我自己一直用的修改版没有用免费版AJ 所以没发现这个问题

**Comment by TonyJiangWJ** [comment]
直接更新到 `v1.3.1.5.4` 即可
