### ISSUE TITLE
好友列表小手识别不到

### ISSUE THREAD

**Issue by mengy822** [TonyJiangWJ/Ant-Forest#53]
如题;
在运行test/MockDetect.js后发现所有小手都被识别为倒计时,帮收识别正常
请问:这个该怎么解决

**Comment by TonyJiangWJ** [comment]
设备分辨率是多少，另外提供一下截图

**Comment by TonyJiangWJ** [comment]
更新到1.3.1.4.1然后手动开启 基于像素点判断是否可收取就行了

**Comment by mengy822** [comment]
好的,谢谢大佬
