### ISSUE TITLE
红米7note，分辨率2340*1080，第一次使用都正常的，但是第二次开始出现问题

### ISSUE THREAD

**Issue by cukewu** [TonyJiangWJ/Ant-Forest#54]
红米7note，分辨率2340*1080，第一次使用都正常的，但是第二次开始出现问题。程序不停的在自己蚂蚁森林界面和好友排行榜切换，，不清楚哪里出了问题。屏幕上一直提示上次有能量未收，将继续收取之类的。日志已上传，大概31日12：48分左右开始执行的
[error.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5148356/error.log)
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5148357/log-verboses.log)

**Comment by cukewu** [comment]
2020-08-31 12:49:02.89 WARN [E:5 T:360] - 漏收原因：发生异常 [Error: out of region: region = [600,-50,-50,20], image.size = [1080,2340]]

**Comment by TonyJiangWJ** [comment]
运行config.js 手动修改一下 排行榜识别区域和底部识别区域，值随便写 不超过屏幕范围即可

**Comment by cukewu** [comment]
值随便填了没有效果，还是一样的问题。软件和js包都重新装了也同样。。真是神奇了，最开始的第一次是好的，后面都不行了
