### ISSUE TITLE
重写解锁代码需要加亮屏和上滑代码么？

### ISSUE THREAD

**Issue by nmcq** [TonyJiangWJ/Ant-Forest#57]
我把ExternalUnlockDevice-demo.js改名ExternalUnlockDevice.js以后，不会点亮屏幕了

**Comment by TonyJiangWJ** [comment]
。。。你看一下注释！demo里面直接把run_unlock覆盖成空函数了 你要是没有特殊的 就把这段删去就行了 仅仅修改适合你自己手机的unlock方法就行
```javascript
  /**
   * 一般情况下仅仅重写unlock即可，点亮、滑动、校验等等都在Unlock中实现了通用方式
   * 但是如果机型特殊，可以直接重写run_unlock()方法
   * 在run_unlock中编写自己的解锁方式
   */
  this.run_unlock = function () {
    // 在这个里面编写解锁逻辑
  }

```

**Comment by nmcq** [comment]
噢噢我试一下。

**Comment by nmcq** [comment]
> 。。。你看一下注释！demo里面直接把run_unlock覆盖成空函数了 你要是没有特殊的 就把这段删去就行了 仅仅修改适合你自己手机的unlock方法就行
> 
> ```js
>   /**
>    * 一般情况下仅仅重写unlock即可，点亮、滑动、校验等等都在Unlock中实现了通用方式
>    * 但是如果机型特殊，可以直接重写run_unlock()方法
>    * 在run_unlock中编写自己的解锁方式
>    */
>   this.run_unlock = function () {
>     // 在这个里面编写解锁逻辑
>   }
> ```

解锁可以解了，但是解锁后似乎不会马上运行。
