### ISSUE TITLE
开启基于图像分析后，在好友列表中只能偷取部分好友的能量，大部分的能量会被跳过

### ISSUE THREAD

**Issue by jiangzIT** [TonyJiangWJ/Ant-Forest#6]
小米8，开启基于图像分析后，在好友列表中只能偷取部分好友的能量，大部分的能量（会忽略好友列表中的能量球）会被跳过

**Comment by TonyJiangWJ** [comment]
运行 `config.js` 进到 `进阶配置` 修改 `小手指像素点个数` 默认2300你可以设大点 具体自己尝试

**Comment by jiangzIT** [comment]
厉害 ，可以了
