### ISSUE TITLE
2个建议和1个问题，仅供参考

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Ant-Forest#60]
1. 更新1.3.3.2，我用了3天，发现起床时段收的能量不如以前收取的方式多，以前早上基本在1.7-1.8，用逛一逛的三天在1.4-1.5。 如果这不是我这里的个别现象的话。建议把“逛一逛”收取能量的方式改为可选、开关选项放到config里，且可自定义配置运行。
2. 蚂蚁森林代人收取机制有更新，帮人收取后如果有新能量会在代收取能量原位置出现，所以代人收取原来的再次进入此人页面的操作可以替换为，在代收取能量球出双击（应该需要一点时间间隔）。
3. 逛一逛收取方式偶尔会出现明明有可收能量/可代收能量，却还提示没能量可收。

再次鸣谢作者！

**Comment by TonyJiangWJ** [comment]
- `1,3` 应该是同个问题，findCircles之后的能量球判定不是很准确导致的。
- `2` 已经做了处理
以上问题已经改了 但是一直在测试稳定性所以没发布更新，等差不多我在发布release
另外逛一逛觉得不行，就先回退旧版本吧
