### ISSUE TITLE
不能进入好友列表，js报错了

### ISSUE THREAD

**Issue by WangShaoYang** [TonyJiangWJ/Ant-Forest#61]
刚刚更新到最新版本，运行发现不能进入好友列表，提示说：找不到[好友首页]元素，我把config重置了一下，再次运行，就出现报错了。
![E67D1657651F34DE537BB0E00E02E8D9](https://user-images.githubusercontent.com/26501618/93694298-7ce1be00-fb3c-11ea-89b5-4f275ecf55b6.jpg)
看了下报错位置，是164行找不到元素，不知道为什么
![693BA4DB8BCEFC981EE49875EBE788EF](https://user-images.githubusercontent.com/26501618/93694315-c29e8680-fb3c-11ea-830b-e4aa5c75313c.jpg)
麻烦有空时候给看下，谢谢大佬！

**Comment by TonyJiangWJ** [comment]
运行config.js  控件文本配置  修改`好友首页` 移除 `|.*大树养成记录`
- `TA的好友|今天|浇水|.*大树养成记录` => `TA的好友|今天|浇水`

**Comment by WangShaoYang** [comment]
![75FB62978B9CB355536C58ADCA7F336D](https://user-images.githubusercontent.com/26501618/93736171-0fa05c80-fc12-11ea-9fe4-5abcd2539201.jpg)
修改后，还是不能进入好友列表。

**Comment by TonyJiangWJ** [comment]
关闭逛一逛试试吧

**Comment by WangShaoYang** [comment]
可以了，谢谢！
不知道其他用户有没有这个情况，如果需要协助调试bug，随时联系~
手机型号：荣耀v10
Autojs版本：4.1.1 Alpha2

**Comment by WangShaoYang** [comment]
又碰到一个问题。运行一段时间后（好友列表大概走到50多），Autojs就被杀掉了，后台没有了，可能是什么问题呢？
这个能通过参数调节解决吗？是不是线程太多？
![D165B44F9AAF3648443FE49FDEE1175D](https://user-images.githubusercontent.com/26501618/93846220-07115a00-fcd6-11ea-9561-477ce3da741d.jpg)

**Comment by WangShaoYang** [comment]
又碰到一个问题。运行一段时间后（好友列表大概走到50多），Autojs就被杀掉了，后台没有了，可能是什么问题呢？
这个能通过参数调节解决吗？是不是线程太多？
![D165B44F9AAF3648443FE49FDEE1175D](https://user-images.githubusercontent.com/26501618/93846150-db8e6f80-fcd5-11ea-929c-3f880e1642e2.jpg)

**Comment by WangShaoYang** [comment]
尝试给Autojs加上后台锁，运行一会儿后，又停了（这次，Autojs还在后台），看日志说，没有截图权限了

**Comment by TonyJiangWJ** [comment]
AutoJS本身不稳定，经常会自动崩溃。脚本已经做了相应处理，奔溃自启之后会自动重新执行脚本，但是需要提供自启动权限。
因此请给与AutoJS自启动权限，另外将电池优化等全改为 无限制。
无障碍的自动启用可以查看README通过ADB赋权，如何使用ADB请百度一下，截图中的无障碍权限问题只能重启手机或者强制重启AutoJS。另外免费版中有不少bug，你可以使用[我修改的版本](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.20200908.apk)
