### ISSUE TITLE
大佬，auto.js可以点亮屏幕，但是不能解锁

### ISSUE THREAD

**Issue by a-len-z** [TonyJiangWJ/Ant-Forest#62]
我的手机是魅族17pro，所有权限都开启了，密码也按说明添加到con里了，测试了好几次，到点，可以正常唤醒屏幕，但是不能解锁，求问这个怎么解决呢？
还有一个问题是，下载的您给的软件，但是偶尔会卡死，不能运行
![WeChat Image_20200921153654](https://user-images.githubusercontent.com/39212442/93742468-bee43000-fc20-11ea-8a41-61e5aaa0bf5d.jpg)

**Comment by TonyJiangWJ** [comment]
解锁报错 请提供解锁报错相关的日志，你截图这个没有展示出相关信息

**Comment by a-len-z** [comment]
> 解锁报错 请提供解锁报错相关的日志，你截图这个没有展示出相关信息

大佬，这个日志路径在哪呢？我第一次玩auto.js，不知道怎么找这个锁屏的日志

**Comment by TonyJiangWJ** [comment]
- AutoJS的日志就是你截图的这个，但是你没有长截图完整。报错区间应该在这个时间范围内 `15:25:51`->`15:27:00`。
- 额外日志是我脚本里面写的，找一下森林脚本目录下 `logs/log-verboses.log` 这个文件。测试前先清空一下logs文件夹，然后执行一遍解锁，完成后将这个文件内容提供一下或者长截图。
- 另外我晚上提交一个解锁辅助工具，到时候你再看看吧。

**Comment by a-len-z** [comment]
好了，大佬，你看下，我按你说的，弄了一遍，得到了这个 logs-verboses.log。希望对您解决这个问题有帮助
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5259917/log-verboses.log)
![WeChat Image_20200922161147](https://user-images.githubusercontent.com/39212442/93858391-af331d00-fcee-11ea-9a50-6ad5727be931.jpg)

**Comment by a-len-z** [comment]
logs文件夹清空，再定时运行main（锁屏），进去检查logs，不知道为啥，里面没有任何文件。日志的话，完整的如下图。如果亮屏运行main的话，log-verboses.log这个文件夹是存在的，不知道这个是否有用呢？有用的话我把它也给大佬贴上来
![Uploading WeChat Image_20200922161147.jpg…]()

**Comment by a-len-z** [comment]
logs文件夹清空，再定时运行main（锁屏），进去检查logs，不知道为啥，里面没有任何文件。日志的话，完整的如下图。如果亮屏运行main的话，log-verboses.log这个文件夹是存在的，不知道这个是否有用呢？有用的话我把它也给大佬贴上来
![WeChat Image_20200922161147](https://user-images.githubusercontent.com/39212442/93859425-3208a780-fcf0-11ea-8db8-75ba17253eaa.jpg)

**Comment by TonyJiangWJ** [comment]
`16:09:02.224` 以后没日志了吗？截图截全呀，从开始到完全结束。

**Comment by a-len-z** [comment]
没了，真的没了，从开始到结束真的就这个长。。。
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5260081/log-verboses.log)
这个是日志。我测试了几次，如果亮屏运行main的话，会有log-verboses.log这个日志产生而且里面的内容会更新，锁屏的话，是没的。比如我亮屏16:08运行一次，就是上面这个文件内容，但是锁屏，如果清空logs文件夹运行，整个文件夹就不会更新。里面没内容。
我感觉，是不是锁屏，就没执行解锁这一步？因为我观察了一下，定时脚本只会把屏幕点亮，一个密码都不带输入的。我刚下了一个其他脚本，可能是屏幕分辨率的问题，密码没自动输入对，但是它执行了，输入了6位数。

**Comment by a-len-z** [comment]
看，前面是亮屏的，后面是息屏的日志，都在这个了。脚本点亮屏幕后会上划进入输入密码那一页，但是没有任何动作，然后屏幕就会自动熄灭了。
![WeChat Image_20200922164946](https://user-images.githubusercontent.com/39212442/93862174-3931b480-fcf4-11ea-9e9a-907643849c7a.jpg)

**Comment by TonyJiangWJ** [comment]
log-verboses.log是异步写入的，没有内容也是因为脚本没有完全结束。
另外你截图的那个也是，脚本根本没有运行结束。脚本结束了会有如下内容：
```
------------
    [/storage/emulated/0/脚本/Ant-forest-master/main.js]运行结束，用时xxxx秒
```
你这个截图里面根本没有，懂了吗？是否还在运行你点管理就能看到运行中脚本了。
实在不行你就自己看README中的说明，自行扩展解锁功能就行了。

**Comment by a-len-z** [comment]
谢谢大佬指点，我刚看了下，确实是脚本还在执行，没有结束。
![WeChat Image_20200922171014](https://user-images.githubusercontent.com/39212442/93863781-89aa1180-fcf6-11ea-9729-6135a119d976.jpg)
那现在是一直等它运行结束吗？还是怎样可以加快这个速度？然后把日志截给您？
readme那个，我当时添加脚本的时候就在github上看了，超出水平啦，就不弄了。
这个搞不定的话，就这样呗，也能用，无非是不能全自动了，哈哈

**Comment by TonyJiangWJ** [comment]
你修改一下 `lib/Unlock.js`中的代码试试吧，找到对应的直接替换就行
```javascript
  // 唤醒设备
  this.wakeup = function () {
    let limit = 3
    while (!device.isScreenOn() && limit-- > 0) {
      device.wakeUp()
      sleep(_config.timeout_unlock)
    }
    if (!device.isScreenOn()) {
      console.warn('isScreenOn判定失效，无法确认是否已亮屏。直接尝试后续解锁操作')
    }
  }

```

**Comment by a-len-z** [comment]
嗯嗯，谢谢谢谢，麻烦了😅
