### ISSUE TITLE
请问如何关闭倒计时收取

### ISSUE THREAD

**Issue by Jonah-77** [TonyJiangWJ/Ant-Forest#63]
大大你好，我只是想在每次想起收能量时减少劳动量让脚本自动收取，并不需要使用倒计时收取与循环收取，但是我找不到如何关闭倒计时收取。

    现在每次收完脚本还会在一定时间后自动开启，这让我有些苦恼，所以想请教一下关闭的方法。

**Comment by TonyJiangWJ** [comment]
运行`config.js` 设置一下 `计时最大等待时间` 和 `单次运行最大收集次数`
- `计时最大等待时间` ：倒计时等待的最大时间，默认是60分钟内有可收取的就会设置倒计时，你如果只需要收集一次，可以将它设置为1。
- `单次运行最大收集次数` ：一次执行所运行的最大次数，指的是脚本一次执行之后根据倒计时所循环的次数，也设为一即可。目前这一项不太可靠，因为脚本的倒计时有延迟可能会被定时启动所打断，导致运行次数就会被清零。

综上所述：两个值都设为1就能满足你只运行一次的需求

**Comment by Jonah-77** [comment]
好的，感谢您的帮助
