### ISSUE TITLE
关于几个BUG的反馈

### ISSUE THREAD

**Issue by z240347235** [TonyJiangWJ/Ant-Forest#65]
1:只有软件第一次打开时候提示的软件需要打开无障碍服务提示是正确的，当js异常后，第二次自动执行JS的时候就会出现失败。失败原因是一直跳转到打开无障碍服务页面，但是也没有提示任何语句。和第一次跳转到无障碍不同，第一次回提示开启adb什么什么权限。第二次就光跳转到那个页面然后继续执行任务。主要是任务也没有继续执行，并没有继续跳转到支付宝程序里面去，有悬浮，有提示，就是不去支付宝一直 停留在无障碍界面。
2:当支付宝需要收集的用户过多时，会收集几分钟后js直接退出。仅退出了main.js,并未退出auto.js程序，可能是因为某种异常。（我猜测是因为主线程还没执行完毕定时任务又开始了。只是我的猜测，可以忽略）
3:手机连接电脑后执行adb shell pm grant org.autojs.autojs android.permission.WRITE_SECURE_SETTINGS后并没有任何反应。(在adb中已经看到又客户端列表了，手机我确定已经连上电脑的adb再执行的命令。)

系统概述:
手机型号：华为 mate 30
系统版本号：10.1.0.159
安卓版本:10
支付宝版本:10.2.3
auto.js版本：Pro 8.2.1-0
[js执行完整日志图片：](http://wadch.dapi.vrtow.com/Screenshot_20200930_073832_com.tony.ant.forest.jpg)

- [ ] 日志图片http://wadch.dapi.vrtow.com/Screenshot_20200930_073832_com.tony.ant.forest.jpg

**Comment by TonyJiangWJ** [comment]
Pro的包名是 org.autojs.autojspro 修改后重新adb赋权吧
第二个问题日志没体现不知道原因

**Comment by TonyJiangWJ** [comment]
你这个脚本路径。。。是把脚本打包了？没针对打包的进行调试，不提供技术支持 自己摸索吧
