### ISSUE TITLE
获取锁屏界面控件信息失败

### ISSUE THREAD

**Issue by dakun123** [TonyJiangWJ/Ant-Forest#66]
![Screenshot_2020-10-02-10-59-43-211_org autojs autojs](https://user-images.githubusercontent.com/63987044/94884015-cf0cd280-049e-11eb-88c7-40abbe4654ec.jpg)

**Comment by TonyJiangWJ** [comment]
将以下下内容增加到lib/Unlock.js 的第十行
```javascript
let { logInfo, errorInfo, warnInfo, debugInfo } = singletonRequire('LogUtils')
```

**Comment by dakun123** [comment]
[info.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5316862/info.log)
麻烦大佬帮忙做一个解锁

**Comment by dakun123** [comment]
还有就是问一下大佬，那个自定义锁屏代码swipe后边括号里四个数代表什么，我需要改动一下，我也是MIUI12，但是下拉是左边，不是右边。

**Comment by TonyJiangWJ** [comment]
也是MIUI的话 解锁用默认的就行了 运行config.js输入一下锁屏密码即可
swipe(x1,y1,x2,y2,执行时间) 代表从点一到点二的滑动 你x1 x2都改成200即可

**Comment by dakun123** [comment]
把x1  x2都改成200还是下拉左边不是右边，改到1000也是，到底哪里出了问题，请教一下，谢谢

**Comment by dakun123** [comment]
可以了，新建文件后，改到1000可以实现

**Comment by dakun123** [comment]
新建文件后，把x1 x2改成1000可以做到锁屏。我明白了
