### ISSUE TITLE
只有一个能量且在中间收取不了

### ISSUE THREAD

**Issue by zhnlanf** [TonyJiangWJ/Ant-Forest#67]
日志显示等待控件【好友首页】失败，查找内容:TA的好友.*|今天

**Comment by TonyJiangWJ** [comment]
似乎是好友首页查询不到控件信息了。你可以进到好友首页然后通过悬浮球运行一下 `unit/获取当前页面的布局信息.js` 
然后提供一下对应的日志

**Comment by zhnlanf** [comment]
![Screenshot_20201009_112300_org autojs autojs](https://user-images.githubusercontent.com/58921007/95540499-7bacfe00-0a23-11eb-8ece-b1ad9b116948.jpg)

**Comment by TonyJiangWJ** [comment]
运行config.js 修改一下控件文本配置 `好友首页` 改成 `TA收取你|浇水`

**Comment by zhnlanf** [comment]
可以了，谢谢作者
