### ISSUE TITLE
不支持新版蚂蚁森林

### ISSUE THREAD

**Issue by liuyix** [TonyJiangWJ/Ant-Forest#68]
新版蚂蚁森林界面变化很大，发现脚本已经不可用了。
![Screenshot_2020-10-19-17-36-38-153_org autojs autojs](https://user-images.githubusercontent.com/680922/96427920-b9830100-1231-11eb-9ef6-647e6d38327b.png)

**Comment by TonyJiangWJ** [comment]
又有新版了? 截图一下森林首页看看
另外提供一下首页的布局信息，进入森林首页运行一下 `unit/获取当前页面的布局信息.js` 然后复制或者截图一下日志

**Comment by liuyix** [comment]
![1603103896843](https://user-images.githubusercontent.com/680922/96440269-4f228e80-123a-11eb-8edd-bac53e58962a.jpg)

**Comment by TonyJiangWJ** [comment]
变化确实挺大的，但是我这里还是老版本的，暂时无能为力了

**Comment by liuyix** [comment]
> 变化确实挺大的，但是我这里还是老版本的，暂时无能为力了

啊？难道我目前蚂蚁森林版本是灰度的吗...支付宝版本号是10.2.6

**Comment by TonyJiangWJ** [comment]
应该是的，我刚才更新到最新版的支付宝也还是老的

**Comment by here101** [comment]
我也更新到新版本了》。。。。也不能用。

**Comment by TonyJiangWJ** [comment]
> 我也更新到新版本了》。。。。也不能用。

提供一下首页的布局信息，进入森林首页运行一下 `unit/获取当前页面的布局信息.js` 然后复制或者截图一下日志

**Comment by williamglasgow** [comment]
- -[1:1]id:[android:id/statusBarBackground]bounds:[0, 0, 1080, 96]
- -[1:2]id:[android:id/navigationBarBackground]bounds:[0, 2296, 1080, 44]
- --[2:0]id:[android:id/content]bounds:[0, 0, 1080, 2296]
- ---[3:0]id:[com.alipay.mobile.nebulaintegration:id/nebulax_root_view]bounds:[0, 0, 1080, 2296]
- ----[4:0]id:[com.alipay.mobile.nebulaintegration:id/nebulax_wrapper_view]bounds:[0, 0, 1080, 2296]
- -----[5:0]id:[com.alipay.mobile.nebulaintegration:id/splash_container]bounds:[0, 0, 1080, 2296]
- -----[5:1]id:[com.alipay.mobile.nebulaintegration:id/fragment_container]bounds:[0, 0, 1080, 2296]
- -------[7:0]id:[com.alipay.mobile.nebula:id/h5_web_content]bounds:[0, 0, 1080, 2296]
- --------[8:0]id:[com.alipay.mobile.nebula:id/h5_pc_container]bounds:[0, 0, 1080, 2296]
- -----------[11:0][desc]content:[蚂蚁森林]bounds:[0, 0, 1080, 2296]
- ------------[12:0]id:[J_app_outter]bounds:[0, 0, 1080, 2296]
- -------------[13:0]id:[J_fullscreenFix]bounds:[0, 0, 1080, 49]
- --------------[14:0]id:[J_treeContainer]bounds:[0, 46, 1080, 1700]
- ---------------[15:0]id:[J_home_panel]bounds:[0, 46, 1080, 1593]
- -----------------[17:0][desc]content:[17°]bounds:[55, 253, 167, 132]
- -----------------[17:1][desc]content:[长沙]bounds:[236, 269, 85, 52]
- -----------------[17:2][desc]content:[晴]bounds:[236, 319, 39, 52]
- ------------------[18:0][desc]content:[我的大树养成记录]bounds:[693, 269, 118, 118]
- -------------------[19:0]id:[J_userEnergy][desc]content:[43502g]bounds:[819, 308, 121, 52]
- ------------------[18:2][desc]content:[种树]bounds:[948, 283, 132, 91]
- -----------------[17:1][desc]content:[奖]bounds:[478, 1487, 55, 47]
- ----------------[16:2]id:[J_tree_dialog_wrap]bounds:[539, 627, 541, 1012]
- --------------[14:0][desc]content:[  ]bounds:[33, 1663, 1014, 633]
- ---------------[15:0][desc]content:[最新动态]bounds:[63, 1716, 187, 46]
- ----------------[16:0][desc]content:[  ]bounds:[154, 1892, 46, 46]
- ----------------[16:0][desc]content:[你有新保护地线索]bounds:[222, 1820, 578, 63]
- ----------------[16:1][desc]content:[点击查看]bounds:[222, 1881, 578, 52]
- ---------------[15:2][desc]content:[查看]bounds:[833, 1837, 176, 79]
- --------------[14:3][desc]content:[  ]bounds:[33, 1960, 1014, 336]
- ---------------[15:0][desc]content:[1430g]bounds:[71, 2021, 118, 118]
- ----------------[16:0][desc]content:[今日共获得1430g]bounds:[222, 2021, 578, 63]
- -----------------[17:0][desc]content:[收取他人1343g]bounds:[222, 2084, 226, 52]
- -----------------[17:1][desc]content:[被人收取26g]bounds:[500, 2084, 195, 52]
- ---------------[15:2]id:[J_btnfanghua][desc]content:[放话]bounds:[833, 2040, 176, 80]
- -----------------[17:0][desc]content:[1111]bounds:[222, 2186, 165, 63]
- -----------------[17:1][desc]content:[共被你收取69g]bounds:[393, 2191, 272, 53]
- ----------------[16:1][desc]content:[今日最慷慨]bounds:[222, 2246, 603, 50]
- ----------------[16:0][desc]content:[10g]bounds:[866, 2216, 49, 50]
- ----------------[16:1][desc]content:[回赠]bounds:[929, 2222, 61, 38]
- -----------------[17:0][desc]content:[1111]bounds:[222, 2293, 399, 3]
- -----------------[17:1][desc]content:[共收取23g]bounds:[627, 2293, 192, 3]
- ----------------[16:1][desc]content:[今日最过分]bounds:[222, 2293, 597, 3]
- ----------------[16:1][desc]content:[踩TA]bounds:[924, 2293, 66, 3]
- -----------------[17:0][desc]content:[1111]bounds:[222, 2293, 86, 3]
- -----------------[17:1][desc]content:[收取1g]bounds:[313, 2293, 129, 3]
- ----------------[16:1][desc]content:[4小时前]bounds:[222, 2293, 597, 3]
- ----------------[16:1][desc]content:[踩TA]bounds:[924, 2293, 66, 3]
- -----------------[17:0][desc]content:[1111]bounds:[222, 2293, 124, 3]
- -----------------[17:1][desc]content:[收取2g]bounds:[354, 2293, 130, 3]
- ----------------[16:1][desc]content:[4小时前]bounds:[222, 2293, 597, 3]
- ----------------[16:1][desc]content:[踩TA]bounds:[924, 2293, 66, 3]
- --------------[14:9][desc]content:[查看更多动态 ]bounds:[33, 2293, 1014, 3]
- --------------[14:10][desc]content:[  ]bounds:[33, 2293, 1014, 3]
- ---------------[15:0][desc]content:[排行榜]bounds:[63, 2293, 954, 3]
- ---------------[15:0][desc]content:[周排行榜]bounds:[178, 2293, 218, 3]
- ---------------[15:1][desc]content:[总排行榜]bounds:[684, 2293, 218, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 30 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:2][desc]content:[3.8kg]bounds:[902, 2293, 101, 3]
- ----------------[16:4][desc]content:[  ]bounds:[115, 2293, 932, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 25 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:2][desc]content:[3.2kg]bounds:[902, 2293, 101, 3]
- ----------------[16:4][desc]content:[  ]bounds:[115, 2293, 932, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 20 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:2][desc]content:[3.0kg]bounds:[902, 2293, 101, 3]
- ----------------[16:4][desc]content:[  ]bounds:[115, 2293, 932, 3]
- ----------------[16:0][desc]content:[4]bounds:[38, 2293, 80, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 1 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:3][desc]content:[2.8kg]bounds:[902, 2293, 101, 3]
- ----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
- ----------------[16:0][desc]content:[5]bounds:[38, 2293, 80, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 1 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:3][desc]content:[2.8kg]bounds:[902, 2293, 101, 3]
- ----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
- ----------------[16:0][desc]content:[6]bounds:[38, 2293, 80, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 44 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:3][desc]content:[2.3kg]bounds:[902, 2293, 101, 3]
- ----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
- ----------------[16:0][desc]content:[7]bounds:[38, 2293, 80, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 20 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:3][desc]content:[2.3kg]bounds:[902, 2293, 101, 3]
- ----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
- ----------------[16:0][desc]content:[8]bounds:[38, 2293, 80, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 10 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:3][desc]content:[1.9kg]bounds:[902, 2293, 101, 3]
- ----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
- ----------------[16:0][desc]content:[9]bounds:[38, 2293, 80, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 42 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:3][desc]content:[1.2kg]bounds:[902, 2293, 101, 3]
- ----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
- ----------------[16:0][desc]content:[10]bounds:[38, 2293, 80, 3]
- -----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
- -----------------[17:1][desc]content:[获得了 10 个环保证书]bounds:[269, 2293, 613, 3]
- ----------------[16:3][desc]content:[1.1kg]bounds:[902, 2293, 101, 3]
- ---------------[15:1][desc]content:[找能量]bounds:[198, 2293, 123, 3]
- ---------------[15:2][desc]content:[直达有能量可收的好友森林]bounds:[346, 2293, 580, 3]
- ---------------[15:0][desc]content:[查看更多好友]bounds:[401, 2293, 278, 3]
- ---------------[15:0][desc]content:[加好友 收能量]bounds:[63, 2293, 954, 3]
- ----------------[16:1][desc]content:[1111]bounds:[33, 2293, 291, 3]
- ----------------[16:2][desc]content:[40.1kg 能量]bounds:[33, 2293, 291, 3]
- ----------------[16:3][desc]content:[加好友]bounds:[85, 2293, 187, 3]
- ----------------[16:1][desc]content:[1111]bounds:[343, 2293, 292, 3]
- ----------------[16:2][desc]content:[50.2kg 能量]bounds:[343, 2293, 292, 3]
- ----------------[16:3][desc]content:[加好友]bounds:[396, 2293, 187, 3]
- ----------------[16:1][desc]content:[可能认识的人]bounds:[654, 2293, 292, 3]
- ----------------[16:3][desc]content:[更多 >]bounds:[742, 2293, 116, 3]
- ----------------[16:0][desc]content:[邀请好友送能量保护罩]bounds:[264, 2293, 550, 3]
- ----------------[16:1][desc]content:[快来邀请好友一起种树]bounds:[264, 2293, 550, 3]
- ---------------[15:2][desc]content:[去邀请]bounds:[811, 2293, 192, 3]
- -------[7:1]id:[com.alipay.mobile.nebula:id/h5_title_bar]bounds:[0, 0, 1080, 229]
- --------[8:0]id:[com.alipay.mobile.nebula:id/h5_rl_title_bar]bounds:[0, 0, 1080, 229]
- ---------[9:0]id:[com.alipay.mobile.nebula:id/h5_status_bar_adjust_view]bounds:[0, 0, 1080, 96]
- ---------[9:1]id:[com.alipay.mobile.nebula:id/h5_title_bar_layout]bounds:[0, 96, 1080, 132]
- ----------[10:0]id:[com.alipay.mobile.nebula:id/h5_rl_title]bounds:[44, 96, 750, 132]
- ------------[12:0]id:[com.alipay.mobile.nebula:id/h5_ll_title_stub]bounds:[44, 96, 200, 132]
- -------------[13:0]id:[com.alipay.mobile.nebula:id/h5_ll_title]bounds:[44, 96, 200, 132]
- ---------------[15:0]id:[com.alipay.mobile.nebula:id/h5_tv_title][desc]content:[蚂蚁森林]bounds:[44, 125, 200, 74]
- ----------[10:1]id:[com.alipay.mobile.nebula:id/h5_nav_options]bounds:[794, 96, 275, 132]
- --------------[14:0][desc]content:[更多]bounds:[834, 121, 110, 82]
- ---------------[15:0][desc]content:[]bounds:[865, 130, 60, 63]
- --------------[14:2][desc]content:[关闭]bounds:[945, 121, 110, 82]
- ---------------[15:0][desc]content:[]bounds:[970, 130, 60, 63]
- ---------[9:2]id:[com.alipay.mobile.nebula:id/h5_h_divider_intitle]bounds:[0, 228, 1080, 1]
- ---------[9:3]id:[com.alipay.mobile.nebula:id/h5_custom_view]bounds:[0, 229, 1080, 0]
- ---------[9:4]id:[com.alipay.mobile.nebula:id/adView]bounds:[0, 229, 1080, 0]

**Comment by williamglasgow** [comment]
```
-[1:1]id:[android:id/statusBarBackground]bounds:[0, 0, 1080, 96]
-[1:2]id:[android:id/navigationBarBackground]bounds:[0, 2296, 1080, 44]
--[2:0]id:[android:id/content]bounds:[0, 0, 1080, 2296]
---[3:0]id:[com.alipay.mobile.nebulaintegration:id/nebulax_root_view]bounds:[0, 0, 1080, 2296]
----[4:0]id:[com.alipay.mobile.nebulaintegration:id/nebulax_wrapper_view]bounds:[0, 0, 1080, 2296]
-----[5:0]id:[com.alipay.mobile.nebulaintegration:id/splash_container]bounds:[0, 0, 1080, 2296]
-----[5:1]id:[com.alipay.mobile.nebulaintegration:id/fragment_container]bounds:[0, 0, 1080, 2296]
-------[7:0]id:[com.alipay.mobile.nebula:id/h5_web_content]bounds:[0, 0, 1080, 2296]
--------[8:0]id:[com.alipay.mobile.nebula:id/h5_pc_container]bounds:[0, 0, 1080, 2296]
-----------[11:0][desc]content:[蚂蚁森林]bounds:[0, 0, 1080, 2296]
------------[12:0]id:[J_app_outter]bounds:[0, 0, 1080, 2296]
-------------[13:0]id:[J_fullscreenFix]bounds:[0, 0, 1080, 49]
--------------[14:0]id:[J_treeContainer]bounds:[0, 46, 1080, 1700]
---------------[15:0]id:[J_home_panel]bounds:[0, 46, 1080, 1593]
-----------------[17:0][desc]content:[17°]bounds:[55, 253, 167, 132]
-----------------[17:1][desc]content:[长沙]bounds:[236, 269, 85, 52]
-----------------[17:2][desc]content:[晴]bounds:[236, 319, 39, 52]
------------------[18:0][desc]content:[我的大树养成记录]bounds:[693, 269, 118, 118]
-------------------[19:0]id:[J_userEnergy][desc]content:[43502g]bounds:[819, 308, 121, 52]
------------------[18:2][desc]content:[种树]bounds:[948, 283, 132, 91]
-----------------[17:1][desc]content:[奖]bounds:[478, 1487, 55, 47]
----------------[16:2]id:[J_tree_dialog_wrap]bounds:[539, 627, 541, 1012]
--------------[14:0][desc]content:[  ]bounds:[33, 1663, 1014, 633]
---------------[15:0][desc]content:[最新动态]bounds:[63, 1716, 187, 46]
----------------[16:0][desc]content:[  ]bounds:[154, 1892, 46, 46]
----------------[16:0][desc]content:[你有新保护地线索]bounds:[222, 1820, 578, 63]
----------------[16:1][desc]content:[点击查看]bounds:[222, 1881, 578, 52]
---------------[15:2][desc]content:[查看]bounds:[833, 1837, 176, 79]
--------------[14:3][desc]content:[  ]bounds:[33, 1960, 1014, 336]
---------------[15:0][desc]content:[1430g]bounds:[71, 2021, 118, 118]
----------------[16:0][desc]content:[今日共获得1430g]bounds:[222, 2021, 578, 63]
-----------------[17:0][desc]content:[收取他人1343g]bounds:[222, 2084, 226, 52]
-----------------[17:1][desc]content:[被人收取26g]bounds:[500, 2084, 195, 52]
---------------[15:2]id:[J_btnfanghua][desc]content:[放话]bounds:[833, 2040, 176, 80]
-----------------[17:0][desc]content:[1111]bounds:[222, 2186, 165, 63]
-----------------[17:1][desc]content:[共被你收取69g]bounds:[393, 2191, 272, 53]
----------------[16:1][desc]content:[今日最慷慨]bounds:[222, 2246, 603, 50]
----------------[16:0][desc]content:[10g]bounds:[866, 2216, 49, 50]
----------------[16:1][desc]content:[回赠]bounds:[929, 2222, 61, 38]
-----------------[17:0][desc]content:[1111]bounds:[222, 2293, 399, 3]
-----------------[17:1][desc]content:[共收取23g]bounds:[627, 2293, 192, 3]
----------------[16:1][desc]content:[今日最过分]bounds:[222, 2293, 597, 3]
----------------[16:1][desc]content:[踩TA]bounds:[924, 2293, 66, 3]
-----------------[17:0][desc]content:[1111]bounds:[222, 2293, 86, 3]
-----------------[17:1][desc]content:[收取1g]bounds:[313, 2293, 129, 3]
----------------[16:1][desc]content:[4小时前]bounds:[222, 2293, 597, 3]
----------------[16:1][desc]content:[踩TA]bounds:[924, 2293, 66, 3]
-----------------[17:0][desc]content:[1111]bounds:[222, 2293, 124, 3]
-----------------[17:1][desc]content:[收取2g]bounds:[354, 2293, 130, 3]
----------------[16:1][desc]content:[4小时前]bounds:[222, 2293, 597, 3]
----------------[16:1][desc]content:[踩TA]bounds:[924, 2293, 66, 3]
--------------[14:9][desc]content:[查看更多动态 ]bounds:[33, 2293, 1014, 3]
--------------[14:10][desc]content:[  ]bounds:[33, 2293, 1014, 3]
---------------[15:0][desc]content:[排行榜]bounds:[63, 2293, 954, 3]
---------------[15:0][desc]content:[周排行榜]bounds:[178, 2293, 218, 3]
---------------[15:1][desc]content:[总排行榜]bounds:[684, 2293, 218, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 30 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:2][desc]content:[3.8kg]bounds:[902, 2293, 101, 3]
----------------[16:4][desc]content:[  ]bounds:[115, 2293, 932, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 25 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:2][desc]content:[3.2kg]bounds:[902, 2293, 101, 3]
----------------[16:4][desc]content:[  ]bounds:[115, 2293, 932, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 20 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:2][desc]content:[3.0kg]bounds:[902, 2293, 101, 3]
----------------[16:4][desc]content:[  ]bounds:[115, 2293, 932, 3]
----------------[16:0][desc]content:[4]bounds:[38, 2293, 80, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 1 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:3][desc]content:[2.8kg]bounds:[902, 2293, 101, 3]
----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
----------------[16:0][desc]content:[5]bounds:[38, 2293, 80, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 1 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:3][desc]content:[2.8kg]bounds:[902, 2293, 101, 3]
----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
----------------[16:0][desc]content:[6]bounds:[38, 2293, 80, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 44 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:3][desc]content:[2.3kg]bounds:[902, 2293, 101, 3]
----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
----------------[16:0][desc]content:[7]bounds:[38, 2293, 80, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 20 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:3][desc]content:[2.3kg]bounds:[902, 2293, 101, 3]
----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
----------------[16:0][desc]content:[8]bounds:[38, 2293, 80, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 10 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:3][desc]content:[1.9kg]bounds:[902, 2293, 101, 3]
----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
----------------[16:0][desc]content:[9]bounds:[38, 2293, 80, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 42 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:3][desc]content:[1.2kg]bounds:[902, 2293, 101, 3]
----------------[16:5][desc]content:[  ]bounds:[115, 2293, 932, 3]
----------------[16:0][desc]content:[10]bounds:[38, 2293, 80, 3]
-----------------[17:0][desc]content:[1111]bounds:[269, 2293, 613, 3]
-----------------[17:1][desc]content:[获得了 10 个环保证书]bounds:[269, 2293, 613, 3]
----------------[16:3][desc]content:[1.1kg]bounds:[902, 2293, 101, 3]
---------------[15:1][desc]content:[找能量]bounds:[198, 2293, 123, 3]
---------------[15:2][desc]content:[直达有能量可收的好友森林]bounds:[346, 2293, 580, 3]
---------------[15:0][desc]content:[查看更多好友]bounds:[401, 2293, 278, 3]
---------------[15:0][desc]content:[加好友 收能量]bounds:[63, 2293, 954, 3]
----------------[16:1][desc]content:[1111]bounds:[33, 2293, 291, 3]
----------------[16:2][desc]content:[40.1kg 能量]bounds:[33, 2293, 291, 3]
----------------[16:3][desc]content:[加好友]bounds:[85, 2293, 187, 3]
----------------[16:1][desc]content:[1111]bounds:[343, 2293, 292, 3]
----------------[16:2][desc]content:[50.2kg 能量]bounds:[343, 2293, 292, 3]
----------------[16:3][desc]content:[加好友]bounds:[396, 2293, 187, 3]
----------------[16:1][desc]content:[可能认识的人]bounds:[654, 2293, 292, 3]
----------------[16:3][desc]content:[更多 >]bounds:[742, 2293, 116, 3]
----------------[16:0][desc]content:[邀请好友送能量保护罩]bounds:[264, 2293, 550, 3]
----------------[16:1][desc]content:[快来邀请好友一起种树]bounds:[264, 2293, 550, 3]
---------------[15:2][desc]content:[去邀请]bounds:[811, 2293, 192, 3]
-------[7:1]id:[com.alipay.mobile.nebula:id/h5_title_bar]bounds:[0, 0, 1080, 229]
--------[8:0]id:[com.alipay.mobile.nebula:id/h5_rl_title_bar]bounds:[0, 0, 1080, 229]
---------[9:0]id:[com.alipay.mobile.nebula:id/h5_status_bar_adjust_view]bounds:[0, 0, 1080, 96]
---------[9:1]id:[com.alipay.mobile.nebula:id/h5_title_bar_layout]bounds:[0, 96, 1080, 132]
----------[10:0]id:[com.alipay.mobile.nebula:id/h5_rl_title]bounds:[44, 96, 750, 132]
------------[12:0]id:[com.alipay.mobile.nebula:id/h5_ll_title_stub]bounds:[44, 96, 200, 132]
-------------[13:0]id:[com.alipay.mobile.nebula:id/h5_ll_title]bounds:[44, 96, 200, 132]
---------------[15:0]id:[com.alipay.mobile.nebula:id/h5_tv_title][desc]content:[蚂蚁森林]bounds:[44, 125, 200, 74]
----------[10:1]id:[com.alipay.mobile.nebula:id/h5_nav_options]bounds:[794, 96, 275, 132]
--------------[14:0][desc]content:[更多]bounds:[834, 121, 110, 82]
---------------[15:0][desc]content:[]bounds:[865, 130, 60, 63]
--------------[14:2][desc]content:[关闭]bounds:[945, 121, 110, 82]
---------------[15:0][desc]content:[]bounds:[970, 130, 60, 63]
---------[9:2]id:[com.alipay.mobile.nebula:id/h5_h_divider_intitle]bounds:[0, 228, 1080, 1]
---------[9:3]id:[com.alipay.mobile.nebula:id/h5_custom_view]bounds:[0, 229, 1080, 0]
---------[9:4]id:[com.alipay.mobile.nebula:id/adView]bounds:[0, 229, 1080, 0]
```

**Comment by williamglasgow** [comment]
我的森林首页分析，机型红米k20pro
我是今天下午才变成新版的
目前取消掉逛一逛开关后可以使用

**Comment by TonyJiangWJ** [comment]
可以尝试将 `core/StrollScanner.js` 第99行颜色值从 `#909090` 改成`#868686` 然后试试逛一逛还能不能用。
https://github.com/TonyJiangWJ/Ant-Forest/blob/65a926ddae4828e893fe5054db97a895edb79440/core/StrollScanner.js#L99

我的依旧是老版本没法针对新版进行更新

**Comment by liuyix** [comment]
> 我的森林首页分析，机型红米k20pro
> 我是今天下午才变成新版的
> 目前取消掉逛一逛开关后可以使用

米10Utlra 逛一逛关掉后也可以用了。

**Comment by liuyix** [comment]
> 可以尝试将 `core/StrollScanner.js` 第99行颜色值从 `#909090` 改成`#868686` 然后试试逛一逛还能不能用。
> https://github.com/TonyJiangWJ/Ant-Forest/blob/65a926ddae4828e893fe5054db97a895edb79440/core/StrollScanner.js#L99
> 
> 我的依旧是老版本没法针对新版进行更新

这个文描不需要改吗，我记得之前应该不叫”找能量“吧

**Comment by TonyJiangWJ** [comment]
> > 可以尝试将 `core/StrollScanner.js` 第99行颜色值从 `#909090` 改成`#868686` 然后试试逛一逛还能不能用。
> > https://github.com/TonyJiangWJ/Ant-Forest/blob/65a926ddae4828e893fe5054db97a895edb79440/core/StrollScanner.js#L99
> > 
> > 我的依旧是老版本没法针对新版进行更新
> 
> 这个文描不需要改吗，我记得之前应该不叫”找能量“吧

这个功能只检测颜色 没有检测文本的

**Comment by TonyJiangWJ** [comment]
已更新代码，请更新到 v1.3.3.1
