### ISSUE TITLE
新版本蚂蚁森林无法偷取能量

### ISSUE THREAD

**Issue by zgwing97** [TonyJiangWJ/Ant-Forest#69]
![1](https://user-images.githubusercontent.com/60022036/96835363-12db7200-1476-11eb-95a9-3e8269ef84a4.jpg)
![2](https://user-images.githubusercontent.com/60022036/96835369-14a53580-1476-11eb-95b6-e9c6e1d6598e.jpg)
![3](https://user-images.githubusercontent.com/60022036/96835371-153dcc00-1476-11eb-9940-fdef84b35a18.jpg)
![Screenshot_20201022_144123_org autojs autojs](https://user-images.githubusercontent.com/60022036/96835374-15d66280-1476-11eb-9d85-a801fd47e2db.jpg)
![Screenshot_20201022_144130_org autojs autojs](https://user-images.githubusercontent.com/60022036/96835376-15d66280-1476-11eb-8608-6de4601a2b9e.jpg)
![6](https://user-images.githubusercontent.com/60022036/96835381-166ef900-1476-11eb-802a-34288b447304.jpg)
![7](https://user-images.githubusercontent.com/60022036/96835384-17078f80-1476-11eb-953d-dcce50853d85.jpg)

一直用旧版本的图像分析的控件偷能量，后面更新版本后无法使用。

**更新后我发现config配置文件里面，**设置参数，既然没办法保存****
![10](https://user-images.githubusercontent.com/60022036/96842226-58506d00-147f-11eb-8f6a-d8224ebda692.png)

**Comment by zgwing97** [comment]
是设置了config里面的排行帮判断区域参数后，再次关闭软件，重新进入----点击实时查看可视化配置----变成初始化的排行帮参数
![10](https://user-images.githubusercontent.com/60022036/96842601-d1e85b00-147f-11eb-8805-d15ff4bb4f18.png)
![Uploading 10.png…]()

**Comment by TonyJiangWJ** [comment]
已更新代码，请更新到 v1.3.3.1
