### ISSUE TITLE
锁屏解锁密码去掉了不能直接打开手机吗

### ISSUE THREAD

**Issue by sandglasstu** [TonyJiangWJ/Ant-Forest#73]
大佬，我把log也传上来了，帮忙看下

info logs for [2020-10-25 16:58:10]
2020-10-25 16:58:27.888 总分析耗时：5928ms 总控件数：203

=================
锁屏界面:
分析耗时：157ms
控件总数：22
分析控件内容：
-[1:0]id:[com.android.systemui:id/notification_panel]bounds:[0, 0, 1080, 2340]
--[2:0]id:[com.android.systemui:id/ic_circle_shortcut_1][desc]content:[录音机]bounds:[96, 2370, 138, -30]
--[2:1]id:[com.android.systemui:id/ic_circle_shortcut_3][desc]content:[手电筒]bounds:[283, 2370, 138, -30]
--[2:2]id:[com.android.systemui:id/ic_circle_shortcut_2][desc]content:[计算器]bounds:[470, 2370, 138, -30]
--[2:3]id:[com.android.systemui:id/ic_circle_shortcut_4][desc]content:[计时器]bounds:[657, 2370, 138, -30]
--[2:4]id:[com.android.systemui:id/ic_circle_shortcut_5][desc]content:[扫一扫]bounds:[845, 2370, 138, -30]
--[2:5]id:[com.android.systemui:id/keyguard_clock_view]bounds:[72, 258, 936, 289]
---[3:0]id:[com.android.systemui:id/clock_parent]bounds:[349, 258, 382, 289]
----[4:0]id:[com.android.systemui:id/clock_text][desc]content:[4:58]bounds:[349, 258, 382, 289]
--[2:6]id:[com.android.systemui:id/chargingstatus][desc]content:[已充满]bounds:[459, 534, 162, 73]
--[2:7]id:[com.android.systemui:id/magazine_simple_title][desc]content:[中国人民保险]bounds:[72, 2250, 258, 57]
--[2:8]id:[com.android.systemui:id/lock_indication]bounds:[0, 174, 1080, 57]
---[3:0]id:[com.android.systemui:id/lock_icon][desc]content:[解锁]bounds:[426, 178, 48, 48]
---[3:1]id:[com.android.systemui:id/hw_keyguard_indication_text][desc]content:[上滑解锁]bounds:[486, 174, 168, 57]
--[2:9]id:[com.android.systemui:id/camera_imageview][desc]content:[相机]bounds:[936, 2241, 72, 72]
-[1:1]id:[com.android.systemui:id/backdrop_back]bounds:[0, 0, 1080, 2340]
-[1:2]id:[com.android.systemui:id/operator_name][desc]content:[没有 SIM 卡]bounds:[57, 14, 183, 47]
-[1:3]id:[com.android.systemui:id/no_sim_view][desc]content:[无 SIM 卡。]bounds:[240, 16, 36, 43]
-[1:4]id:[com.android.systemui:id/wifi_combo][desc]content:[WLAN 信号强度满格。]bounds:[276, 16, 44, 42]
-[1:5][desc]content:[振铃器静音。]bounds:[828, 6, 42, 62]
-[1:6]id:[com.android.systemui:id/battery_outside_percent][desc]content:[100%]bounds:[870, 14, 82, 46]
-[1:7]id:[com.android.systemui:id/battery_border][desc]content:[正在充电，已完成百分之100。]bounds:[952, 16, 71, 43]
=================
密码输入界面:
分析耗时：545ms
控件总数：181
分析控件内容：
-[1:0]id:[org.autojs.autojs:id/drawer_layout]bounds:[0, 0, 1080, 2214]
---[3:0][desc]content:[打开侧拉菜单]bounds:[0, 0, 168, 48]
---[3:1][desc]content:[Auto.js]bounds:[216, 0, 189, 4]
---[3:2]id:[org.autojs.autojs:id/action_log][desc]content:[日志]bounds:[744, 0, 168, 36]
---[3:3]id:[org.autojs.autojs:id/action_search][desc]content:[搜索]bounds:[912, 0, 168, 36]
---[3:4]id:[org.autojs.autojs:id/tab]bounds:[0, 48, 1080, 144]
----[4:0][desc]content:[文件]bounds:[0, 48, 216, 144]
-----[5:0][desc]content:[文件]bounds:[66, 91, 84, 57]
----[4:1][desc]content:[教程]bounds:[216, 48, 216, 144]
-----[5:0][desc]content:[教程]bounds:[282, 91, 84, 57]
----[4:2][desc]content:[社区]bounds:[432, 48, 216, 144]
-----[5:0][desc]content:[社区]bounds:[498, 91, 84, 57]
----[4:3][desc]content:[市场]bounds:[648, 48, 216, 144]
-----[5:0][desc]content:[市场]bounds:[714, 91, 84, 57]
----[4:4][desc]content:[管理]bounds:[864, 48, 216, 144]
-----[5:0][desc]content:[管理]bounds:[930, 91, 84, 57]
---[3:5]id:[org.autojs.autojs:id/viewpager]bounds:[0, 192, 1080, 2022]
----[4:0]id:[org.autojs.autojs:id/explorer_item_list]bounds:[0, 192, 1080, 2022]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 192, 1080, 24]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 192, 120, 0]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[功能测试-查看百度识图次数]bounds:[216, 192, 564, -60]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[439 B]bounds:[216, 192, 564, -4]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 192, 102, -9]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 192, 102, -9]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 192, 72, -9]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 218, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 242, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[功能测试-查看运行队列]bounds:[216, 245, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[129 B]bounds:[216, 314, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 251, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 251, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 251, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 388, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 412, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[功能测试-清空任务队列]bounds:[216, 415, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[163 B]bounds:[216, 484, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 421, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 421, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 421, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 558, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 582, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[功能测试-任务队列测试]bounds:[216, 585, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[454 B]bounds:[216, 654, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 591, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 591, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 591, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 728, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 752, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[功能测试-重置默认配置]bounds:[216, 755, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[1.9 KB]bounds:[216, 824, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 761, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 761, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 761, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 898, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 922, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[关闭所有脚本并锁屏-放在unit文件夹下]bounds:[216, 925, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[647 B]bounds:[216, 994, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 931, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 931, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 931, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 1068, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 1092, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[获取当前页面的布局信息]bounds:[216, 1095, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[6.7 KB]bounds:[216, 1164, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 1101, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 1101, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 1101, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 1238, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 1262, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[获取锁屏界面控件信息]bounds:[216, 1265, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[8.5 KB]bounds:[216, 1334, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 1271, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 1271, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 1271, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 1408, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 1432, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[浇水测试]bounds:[216, 1435, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[535 B]bounds:[216, 1504, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 1441, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 1441, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 1441, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 1578, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 1602, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[浇水三次]bounds:[216, 1605, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[594 B]bounds:[216, 1674, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 1611, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 1611, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 1611, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 1748, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 1772, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[能量收集统计]bounds:[216, 1775, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[5.4 KB]bounds:[216, 1844, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 1781, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 1781, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 1781, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 1918, 1080, 168]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 1942, 120, 120]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[清空百度OCR像素点个数和倒计时的缓存]bounds:[216, 1945, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[522 B]bounds:[216, 2014, 564, 44]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 1951, 102, 102]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 1951, 102, 102]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 1951, 72, 102]
------[6:0]id:[org.autojs.autojs:id/item]bounds:[0, 2088, 1080, 126]
-------[7:0]id:[org.autojs.autojs:id/first_char][desc]content:[J]bounds:[48, 2112, 120, 102]
-------[7:1]id:[org.autojs.autojs:id/name][desc]content:[统计能量增长信息]bounds:[216, 2115, 564, 57]
-------[7:2]id:[org.autojs.autojs:id/desc][desc]content:[690 B]bounds:[216, 2184, 564, 30]
-------[7:3]id:[org.autojs.autojs:id/run]bounds:[780, 2121, 102, 93]
-------[7:4]id:[org.autojs.autojs:id/edit]bounds:[882, 2121, 102, 93]
-------[7:5]id:[org.autojs.autojs:id/more]bounds:[984, 2121, 72, 93]
-----[5:0][desc]content:[Index | Auto.js 4.1.0 文档]bounds:[1080, 192, 1080, 2022]
------[6:0]id:[content]bounds:[1080, 192, 1080, 2022]
-------[7:0]id:[column1]bounds:[1080, 192, 1080, 2022]
---------[9:0][desc]content:[Auto.js 4.1.0 文档]bounds:[1098, 192, 1043, 154]
---------[9:1]id:[gtoc]bounds:[1098, 346, 1043, 46]
-----------[11:0][desc]content:[索引]bounds:[1095, 347, 75, 44]
-----------[11:1][desc]content:[ | ]bounds:[1167, 350, 22, 38]
-----------[11:2][desc]content:[查看全部]bounds:[1184, 347, 137, 44]
--------[8:1]id:[toc]bounds:[1098, 486, 1043, 0]
---------[9:0][desc]content:[目录]bounds:[1098, 463, 78, 46]
--------[8:2]id:[apicontent]bounds:[1098, 543, 1043, 1671]
-----------[11:0][desc]content:[• ]bounds:[1148, 588, 14, 48]
-----------[11:1][desc]content:[关于本文档]bounds:[1172, 585, 209, 54]
-----------[11:0][desc]content:[• ]bounds:[1148, 663, 14, 48]
-----------[11:1][desc]content:[W3CSchool - ECMAScript教程]bounds:[1172, 660, 532, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 738, 14, 48]
-----------[11:1][desc]content:[阮一峰 - ECMAScript 6教程]bounds:[1172, 735, 477, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 870, 14, 48]
-----------[11:1][desc]content:[Overview - 综述]bounds:[1172, 867, 287, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 945, 14, 48]
-----------[11:1][desc]content:[Q&A - 常见问题]bounds:[1172, 942, 282, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1021, 14, 48]
-----------[11:1][desc]content:[App - 应用]bounds:[1172, 1017, 191, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1096, 14, 48]
-----------[11:1][desc]content:[Console - 控制台]bounds:[1172, 1092, 298, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1171, 14, 48]
-----------[11:1][desc]content:[CoordinatesBasedAutomation - 基于坐标的操作]bounds:[1172, 1167, 828, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1246, 14, 48]
-----------[11:1][desc]content:[Device - 设备]bounds:[1172, 1243, 238, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1321, 14, 47]
-----------[11:1][desc]content:[Dialogs - 对话框]bounds:[1172, 1318, 287, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1396, 14, 47]
-----------[11:1][desc]content:[Engines - 脚本引擎]bounds:[1172, 1393, 331, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1472, 14, 47]
-----------[11:1][desc]content:[Events - 事件与监听]bounds:[1172, 1468, 352, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1547, 14, 47]
-----------[11:1][desc]content:[Floaty - 悬浮窗]bounds:[1172, 1543, 267, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1622, 14, 47]
-----------[11:1][desc]content:[Files - 文件系统]bounds:[1172, 1618, 277, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1697, 14, 47]
-----------[11:1][desc]content:[Globals - 一般全局函数]bounds:[1172, 1694, 403, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1765, 14, 48]
-----------[11:1][desc]content:[Http - HTTP]bounds:[1172, 1762, 222, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1838, 14, 47]
-----------[11:1][desc]content:[Images - 图片与图色处理]bounds:[1172, 1834, 434, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 1913, 14, 47]
-----------[11:1][desc]content:[Keys - 按键模拟]bounds:[1172, 1908, 280, 56]
-----------[11:0][desc]content:[• ]bounds:[1148, 1988, 14, 47]
-----------[11:1][desc]content:[Media - 多媒体]bounds:[1172, 1985, 267, 55]
-----------[11:0][desc]content:[• ]bounds:[1148, 2063, 14, 47]
-----------[11:1][desc]content:[Modules - 模块]bounds:[1172, 2059, 268, 56]
-----------[11:0][desc]content:[• ]bounds:[1148, 2138, 14, 47]
-----------[11:1][desc]content:[WidgetsBasedAutomation - 基于控件的操作]bounds:[1172, 2134, 760, 56]
-----------[11:0][desc]content:[• ]bounds:[1148, 2214, 14, 0]
-----------[11:1][desc]content:[Sensors - 传感器]bounds:[1172, 2209, 292, 5]
-----------[11:0][desc]content:[• ]bounds:[1148, 2289, 14, -75]
-----------[11:1][desc]content:[Shell - Shell命令]bounds:[1172, 2284, 286, -70]
-----------[11:0][desc]content:[• ]bounds:[1148, 2364, 14, -150]
-----------[11:1][desc]content:[Storages - 本地存储]bounds:[1172, 2359, 346, -145]
-----------[11:0][desc]content:[• ]bounds:[1148, 2439, 14, -225]
-----------[11:1][desc]content:[Threads - 多线程]bounds:[1172, 2435, 298, -221]
-----------[11:0][desc]content:[• ]bounds:[1148, 2514, 14, -300]
-----------[11:1][desc]content:[Timers - 定时器]bounds:[1172, 2510, 277, -296]
-----------[11:0][desc]content:[• ]bounds:[1148, 2588, 14, -374]
-----------[11:1][desc]content:[UI - 用户界面]bounds:[1172, 2585, 238, -371]
-----------[11:0][desc]content:[• ]bounds:[1148, 2664, 14, -450]
-----------[11:1][desc]content:[Work with Java - 调用Java API]bounds:[1172, 2660, 527, -446]
-----------[11:0][desc]content:[• ]bounds:[1148, 2797, 14, -583]
-----------[11:1][desc]content:[GitHub项目 & Issue提交]bounds:[1172, 2792, 424, -578]
-----------[11:0][desc]content:[• ]bounds:[1148, 2872, 14, -658]
-----------[11:1][desc]content:[Auto.js交流社区]bounds:[1172, 2867, 289, -653]
---[3:6]id:[org.autojs.autojs:id/fab]bounds:[864, 2214, 168, 0]

**Comment by TonyJiangWJ** [comment]
这个确实是没有考虑到不锁定手机，你可以自己自定义扩展一下解锁代码，将解锁操作改为空内容就行具体先自己调试一下，如何扩展见README
