### ISSUE TITLE
非常感谢，很有用！顺便提一点小建议

### ISSUE THREAD

**Issue by Prophetia086** [TonyJiangWJ/Ant-Forest#75]
这是目前我用过的几个收能量js中功能最完善，体验最好的版本。整体非常满意，基本满足了我所有的需求。

如果非要说有什么还可以优化的内容，就是有两个规则可以利用一下：
1、每天0:00，会有一批好友的能量变为可收取，但是在这之前不会有倒计时。也就是说可能23:59浏览好友列表，全都是空白，于是按照现在的无限执行逻辑，会在设定时间后再次检查（默认60分钟）；但是下一分钟其实就已经有好几个能量可以收取了。
2、除了真的在半夜晚上有线下支付等情况以外，几乎不会有能量在0:01-6:59这段时间成熟，而早上7:00和0:00一样，会有一批能量同时可以收取。

所以建议如下：
方案一：增加自定义执行时间，可以设定固定在某个时间执行一次，与倒计时逻辑无关；
方案二：增加无限循环的起始时间和终止时间自定义，在起始时间执行第一次，中间的过程和现在保持一致；在终止时间执行最后一次，但是下一次执行时间为下一个循环的第一次。
例如：设定每天7:00到次日0:01为循环执行，那么每天早上7:00执行第一次，次日0:01执行最后一次，然后下一次为次日7:00；如此循环。

多谢！

**Comment by TonyJiangWJ** [comment]
感谢支持，另外你说的这些其实已经可以实现了，而且我自己使用已经这么做了，并不需要在脚本中去增加代码。
针对第一点，直接定义每天零点钟的定时任务就行。
具体的自定义脚本已经写好了，只需要你自己针对它们增加定时任务即可：
- `unit` 下提供了多个自定义模式的切换脚本，执行后会自动打断当前运行中的脚本然后按新的设置启动。
  - `自定义1永不停止.js` 25-35分钟的随机范围轮询一次，有倒计时按倒计时时间执行，适合9-23点。可以对它设置每天9点的定时任务
  - `自定义2计时停止.js` 按倒计时时间执行，最长等待时间60分钟，适合早上执行和晚上23点执行，避免0点后继续无意义的永不停止。可以对它设置7点、23点以及0点的定时任务
  - `自定义3循环千次只收自己.js` 循环收集自己的，适合自己能量快要生成的时候执行，因为每天步行能量生成时间是固定的，因此在生成前一分钟设置定时任务即可，然后再设置2分钟后的定时任务`自定义2计时停止.js`
  - 其他自定义方式请自行创建，内容参考以上文件和config.js中的字段

**Comment by Prophetia086** [comment]
收到，感谢回复。我去试试。😁
