### ISSUE TITLE
好友的非两边的球无法收集

### ISSUE THREAD

**Issue by SimonKly** [TonyJiangWJ/Ant-Forest#77]
基础环境
手机：mix2s
autojs:使用的是你推荐的版本

使用的是master分支代码

使用默认配置的，会有好友的非两侧的能量球无法收集

其中debug日志`找到可收取和和帮助的点集合`也看见打印了具体可收集球的信息

目前问题定位在你代码的BaseScanner.js的358行的判断，我没有看懂具体逻辑。我暴力的把这个判断注释了之后就可以正常的收集了

随便说一下，大神钦佩。能否加个联系方式，学习膜拜

**Comment by TonyJiangWJ** [comment]
358行是能量球所在区域，因为有时候会识别到其他区域的球并且误判成了可收取，比如之前有个仙人掌树的胳膊就会误判，还有有时候的活动图标也会误判，所以加了这个限制。
具体区域范围是自动计算的，计算结果可以运行config.js之后点击进阶配置，查看 `当前自动设置的能量球所在区域`，可以勾一下 `下次运行时自动判断能量球所在区域` 使得脚本重新自动计算；你这个估计是计算有误了也许重新计算也会有问题，目前没有加手动输入的功能
你可以加一下原作者的群，我是群管理 524611323；加群答案是 Nick-Hopps

**Comment by SimonKly** [comment]
感谢回复。
你说的那个配置我这边用起来不生效
