### ISSUE TITLE
最近经常遇到进入好友页面但是不收取的情况

### ISSUE THREAD

**Issue by Prophetia086** [TonyJiangWJ/Ant-Forest#78]
这个问题大概出现了一周了，具体现象是这样的：
1、进入自己的主页，收取能量，没问题；
2、随便逛一逛，逛到了某个好友有能量，但是进入页面没有任何操作，马上就返回了；
3、然后看排行榜，看到了有小手，点击进入好友页面，也不收取，再返回到列表，提示“上次收取有遗漏，重新执行”；
4、然后不再逛列表，直接回到首页重新执行，但是逛到好友的能量之后，又重复第二步。

一般情况下，重复3-4遍就会收取，但是也出现过重复5遍左右，直接退出，不收取了的情况。

第一个问题是，第三步，我记得以前发现有遗漏也要把排行榜逛完，现在是改了规则吗？

第二个问题是，第二步，我看了日志，进入好友页面后，有两个超时，分别是：
"try to find one: 使用了保护罩 timeout:500ms
try to find one: 你收取TA timeout:8000ms"
随后找到了球的位置，但是继续报错：
"can not find any matches 使用了保护罩
timeout for finding 使用了保护罩
not found using protect info
等待能量保护罩检测结束：true
未找到匹配的可收取或帮助的点"

然后就准备逛下一个了
请问为什么会出现查找保护罩名单超时的情况呢？我删除了所有脚本，清楚了缓存和数据，全部重新加载，也是一样的。需要怎么解决呢？
谢谢！

**Comment by TonyJiangWJ** [comment]
保护罩这个你无需关心，从内容看就是没有识别到能量球。
首先确认一下你有没有开启深色模式或者护眼模式，然后下载最新的master代码，在有能量球的页面运行一下unit/TestDetectBallByHough.js 然后截图一下回复

**Comment by Prophetia086** [comment]
![Screenshot_20201125-000514_Alipay](https://user-images.githubusercontent.com/73395827/100170433-a6ceac80-2f00-11eb-987b-1dc694e563cc.png)
是这个吗？

**Comment by TonyJiangWJ** [comment]
不是，随缘收吧
