### ISSUE TITLE
最新版1.2.0.5收取好友失败

### ISSUE THREAD

**Issue by baocq2019** [TonyJiangWJ/Ant-Forest#8]
依旧在好友列表下拉两次之后，停滞，脚本重启。

**Comment by TonyJiangWJ** [comment]
给个日志看看，强制关闭AutoJS然后重新运行
- 现在有两条路
1. 修改AutoJS源码 修复这个问题
2. 暂时使用1.2.0.4以前的，然后重新修改脚本

我选择了1，但是暂时不会打包APK，所以你要是关闭AutoJS后重复遇到这个问题 只能先用1.2.0.4以前的了 下载地址[releases](https://github.com/TonyJiangWJ/Ant-Forest/releases)页面对应的[1.2.0.4-zip](https://github.com/TonyJiangWJ/Ant-Forest/archive/v1.2.0.4.zip)

**Comment by 460176980** [comment]
> 
> 
> 给个日志看看，强制关闭AutoJS然后重新运行
> 
>     * 现在有两条路
> 
> 
>     1. 修改AutoJS源码 修复这个问题
> 
>     2. 暂时使用1.2.0.4以前的，然后重新修改脚本
> 
> 
> 我选择了1，但是暂时不会打包APK，所以你要是关闭AutoJS后重复遇到这个问题 只能先用1.2.0.4以前的了 下载地址[releases](https://github.com/TonyJiangWJ/Ant-Forest/releases)页面对应的[1.2.0.4-zip](https://github.com/TonyJiangWJ/Ant-Forest/archive/v1.2.0.4.zip)
12月10日支付宝更新比较大，可以使用2019年11月份的支付宝版本，支付宝功能使用不影响，同时可以使用过去已有的autojs代码实现。因为图像识别可能会有误差，最好的解决办法就是修改支付宝版本。如果需要旧版支付宝可以邮箱我460176980@qq.com。
