### ISSUE TITLE
能否增加自动登录支付宝的功能

### ISSUE THREAD

**Issue by vincenthsing** [TonyJiangWJ/Ant-Forest#81]
相信不少朋友主力机是iphone的，支付宝这种高频应用自然也会登录在iphone上。
但是也想用这个项目去实现每天早上自动偷能量，睡个安稳觉。
现在是每天晚上睡前要手动在android手机上登录下支付宝，才能保证第二天早上能顺利偷能量。
所以不知道这种场景下是不是有合适的方案来实现自动登录支付宝，再自动收集能量。

按照安卓的登录方式来说：
1.直接配置明文密码，然后自动输入，自动登录，这个方案相对不安全，但是可行性最高。
2.短信验证码登录，这个就要求淘宝绑定的手机号装在安卓机上，局限性比较大
3.我在ios上看到有淘宝登录，安卓上没找到，不知道是不是我姿势不对。淘宝是支持多端登录的

能不能劳烦大佬评估下，是不是可行呀？感谢付出！

**Comment by TonyJiangWJ** [comment]
多设备登录除了密码有时候还需要验证人脸的 放弃吧

**Comment by vincenthsing** [comment]
> 多设备登录除了密码有时候还需要验证人脸的 放弃吧

不是第一次登录的设备而是登录过的设备，我印象中都不需要人脸哦，都是密码登录

**Comment by TonyJiangWJ** [comment]
要的 我经常在两台手机上切换，这个主要受蚂蚁风控影响。
单台设备切换不同账号是不需要人脸验证，多设备切换同个账号就会看情况人脸验证

**Comment by TonyJiangWJ** [comment]
另外没记错的话这一个脚本里面应该是有账号切换功能的 你可以尝试一下 https://github.com/SuperMonster003/Ant-Forest

**Comment by vincenthsing** [comment]
> 另外没记错的话这一个脚本里面应该是有账号切换功能的 你可以尝试一下 https://github.com/SuperMonster003/Ant-Forest
好的，非常感谢，那我就关了
