### ISSUE TITLE
昨天开始无法收取或帮收取好友的能力

### ISSUE THREAD

**Issue by iciness** [TonyJiangWJ/Ant-Forest#83]
脚本版本：1.3.4.4.1

https://user-images.githubusercontent.com/4505686/103262641-80f56580-49e0-11eb-8f4a-078c023f093d.mp4

**Comment by TonyJiangWJ** [comment]
提供一下日志，光看视频没法分析

**Comment by iciness** [comment]
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5751271/log-verboses.log)

**Comment by iciness** [comment]
![unknow_not_found_3850](https://user-images.githubusercontent.com/4505686/103296905-153be880-4a32-11eb-86dc-d509670c4fbb.png)
![unknow_not_found_7921](https://user-images.githubusercontent.com/4505686/103296909-1705ac00-4a32-11eb-9c06-8310becc06a7.png)
![unknow_not_found_8238](https://user-images.githubusercontent.com/4505686/103296911-1836d900-4a32-11eb-8817-b261fc38cfc0.png)
![unknow_not_found_10005](https://user-images.githubusercontent.com/4505686/103296917-19680600-4a32-11eb-9e45-86f6c0d2b663.png)
![Screenshot_20201229_235701_com eg android AlipayGphone](https://user-images.githubusercontent.com/4505686/103296920-1c62f680-4a32-11eb-93e4-d9b19e9ead46.jpg)
![unknow_not_found_3081](https://user-images.githubusercontent.com/4505686/103296922-1c62f680-4a32-11eb-8614-fb80f25c2f9a.png)
另外设置中，开发模式中打开是否保存一些开发用数据的话，无法正常执行

**Comment by iciness** [comment]
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5751314/log-verboses.log)
这个是开启开发模式是否保存一些开发数据后的日志

**Comment by TonyJiangWJ** [comment]
尝试修改一下core/BaseScanner.js第30行 1080改为1176
  let SCALE_RATE = _config.device_width / 1176

**Comment by iciness** [comment]
有效，谢谢🤗

**Comment by iciness** [comment]
新的问题出现，找能量完后，进入排行榜后无划屏，提示报错后重启
[log-verboses.202012301530.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5753372/log-verboses.202012301530.log)

**Comment by TonyJiangWJ** [comment]
```log

2020-12-30 15:30:04.474 WARN [E:46 T:40206] - 等待操作超时, 操作时间: 501ms
2020-12-30 15:30:04.474 WARN [E:46 T:40206] - 获取截图失败 等待截图超时 再试一次 count:1
2020-12-30 15:30:04.976 WARN [E:46 T:40206] - 等待操作超时, 操作时间: 501ms
2020-12-30 15:30:04.982 WARN [E:46 T:40206] - 获取截图失败 等待截图超时 再试一次 count:2
2020-12-30 15:30:05.488 WARN [E:46 T:40206] - 等待操作超时, 操作时间: 502ms
2020-12-30 15:30:05.490 WARN [E:46 T:40206] - 获取截图失败 等待截图超时, 建议将获取截图超时时间加长  count:3
2020-12-30 15:30:05.492 ERROR [E:46 T:40206] - 获取截图失败多次[3], 可能已经没有了截图权限，重新执行脚本

```

异步等待截图的时间默认500毫秒你可以调高一点，或者直接关闭异步等待截图，但是有一定几率卡死不动。建议调整异步等待截图的时间 具体数值需要自己多多尝试

**Comment by iciness** [comment]
好的，我自己尝试下

**Comment by iciness** [comment]
截图改到750   模拟滑动速度改成250后正常了，谢谢

**Comment by TonyJiangWJ** [comment]
昨天发布了新版本，你试试可不可以收能量了。之前没有考虑到非标准的分辨率

**Comment by iciness** [comment]
已更新可以收，但是截图超时和模拟滑动速度还是需要调整

**Comment by TonyJiangWJ** [comment]
截图超时和系统有关，暂时无解
