### ISSUE TITLE
module  is not defined

### ISSUE THREAD

**Issue by shuimuqinghua1** [TonyJiangWJ/Ant-Forest#84]
请问一下在测试ExternalUnlockDevice和unlock时提示module  is not defined这该怎么解决？

**Comment by TonyJiangWJ** [comment]
测试时运行main.js而不是运行ExternalUnlockDevice.js这个文件

**Comment by shuimuqinghua1** [comment]
> 测试时运行main.js而不是运行ExternalUnlockDevice.js这个文件
我是想添加解锁然后运行ExternalUnlockDevice出现了module is not defined

**Comment by TonyJiangWJ** [comment]
添加解锁和运行ExternalUnlockDevice有什么关系。。。ExternalUnlockDevice是一个模块不是拿来运行的

**Comment by shuimuqinghua1** [comment]
啊，我是小白不太懂。我的问题是这样的：我的屏幕有时不能自主唤醒，然后我就想添加一个解锁我就运行了一下ExternalUnlockDevice然后就出现module is not defined

**Comment by TonyJiangWJ** [comment]
...不是和你说了运行main.js吗

**Comment by shuimuqinghua1** [comment]
啊，可能是我表述有问题，我的意思是我设置完定时任务之后手机不能自主唤醒，运行的是main.js。要解决这个问题解锁里面该怎么改呀

**Comment by TonyJiangWJ** [comment]
![image](https://user-images.githubusercontent.com/11325805/103396873-897ca600-4b70-11eb-8b5e-8c1d637336f1.png)

**Comment by shuimuqinghua1** [comment]
[info.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5756571/info.log)
我的是这样的，后续之后就不知道怎么操作了，得到这个控件信息之后接下来要怎么办呀

**Comment by TonyJiangWJ** [comment]
这个布局信息看起来不应该有问题，华为？
你删除本地的ExternalUnlockDevice和所有的日志文件。
然后锁屏状态下运行main.js 然后发一下对应的日志 log-verboses.log

**Comment by shuimuqinghua1** [comment]
[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5756594/log-verboses.log)
是的华为手机，我设置得定时任务屏幕点不亮，解锁后又自己运行

**Comment by TonyJiangWJ** [comment]
```log
2020-12-31 14:25:34.176 LOG [E:65 T:13498] - ======解锁并校验截图权限======
2020-12-31 14:25:34.178 LOG [E:65 T:13498] - 已解锁
2020-12-31 14:25:34.178 LOG [E:65 T:13498] - 不需要重新锁定屏幕
```

...你别手动解锁啊，你这个问题和解锁没有任何关系，是锁屏后无法触发定时任务吧？
给与AutoJS自启动权限，电量优化全关，再不行就多等个几分钟

**Comment by shuimuqinghua1** [comment]
[log-verboses (2).log](https://github.com/TonyJiangWJ/Ant-Forest/files/5756627/log-verboses.2.log)
设置好定时任务之后等了很久都没反应，手动点亮屏幕之后能够自动解锁完成后续操作

**Comment by TonyJiangWJ** [comment]
那基本可以确认无解了，系统限制了AutoJS没法自动唤醒。
不过也有额外方式，可以尝试一下，下载我修改的版本 [AutoJS Modify](https://github.com/TonyJiangWJ/Auto.js/releases/download/v4.1.1/AutoJS.Modify.latest.apk)
然后解压以下脚本到 脚本 目录下，运行一次 `定期校验一次是否有任务超时.js`, 会创建一个线程循环检测有没有定时任务超时。
[CheckAutoJSTimedTasks.zip](https://github.com/TonyJiangWJ/Ant-Forest/files/5756702/CheckAutoJSTimedTasks.zip)
可能会增加耗电，也有可能在你的手机上无法保证运行，需要将AutoJS常驻后台，开启自启动，关闭电量优化

**Comment by shuimuqinghua1** [comment]
哦哦好吧，谢谢
