### ISSUE TITLE
会点击邀请

### ISSUE THREAD

**Issue by here101** [TonyJiangWJ/Ant-Forest#86]
当好友列表有好友未开通时，会点击邀请，然后一直卡在那个界面，最后退出蚂蚁森林回到auto的界面又重新进入蚂蚁森林。
![按钮](https://user-images.githubusercontent.com/49056220/105341457-14097000-5c1a-11eb-814a-a0aad1b27897.jpg)
![邀请](https://user-images.githubusercontent.com/49056220/105341463-153a9d00-5c1a-11eb-9e6a-7b8419987b81.jpg)

**Comment by TonyJiangWJ** [comment]
该问题已修复，但是还在优化其他代码，临时解决方案：
core/ImgBasedFriendListScanner.js 260行尝试添加以下代码
```javascript
    if (point.regionSame > 4500) {
        return
    }
```
![image](https://user-images.githubusercontent.com/11325805/105342744-b2e29c00-5c1b-11eb-84f2-ecb514aa89bd.png)

**Comment by TonyJiangWJ** [comment]
已修复
