### ISSUE TITLE
我执行了“获取锁屏界面控件信息.js”文件，不知道怎么编写解锁屏幕的代码

### ISSUE THREAD

**Issue by linfeizheng** [TonyJiangWJ/Ant-Forest#90]
我执行了“获取锁屏界面控件信息.js”文件，不知道怎么编写解锁屏幕的代码
下面是info.log的内容
可否启发一下，给个例子

`info logs for [2021-01-29 19:01:46]
2021-01-29 19:02:01.442 总分析耗时：5338ms 总控件数：51

=================
锁屏界面:
分析耗时：142ms
控件总数：24
分析控件内容：
-[1:0]id:[com.android.systemui:id/notification_panel]bounds:[0, 0, 1080, 2376]
--[2:0]id:[com.android.systemui:id/vivo_flow][desc]content:[今日已用: 28.0MB 本月已用: 7.12GB查看流量监控详情,双击可以激活]bounds:[228, 0, 624, 0]
---[3:0]id:[com.android.systemui:id/flow2][desc]content:[今日已用: 28.0MB 本月已用: 7.12GB]bounds:[228, 0, 588, -6]
--[2:1]id:[com.android.systemui:id/magazine_wallpaper_container][desc]content:[双指上滑即可解锁设备]bounds:[0, 0, 1080, 2376]
---[3:0]id:[com.vivo.magazine:id/wallpaper_info_title]bounds:[600, 2084, 0, 72]
---[3:1]id:[com.vivo.magazine:id/wallpaper_info_description]bounds:[600, 2156, 480, 102]
---[3:2]id:[com.vivo.magazine:id/wallpaper_tag]bounds:[600, 2258, 105, 48]
---[3:3]id:[com.vivo.magazine:id/like_num]bounds:[1512, 2127, -432, 48]
--[2:2]id:[com.android.systemui:id/charge_info]bounds:[540, 0, 0, 65]
--[2:3]id:[com.android.systemui:id/tv_time][desc]content:[19:01]bounds:[54, 171, 334, 199]
--[2:4]id:[com.android.systemui:id/tv_date][desc]content:[1月29日   星期五]bounds:[63, 382, 309, 57]
--[2:5]id:[com.android.systemui:id/tv_lunar][desc]content:[庚子(鼠)年腊月十七]bounds:[63, 451, 366, 57]
--[2:6]id:[com.android.systemui:id/tv_battery_info][desc]content:[正在充电 86%]bounds:[63, 520, 271, 57]
--[2:7]id:[com.android.systemui:id/vivo_face_unlock_icon]bounds:[507, 1682, 66, 87]
--[2:8]id:[com.android.systemui:id/vivo_face_unlock_tips]bounds:[540, 1805, 0, 48]
--[2:9]id:[com.android.systemui:id/left_shortcut][desc]content:[电话]bounds:[0, 2181, 195, 195]
--[2:10]id:[com.android.systemui:id/right_shortcut][desc]content:[相机]bounds:[885, 2181, 195, 195]
-[1:1]id:[com.android.systemui:id/mobile_type_signal_sim2][desc]content:[5G信号4格]bounds:[171, 49, 60, 33]
-[1:2][desc]content:[Android 系统通知：作为媒体设备连接]bounds:[276, 43, 30, 45]
-[1:3][desc]content:[systemui.irrelevent.icon]bounds:[321, 43, 30, 45]
-[1:4]id:[com.android.systemui:id/battery][desc]content:[电池电量为百分之 86。]bounds:[930, 51, 90, 30]
-[1:5]id:[com.android.systemui:id/battery_level][desc]content:[86%]bounds:[845, 45, 79, 41]
-[1:6]id:[com.android.systemui:id/wifi_combo]bounds:[796, 51, 49, 30]
-[1:7]id:[com.android.systemui:id/vivo_airplane_mode_icon][desc]content:[飞行模式]bounds:[465, 33, 42, 66]
=================
密码输入界面:
分析耗时：132ms
控件总数：27
分析控件内容：
--[2:0]id:[com.android.systemui:id/keyguard_host_view]bounds:[0, 0, 1080, 2376]
---[3:0]id:[com.android.systemui:id/vivo_pin_view]bounds:[0, 75, 1080, 2301]
----[4:0]id:[com.android.systemui:id/vivo_bouncer_face_icon]bounds:[440, 566, 200, 180]
----[4:1]id:[com.android.systemui:id/vivo_message_title][desc]content:[使用指纹、面部或输入密码]bounds:[0, 806, 1080, 72]
----[4:2]id:[com.android.systemui:id/vivo_message_area]bounds:[0, 878, 1080, 57]
----[4:3]id:[com.android.systemui:id/VivoPinkey1][desc]content:[1]bounds:[168, 1131, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[1]bounds:[237, 1165, 42, 112]
----[4:4]id:[com.android.systemui:id/VivoPinkey2][desc]content:[2]bounds:[450, 1131, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[2]bounds:[515, 1165, 50, 112]
----[4:5]id:[com.android.systemui:id/VivoPinkey3][desc]content:[3]bounds:[732, 1131, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[3]bounds:[797, 1165, 50, 112]
----[4:6]id:[com.android.systemui:id/VivoPinkey4][desc]content:[4]bounds:[168, 1353, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[4]bounds:[232, 1387, 53, 112]
----[4:7]id:[com.android.systemui:id/VivoPinkey5][desc]content:[5]bounds:[450, 1353, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[5]bounds:[515, 1387, 50, 112]
----[4:8]id:[com.android.systemui:id/VivoPinkey6][desc]content:[6]bounds:[732, 1353, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[6]bounds:[797, 1387, 51, 112]
----[4:9]id:[com.android.systemui:id/VivoPinkey7][desc]content:[7]bounds:[168, 1575, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[7]bounds:[235, 1609, 47, 112]
----[4:10]id:[com.android.systemui:id/VivoPinkey8][desc]content:[8]bounds:[450, 1575, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[8]bounds:[515, 1609, 51, 112]
----[4:11]id:[com.android.systemui:id/VivoPinkey9][desc]content:[9]bounds:[732, 1575, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[9]bounds:[797, 1609, 51, 112]
----[4:12]id:[com.android.systemui:id/VivoPinkey0][desc]content:[0]bounds:[450, 1797, 180, 180]
-----[5:1]id:[com.android.systemui:id/vivo_digit_text][desc]content:[0]bounds:[515, 1831, 51, 112]
----[4:13]id:[com.android.systemui:id/VivoPinEmergency][desc]content:[紧急拨号]bounds:[72, 2211, 264, 120]
----[4:14]id:[com.android.systemui:id/vivo_cancel][desc]content:[取消]bounds:[744, 2211, 264, 120]
`

**Comment by TonyJiangWJ** [comment]
在 `extends/` 下创建文件 `ExternalUnlockDevice.js` ，然后将以下内容写入并保存，试试能不能解锁
```javascript
let { config: _config } = require('../config.js')(runtime, this)
module.exports = function (obj) {
  this.__proto__ = obj

  this.unlock = function (password) {
    // 自行定制化解锁方式，这里展示PIN密码的解锁
    if (typeof password !== 'string') throw new Error('密码应为字符串！')
    // 模拟按键
    let button = null
    for (let i = 0; i < password.length; i++) {
      let key_id = 'com.android.systemui:id/VivoPinkey' + password[i]
      if ((button = id(key_id).findOne(_config.timeout_findOne)) !== null) {
        button.click()
      }
      sleep(100)
    }
    // 解锁完毕后返回check_unlock方法，模块自动判断是否成功
    return this.check_unlock()
  }
  
}


```

**Comment by linfeizheng** [comment]
我已新建ExternalUnlockDevice.js文件并拷贝了ExternalUnlockDevice-demo.js里面的代码，不知应将我的PIN码写在何处

**Comment by TonyJiangWJ** [comment]
密码的话 运行 `可视化配置.js` 然后在 `锁屏相关` - `锁屏密码` 输入即可，关闭后自动保存
![image](https://user-images.githubusercontent.com/11325805/106268643-59571e80-6266-11eb-9eca-8526fbdba337.png)

**Comment by linfeizheng** [comment]
屏幕亮起后未曾输入密码
见附件

https://user-images.githubusercontent.com/9878167/106269755-e353b700-6267-11eb-9671-1096e5cfaec0.mp4

**Comment by linfeizheng** [comment]
锁屏密码我已正确输入

**Comment by TonyJiangWJ** [comment]
删除日志文件重新运行一遍，然后上传一下，我看看具体日志
日志文件位置 `logs/log-verboses.log`

**Comment by linfeizheng** [comment]
请看附件

[log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/5893646/log-verboses.log)

**Comment by TonyJiangWJ** [comment]
从日志看并没有生效，确认一下是否成功保存在了 `extends/ExternalUnlockDevice.js` 下，注意文件名称 没有 `-demo` 后缀
```log
2021-01-29 19:49:11.278 LOG [E:8 T:2323] - 使用内置解锁模块
```

另外重新替换一下内容，我补充了一些日志

```javascript

let { config: _config } = require('../config.js')(runtime, this)
let singletonRequire = require('./SingletonRequirer.js')(runtime, this)
let automator = singletonRequire('Automator')
let { logInfo, errorInfo, warnInfo, debugInfo } = singletonRequire('LogUtils')
module.exports = function (obj) {
  this.__proto__ = obj

  this.unlock = function (password) {
    // 自行定制化解锁方式，这里展示PIN密码的解锁
    if (typeof password !== 'string') throw new Error('密码应为字符串！')
    if (id('com.android.systemui:id/VivoPinkey1').findOne(1000)) {
      logInfo('进入密码界面成功')
    }
    // 模拟按键
    let button = null
    for (let i = 0; i < password.length; i++) {
      let key_id = 'com.android.systemui:id/VivoPinkey' + password[i]
      if ((button = id(key_id).findOne(_config.timeout_findOne)) !== null) {
        logInfo(['找到了第{}个密码按钮', i + 1])
        automator.clickCenter(button)
        logInfo('按钮点击完毕 执行下一个')
      }
      sleep(100)
    }
    // 解锁完毕后返回check_unlock方法，模块自动判断是否成功
    return this.check_unlock()
  }
  
}

```

**Comment by linfeizheng** [comment]
缺少一个引用文件

![Screenshot_20210129_195930](https://user-images.githubusercontent.com/9878167/106272792-932b2380-626c-11eb-9179-c63ed7242541.jpg)

**Comment by TonyJiangWJ** [comment]
已修改 重新复制一下

**Comment by linfeizheng** [comment]
是我将ExternalUnlockDevice.js文件放在了根目录下，我移到extends下已经可以解锁，非常感谢

**Comment by linfeizheng** [comment]
我想设置每天7点10分自动偷能量，之后每隔5分钟偷一次，如何设置，
我只知道在定时任务中开启每天定时偷，但不知道之后每隔5分钟偷一次如何设置

**Comment by TonyJiangWJ** [comment]
正常情况下会自动识别倒计时，按实际获取的最小倒计时再次启动（默认是小于60，超过的就会停止直到下次手动执行或者手动设置的定时启动）；
如果想5分钟不停的话需要在设置里面开启 `永不停止` 然后 `重新激活时间` 改为5分钟，此时如果识别到的倒计时小于5分钟按实际倒计时定时，超过了则按5分钟计时；不太推荐5分钟这么短，你可以设置长一点 比如我平常是设置 45-55 分钟的随机时间

**Comment by linfeizheng** [comment]
当我的autojs偷完一轮后，会不停的点击排行榜最后一行，如附件所示，是何原因
我想当他偷完一轮后停止操作脚本

https://user-images.githubusercontent.com/9878167/106344592-a29a8300-62e5-11eb-98d0-c8d697c9527c.mp4

**Comment by TonyJiangWJ** [comment]
排行榜底部识别失败了，参考一下README中的描述 手动修改一下底部识别区域

**Comment by linfeizheng** [comment]
thanks
