### ISSUE TITLE
倒计时不准确的问题

### ISSUE THREAD

**Issue by linfeizheng** [TonyJiangWJ/Ant-Forest#92]
我会在晚上将循环时间改为5分钟，早上睡醒之后(已偷好自己和好友的步数能量)将时间改为半小时，我发现倒计时时间完全不对，显示的下次运行时间完全摸不着规律，我想知道，更改循环时间的正确步骤是啥，现在好像，会被上一次的循环时间影响

**Comment by TonyJiangWJ** [comment]
你指的倒计时不准 是识别不准还是计划任务的执行时间不准？
如果是识别不准请更新到最新版

**Comment by linfeizheng** [comment]
执行完一次采集能量后，左上角显示的‘距离下次运行还有XX分’这个时间不是我设置的时间，
当XX分到的时候是会执行的
（另外，如何更新，是clone最新代码后再次放到手机吗）

**Comment by TonyJiangWJ** [comment]
这个是识别的倒计时时间 具体如何更新README有写

**Comment by linfeizheng** [comment]
我想要在每日7点15开始收取能量，并且之后每2分钟获取一次，
我现在是设置的每日7点15的定时任务，并且**每天晚上睡前先杀掉APP后台，再次打开APP后将激活时间设置为2分钟**，
这是不是最好的配置方式，
readme我已看完，有以上困惑

**Comment by TonyJiangWJ** [comment]
也没有所谓最好或者最坏的配置 完全看个人喜好

### 循环/计时模式、永不停止模式等详细说明

- 循环模式：脚本会根据设置的次数不间断的循环执行直到当前执行了指定次数之后便会停止。
- 计时模式：当关闭循环模式，且不开启永不停止模式时，启用计时模式。计时模式需要设置最大等待时间，默认为60分钟，脚本执行时会通过OCR识别排行榜中的倒计时时间，如果得到的最小倒计时时间小于最大等待时间，那么脚本将会按识别到的最小倒计时计时启动，否则脚本将退出执行。
- 永不停止模式：关闭循环模式并开启永不停止，此时需要设置重新激活时间，当识别到的倒计时时间小于这个重新激活时间时，脚本会按实际倒计时计时启动，当识别到的倒计时时间大于重新激活时间时，则按重新激活时间来计时启动。以此循环实现全天不间断的执行。这个重新激活时间可以设置为一个随机范围，每次判断都会在指定范围内生成一个随机的时间。
- 以上计时模式和永不停止模式依赖于OCR的正常运行，如果设备分辨率为1080P的建议直接将自建OCR识别和百度OCR识别关闭，此时会启用模拟的识别，准确率和速度都相较OCR来说更理想。其他分辨率设备则没怎么测试过，自行斟酌。

**Comment by linfeizheng** [comment]
请问我框出来的“识别到的倒计时时间”是什么，永不停止模式不是以激活时间作为唯一倒计时吗

![微信截图_20210207173526](https://user-images.githubusercontent.com/9878167/107142556-e5ee9480-696a-11eb-9e69-4bbad7605a2f.png)

**Comment by linfeizheng** [comment]
![微信截图_20210207173526](https://user-images.githubusercontent.com/9878167/107142607-382fb580-696b-11eb-8be9-004a95926940.png)

**Comment by linfeizheng** [comment]
永不停止模式：关闭循环模式并开启永不停止，此时需要设置重新激活时间，当**识别到的倒计时时间**小于这个重新激活时间时

**Comment by TonyJiangWJ** [comment]
。。。第四点不写了吗 OCR

**Comment by linfeizheng** [comment]
谢谢！
