### ISSUE TITLE
作者你好，脚本很好用，想问个问题

### ISSUE THREAD

**Issue by PeterPuffer** [TonyJiangWJ/Ant-Forest#93]
我的autojs设置了定时任务后, 如果到该执行的时间了，但是autojs后台被清理, 此时无法唤醒支付宝, 只会有个toast提示【未找到允许截图按钮，查找内容为xxx】, 我寻思在脚本每次启动前都先自动启动autojs, 但是在main.js 的开头加了 app.launchPackage("org.autojs.autojs") 也并不奏效。

请问作者有碰到过这个问题吗, 是如何解决的呢?

所有权限都打开了, 如果执行定时任务时autojs在后台没有被关闭/在前台 的的话就可以正常启动脚本。
机型：RedMI K30 Pro
系统版本: MIUI 12
是否Root: 是

**Comment by TonyJiangWJ** [comment]
没遇到过，如果只是因为AutoJS在后台没法启动的话看一下有没有赋予AutoJS权限：`后台弹出界面`

**Comment by PeterPuffer** [comment]
作者你好, 很开心得到你的答复。 目前我用的解决办法很临时 但是有效果, 我在main.js的第一行打开了控制台，并将控制台的位置移动到了屏幕最左边, 这样就可以保证autojs被正常唤醒. 在程序结束后console.hide()关闭控制台 😂 目前我是这么解决的 如果后续遇到其他的问题在像作者请教吧~
