### ISSUE TITLE
打开可视化配置白屏

### ISSUE THREAD

**Issue by BIGMONK** [TonyJiangWJ/Ant-Forest#95]
**问题描述**

打开可视化配置白屏
![image](https://user-images.githubusercontent.com/18308637/113380458-dd389e80-93ae-11eb-8297-170dc7ac129f.png)

**软件硬件信息**
操作系统: 安卓10
设备型号: 小米8  
Auto.js版本:  4.1.1 Alpha2

**Comment by TonyJiangWJ** [comment]
看一眼日志有没有报错

**Comment by BIGMONK** [comment]
![image](https://user-images.githubusercontent.com/18308637/113435270-0724ac00-9415-11eb-8ddd-a5b32c65f570.png)
没有错误日志

**Comment by TonyJiangWJ** [comment]
。。。。。右上角 日志界面截图 你截图这个看个啥？

**Comment by BIGMONK** [comment]
![image](https://user-images.githubusercontent.com/18308637/113437854-fc204a80-9419-11eb-9220-30028a6e97f2.png)
![image](https://user-images.githubusercontent.com/18308637/113437880-0b9f9380-941a-11eb-9b73-5dd6e1afe368.png)

**Comment by TonyJiangWJ** [comment]
Vue is not defined 检查一下是不是禁用了AutoJS的网络访问权限，或者重新更新一下最新版目前代码是没问题的，你这个目测是无法正确加载vue的包

**Comment by BIGMONK** [comment]
果然是网络的问题，谢谢谢谢谢
