### ISSUE TITLE
刷列表时碰到小手会卡住

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Ant-Forest#98]
我勾选了列表中仅识别倒计时，但刷到小手时会停住不动，如果我手动点进去收了再出来到列表、或者我手动往下刷一下过了小手，就会继续刷列表。

**Comment by TonyJiangWJ** [comment]
提供一下日志文件 `logs/log-verboses.log`

**Comment by williamglasgow** [comment]
[8_log-verboses.log](https://github.com/TonyJiangWJ/Ant-Forest/files/6395824/8_log-verboses.log)

**Comment by williamglasgow** [comment]
不好意思慢了点。
运行了一次，逛一逛进入这个可收集的人的瞬间故意又点了下逛一逛以跳过。然后就开始刷列表，刷到这个小手就卡主，我手动点进去收了，然后出来还卡着，我划了一下又开始继续刷列表了

**Comment by TonyJiangWJ** [comment]
`core/ImgBasedFriendListScanner.js` 的第423行加上如下代码试试 ```countdownLatch.countDown()```

```javascript 
    this.solveCollectable = function (point, listWriteLock, countdownLatch, collectOrHelpList) {
    if (_config.collect_by_stroll_only) {
      countdownLatch.countDown()  // 增加这行代码
      return true
    }
```

**Comment by williamglasgow** [comment]
观察了两轮，没问题了！

**Comment by TonyJiangWJ** [comment]
是个隐藏bug了 一直没发现 哈哈
